/**
 * Pure render of one route → one Caddyfile site block.
 *
 * The existing client.js wrote site blocks imperatively, with no
 * concept of source-IP gating. Step 7b adds an optional
 * `vpn_only: 1` flag (plus optional `service` tag) on each route;
 * routes flagged vpn_only render with a per-peer remote_ip matcher
 * so only specific WireGuard peers' /32s reach the upstream, and
 * every other source gets a 403.
 *
 * This module is pure: no fs, no Caddy admin API, no SQLite. The
 * caller passes the route row + the resolved peer set, and gets a
 * site-block string. Side effects (atomic write, reload) live in
 * reconcile.js. Matching firewall manager's render.js / reconcile.js
 * split — same reasoning: pure render is unit-testable in isolation
 * and produces byte-identical output for byte-identical input.
 */

/**
 * Sentinel /32 for "no allowed peers". Caddy's remote_ip matcher
 * with a single never-routable address is equivalent to "match
 * nothing", so Caddy returns 403 for every real source. Mirrors the
 * firewall-side broadcast sentinel (255.255.255.255/32) introduced
 * in step 7a/4: "rule effectively closed, render explicitly so the
 * operator can see the closed state in the rendered config".
 *
 * Caddy 2.x's remote_ip matcher rejects an empty argument list
 * ("matchers must specify at least one address"), so emitting an
 * explicit sentinel is required — the alternative (omitting the
 * matcher) would either reverse-proxy to everyone or silently drop
 * the route block, both worse than a 403.
 */
const NO_ALLOWED_PEERS_SENTINEL = '255.255.255.255/32';

/**
 * Resolve a route's peer-allow list against the enabled-peer set.
 * Identical join semantics to firewall reconcile's resolveVpnSources():
 *   - every full + admin peer's /32 is included unconditionally
 *   - every services-scope peer's /32 is included only when the
 *     route's `service` tag appears in the peer's scope_services_json
 *
 * Returns a sorted /32 list. Sort by trailing octet so the rendered
 * Caddyfile is byte-identical for an unchanged peer set, matching
 * the IP-pool picker and resolveVpnSources()'s sort order.
 */
export function resolveRoutePeers(route, peers) {
  const fullAdmin = peers
    .filter(p => p.scope === 'full' || p.scope === 'admin')
    .map(p => `${p.allowed_ip}/32`);
  const services = peers
    .filter(p => p.scope === 'services')
    .map(p => ({
      cidr: `${p.allowed_ip}/32`,
      tags: p.scope_services_json ? JSON.parse(p.scope_services_json) : [],
    }));
  const allowed = new Set(fullAdmin);
  if (route.service) {
    for (const sp of services) {
      if (sp.tags.includes(route.service)) allowed.add(sp.cidr);
    }
  }
  return [...allowed].sort((a, b) => {
    const ao = Number(a.split('/')[0].split('.')[3]);
    const bo = Number(b.split('/')[0].split('.')[3]);
    return ao - bo;
  });
}

/**
 * Render a route to a Caddyfile site block string.
 *
 * For non-vpn-only routes: same shape as the imperative path in
 * client.js — site address, optional path-prefix handle,
 * reverse_proxy, security headers, log directive. Kept identical
 * so swapping client.js's imperative writeFile() for this pure
 * render is a behavior-preserving refactor for the public-internet
 * case.
 *
 * For vpn-only routes: the reverse_proxy is wrapped in a
 * `handle @vpn-<routeid> { ... }` block, and a `handle { respond 403 }`
 * fallthrough denies anyone outside the matcher. The matcher
 * enumerates the resolved /32 list (or the sentinel above when
 * empty). Logging stays at site scope so a denied request still
 * logs.
 */
export function renderRoute(route, peers = []) {
  const {
    domain,
    upstream_address,
    path_prefix = '/',
    tls_auto = 1,
    vpn_only = 0,
  } = route;
  if (!domain) throw new Error('renderRoute: route.domain is required');
  if (!upstream_address) throw new Error('renderRoute: route.upstream_address is required');

  const siteAddress = tls_auto ? domain : `http://${domain}`;
  const lines = [];
  lines.push(`# ProxyPilot Managed Route`);
  lines.push(`# Generated by ProxyPilot. Do not edit by hand.`);
  lines.push(``);
  lines.push(`${siteAddress} {`);

  if (vpn_only) {
    const sources = resolveRoutePeers(route, peers);
    const matcherIps = sources.length > 0 ? sources : [NO_ALLOWED_PEERS_SENTINEL];
    // Caddyfile matcher names are scoped per-site, so a fixed
    // `@vpn` name is unambiguous regardless of how many vpn-only
    // routes exist. Avoiding a per-route id also lets the
    // imperative addRoute() path render the Caddyfile before the
    // SQLite INSERT (which is where the id lives) without needing
    // to reorder lxc create's all-or-nothing flow.
    lines.push(`    @vpn remote_ip ${matcherIps.join(' ')}`);
    lines.push(``);
    lines.push(`    handle @vpn {`);
    if (path_prefix !== '/') {
      lines.push(`        handle ${path_prefix}* {`);
      lines.push(`            reverse_proxy ${upstream_address}`);
      lines.push(`        }`);
    } else {
      lines.push(`        reverse_proxy ${upstream_address}`);
    }
    lines.push(`    }`);
    lines.push(``);
    // Fallthrough: anything that didn't hit the matcher (i.e. any
    // source not on the allow list) returns 403. We do NOT skip the
    // site block when the matcher is empty — "no allowed peers" is
    // meaningful state and must surface as a 403, not a 404 or a
    // missing site.
    lines.push(`    handle {`);
    lines.push(`        respond 403`);
    lines.push(`    }`);
  } else if (path_prefix !== '/') {
    lines.push(`    handle ${path_prefix}* {`);
    lines.push(`        reverse_proxy ${upstream_address}`);
    lines.push(`    }`);
  } else {
    lines.push(`    reverse_proxy ${upstream_address}`);
  }

  lines.push(``);
  lines.push(`    header {`);
  lines.push(`        X-Frame-Options "SAMEORIGIN"`);
  lines.push(`        X-Content-Type-Options "nosniff"`);
  lines.push(`        X-XSS-Protection "1; mode=block"`);
  lines.push(`        Referrer-Policy "strict-origin-when-cross-origin"`);
  lines.push(`    }`);
  lines.push(``);
  lines.push(`    log {`);
  lines.push(`        output file /var/log/caddy/${domain}.log`);
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);

  return lines.join('\n');
}
