// Manual (pasted) TLS certificate API — admin-only management of admin-supplied
// certs that Caddy serves INSTEAD of issuing via ACME, for networks that block
// Let's Encrypt. All mutations run the same pipeline: validate (cert well-formed,
// key matches, passphrase ok) → store (key encrypted at rest) → materialize
// files (0600 key) → regenerate + `caddy adapt` (validate) + `caddy reload`,
// with rollback if Caddy rejects the config, so a bad paste can never take the
// proxy down. Every create/rotate/delete + apply is audit-logged.
//
// Security (cid-security): authenticateToken + requireAdmin on every route,
// requireSudo on mutations; the private key is never returned (GET is metadata +
// public PEM only) and never logged (errors are redacted).

import { Router } from 'express';
import { z } from 'zod';
import { authenticateToken, requireAdmin, requireSudo } from '../middleware/auth.js';
import { getDb, logAudit, getSetting, setSetting } from '../db.js';
import { caddyAdapt, caddyReload } from '../lib/caddy-driver.js';
import { regenerateDomainCaddyConfig, ensureCaddyStructure } from './services.js';
import { reconcileMock2Domains } from '../mock2/reconcile.js';
import {
  validateCertKeyPair, assembleServedChain, certCoversHost, redactKeyMaterial,
} from '../lib/tls-certs.js';
import {
  insertCert, updateCert, deleteCertRow, getCertRow, listCertRows, certPublicShape,
  materializeCertFiles, removeCertFiles, servedChainForRow, getCertKeyPem, currentTlsMode,
  reconcileAdminTls,
} from '../lib/tls-cert-store.js';

export const tlsCertsRouter = Router();
const router = tlsCertsRouter;

const CONFIG_FILE = process.env.CADDY_CONFIG_FILE || '/etc/caddy/Caddyfile';

// ---- input schemas ----
const pemCert = z.string().trim().min(1).max(200000);
const pemBlob = z.string().trim().max(400000);
const certBodySchema = z.object({
  label: z.string().trim().min(1).max(120),
  certificate: pemCert,
  private_key: z.string().trim().min(1).max(200000),
  chain: pemBlob.optional(),
  passphrase: z.string().max(1024).optional(),
});
// Rotate/replace: same shape, but every field except label optional so a caller
// can update just the label. When cert or key is present, BOTH must be.
const rotateBodySchema = certBodySchema.partial().extend({ label: z.string().trim().min(1).max(120).optional() });
const tlsModeSchema = z.object({ mode: z.enum(['acme', 'manual']) });

// ---- helpers ----

// Service (+ legacy) domains — the ONLY hosts regenerateDomainCaddyConfig owns.
// Provisioned self-service domains are deliberately excluded here: their site
// files are generated by lib/domain-provision-logic, and calling the service
// reconciler on them would find no service rows and DELETE their file.
function serviceHosts() {
  const db = getDb();
  const hosts = new Set();
  try { for (const r of db.prepare('SELECT DISTINCT domain FROM service_http_routes').all()) if (r.domain) hosts.add(r.domain); } catch { /* table may lag */ }
  try { for (const r of db.prepare("SELECT domain FROM services WHERE domain IS NOT NULL AND domain != ''").all()) hosts.add(r.domain); } catch { /* legacy */ }
  return [...hosts];
}

// Every managed HTTP(S) hostname across all subsystems — for REPORTING which
// routes a cert is bound to (read-only; never drives regeneration).
function allManagedHosts() {
  const db = getDb();
  const hosts = new Set(serviceHosts());
  try { for (const r of db.prepare('SELECT domain FROM provisioned_domains').all()) if (r.domain) hosts.add(r.domain); } catch { /* feature may be off */ }
  return [...hosts];
}

function boundHostsFor(coveredNames) {
  return allManagedHosts().filter((h) => certCoversHost(coveredNames, h));
}

// Regenerate every managed service domain so covered sites pick up (or drop) the
// manual `tls` directive, then reconcile mock2 project domains. Pure host/FS work
// — the caller adapts + reloads afterwards.
async function regenerateManagedSites() {
  const db = getDb();
  await ensureCaddyStructure();
  for (const domain of serviceHosts()) {
    try { regenerateDomainCaddyConfig(db, domain); } catch (e) { console.warn('[tls] regenerate failed for', domain, e?.message); }
  }
  try { await reconcileMock2Domains(); } catch (e) { console.warn('[tls] mock2 reconcile failed:', e?.message); }
  // The admin dashboard's own site is not a service host — flip its imported
  // TLS snippet onto the pasted cert here so the admin ORIGIN serves it too
  // (required for Cloudflare "Full (strict)" origin pulls).
  try { reconcileAdminTls(); } catch (e) { console.warn('[tls] admin TLS reconcile failed:', e?.message); }
}

// Apply the current cert set to Caddy: regenerate sites → validate → reload.
// Returns { ok } or { ok:false, error } (never throws). Caddy keeps its last-good
// running config if a reload fails, so the proxy stays up regardless.
async function applyAndReload() {
  await regenerateManagedSites();
  try {
    await caddyAdapt({ configPath: CONFIG_FILE });
  } catch (err) {
    return { ok: false, stage: 'validate', error: redactKeyMaterial(err?.stderr || err?.message || 'caddy validate failed') };
  }
  try {
    await caddyReload({ configPath: CONFIG_FILE });
  } catch (err) {
    return { ok: false, stage: 'reload', error: redactKeyMaterial(err?.stderr || err?.message || 'caddy reload failed') };
  }
  return { ok: true };
}

// Reusable reconcile: regenerate every managed site so covered hosts pick up
// their manual cert, then validate + reload Caddy. Exported so the install-time
// cert seeder applies exactly the same pipeline the API mutations use.
export async function applyManagedTls() {
  return applyAndReload();
}

// Validate a cert+key(+chain) submission into everything the store needs.
// Returns { ok:true, parsed, normalizedKeyPem, servedChain } or { ok:false,
// status, code, message } with a specific, actionable error.
function validateSubmission({ certificate, private_key, chain, passphrase }) {
  const v = validateCertKeyPair(certificate, private_key, passphrase || null);
  if (!v.ok) return { ok: false, status: 400, code: v.code, message: v.message };
  const assembled = assembleServedChain(certificate, chain || null);
  if (!assembled.ok) return { ok: false, status: 400, code: assembled.code, message: assembled.message };
  return { ok: true, parsed: v.parsed, normalizedKeyPem: v.normalizedKeyPem, servedChain: assembled.chainPem };
}

// ---- routes (admin only; mutations need sudo) ----

// List certs — METADATA ONLY (+ bound hosts). Never the key.
router.get('/', authenticateToken, requireAdmin, (req, res) => {
  const now = Date.now();
  const certs = listCertRows().map((row) => {
    const shape = certPublicShape(row, { nowMs: now });
    return { ...shape, bound_hosts: boundHostsFor(shape.covered_names) };
  });
  res.json({ tls_mode: currentTlsMode(), certificates: certs });
});

router.get('/:id', authenticateToken, requireAdmin, (req, res) => {
  const row = getCertRow(req.params.id);
  if (!row) return res.status(404).json({ error: 'certificate not found' });
  const shape = certPublicShape(row, { nowMs: Date.now() });
  res.json({ ...shape, bound_hosts: boundHostsFor(shape.covered_names) });
});

// Create: validate → store → materialize → apply → audit. On a Caddy failure,
// undo the DB row + files and re-apply so the proxy is never left degraded.
router.post('/', authenticateToken, requireAdmin, requireSudo, async (req, res) => {
  const parsed = certBodySchema.safeParse(req.body || {});
  if (!parsed.success) return res.status(400).json({ error: 'label, certificate and private_key are required' });
  const sub = validateSubmission(parsed.data);
  if (!sub.ok) return res.status(sub.status).json({ error: sub.message, code: sub.code });

  let id = null;
  try {
    id = insertCert({ label: parsed.data.label, certPem: parsed.data.certificate, chainPem: parsed.data.chain || null, normalizedKeyPem: sub.normalizedKeyPem, parsed: sub.parsed, createdBy: req.user?.id ?? null });
    materializeCertFiles(id, sub.servedChain, sub.normalizedKeyPem);
  } catch (err) {
    if (id) { try { deleteCertRow(id); } catch { /* ignore */ } removeCertFiles(id); }
    return res.status(500).json({ error: redactKeyMaterial(err?.message || 'could not store the certificate') });
  }

  const applied = await applyAndReload();
  if (!applied.ok) {
    deleteCertRow(id); removeCertFiles(id);
    await applyAndReload().catch(() => {});
    return res.status(400).json({ error: `Caddy rejected the new configuration (${applied.stage}) — reverted. ${applied.error}` });
  }
  logAudit(req.user?.id ?? null, 'TLS_CERT_ADDED', 'tls_certificate', String(id), { label: parsed.data.label, covered_names: sub.parsed.coveredNames, fingerprint: sub.parsed.fingerprint256 }, req.ip);
  res.status(201).json({ ...certPublicShape(getCertRow(id), { nowMs: Date.now() }), applied: true });
});

// Rotate/replace or relabel. Snapshots the previous row + files so a Caddy
// failure rolls all the way back.
router.put('/:id', authenticateToken, requireAdmin, requireSudo, async (req, res) => {
  const prev = getCertRow(req.params.id);
  if (!prev) return res.status(404).json({ error: 'certificate not found' });
  const parsed = rotateBodySchema.safeParse(req.body || {});
  if (!parsed.success) return res.status(400).json({ error: 'invalid certificate fields' });
  const { certificate, private_key, chain, passphrase, label } = parsed.data;
  const replacingCert = certificate != null || private_key != null;
  if (replacingCert && !(certificate && private_key)) {
    return res.status(400).json({ error: 'to rotate, supply BOTH certificate and private_key' });
  }
  const id = Number(prev.id);

  if (!replacingCert) {
    // Label-only change — no cert material touched, so no key re-encryption and
    // no Caddy reload needed (covered_names/files are unchanged).
    if (!label) return res.status(400).json({ error: 'nothing to update: supply a new label, or certificate + private_key to rotate' });
    getDb().prepare('UPDATE tls_certificates SET label = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?').run(label, id);
    logAudit(req.user?.id ?? null, 'TLS_CERT_RELABELED', 'tls_certificate', String(id), { label }, req.ip);
    return res.json(certPublicShape(getCertRow(id), { nowMs: Date.now() }));
  }

  const sub = validateSubmission({ certificate, private_key, chain, passphrase });
  if (!sub.ok) return res.status(sub.status).json({ error: sub.message, code: sub.code });

  try {
    updateCert(id, { label: label || prev.label, certPem: certificate, chainPem: chain || null, normalizedKeyPem: sub.normalizedKeyPem, parsed: sub.parsed });
    materializeCertFiles(id, sub.servedChain, sub.normalizedKeyPem);
  } catch (err) {
    return res.status(500).json({ error: redactKeyMaterial(err?.message || 'could not store the certificate') });
  }

  const applied = await applyAndReload();
  if (!applied.ok) {
    // Roll back to the previous cert row + files, then re-apply.
    getDb().prepare('UPDATE tls_certificates SET label=?, cert_pem=?, chain_pem=?, key_pem_enc=?, covered_names=?, fingerprint=?, not_before=?, not_after=?, updated_at=CURRENT_TIMESTAMP WHERE id=?')
      .run(prev.label, prev.cert_pem, prev.chain_pem, prev.key_pem_enc, prev.covered_names, prev.fingerprint, prev.not_before, prev.not_after, id);
    try { materializeCertFiles(id, servedChainForRow(prev), getCertKeyPem(id)); } catch { /* best effort */ }
    await applyAndReload().catch(() => {});
    return res.status(400).json({ error: `Caddy rejected the rotated certificate (${applied.stage}) — reverted to the previous cert. ${applied.error}` });
  }
  logAudit(req.user?.id ?? null, 'TLS_CERT_ROTATED', 'tls_certificate', String(id), { label: label || prev.label, covered_names: sub.parsed.coveredNames, fingerprint: sub.parsed.fingerprint256 }, req.ip);
  res.json({ ...certPublicShape(getCertRow(id), { nowMs: Date.now() }), applied: true });
});

// Delete: remove the row + files, then re-apply so covered hosts fall back to
// the global mode (ACME by default). Reload failure here leaves Caddy on its
// last-good config; we surface it but the row is already gone.
router.delete('/:id', authenticateToken, requireAdmin, requireSudo, async (req, res) => {
  const row = getCertRow(req.params.id);
  if (!row) return res.status(404).json({ error: 'certificate not found' });
  const id = Number(row.id);
  const covered = JSON.parse(row.covered_names || '[]');
  deleteCertRow(id);
  removeCertFiles(id);
  const applied = await applyAndReload();
  logAudit(req.user?.id ?? null, 'TLS_CERT_DELETED', 'tls_certificate', String(id), { label: row.label, covered_names: covered, reload_ok: applied.ok }, req.ip);
  if (!applied.ok) return res.status(200).json({ deleted: true, reload_warning: `certificate removed, but Caddy reload reported: ${applied.error}` });
  res.json({ deleted: true, bound_hosts_released: boundHostsFor(covered) });
});

// Global TLS mode toggle. 'manual' means "ACME is blocked": covered hosts serve
// their pasted cert; uncovered hosts use Caddy's internal (self-signed) issuer
// instead of attempting ACME. 'acme' restores automatic issuance for uncovered
// hosts. Applying re-runs the pipeline.
router.put('/tls-mode', authenticateToken, requireAdmin, requireSudo, async (req, res) => {
  const parsed = tlsModeSchema.safeParse(req.body || {});
  if (!parsed.success) return res.status(400).json({ error: 'mode must be "acme" or "manual"' });
  const prev = currentTlsMode();
  setSetting('tls_mode', parsed.data.mode);
  const applied = await applyAndReload();
  if (!applied.ok) {
    setSetting('tls_mode', prev);
    await applyAndReload().catch(() => {});
    return res.status(400).json({ error: `Caddy rejected the mode change (${applied.stage}) — reverted to "${prev}". ${applied.error}` });
  }
  logAudit(req.user?.id ?? null, 'TLS_MODE_SET', 'app_settings', 'tls_mode', { from: prev, to: parsed.data.mode }, req.ip);
  res.json({ tls_mode: parsed.data.mode, applied: true });
});
