// Reading a design review back into the list of defects it actually is.
//
// The review posts one message: a headline, an adherence line, and then a
// bulleted list of findings — design critique, then axe-core violations, then
// adherence codes. As text it is five kilobytes somebody has to read, decide
// about, and then re-type an instruction from. As a LIST it is a set of things
// to tick.
//
// WHY PARSE RATHER THAN CARRY STRUCTURE. The message body is the durable record
// — it is what is stored, copied, saved and re-read — and a second structured
// copy stored beside it is a second thing to keep in sync. The format is
// generated by code in this repo (design-review-logic.js `reviewChatMessage`),
// so this is not scraping somebody else's output; it is reading our own. A
// backend ratchet runs this parser against a REAL generated message, so the two
// cannot drift apart silently.
//
// NO IMPORTS ON PURPOSE. The backend test suite imports this file directly to
// hold the two formats together, and it cannot resolve the frontend's `@/`
// alias or its JSX.

// `• [high] /admin@390: the issue — fix: the fix`
const BULLET = /^[•\-*]\s*\[([a-z]+)\]\s*([^:]+):\s*([\s\S]+)$/i;
// An adherence code is a SHOUTED token — TOKENDRIFT, TOKENCLEAN. That is what
// tells it apart from a screen like `/admin@390`, which is the only other thing
// that appears in the same position.
const CODE = /^[A-Z][A-Z0-9_]{2,}$/;
// axe lines end with the rule id in brackets: `… must have labels (label)`.
const AXE_TAIL = /\s*\(([a-z0-9-]+)\)\s*$/;

const SEVERITY_ORDER = { critical: 0, high: 1, serious: 2, medium: 3, moderate: 4, low: 5, minor: 6 };

export function severityRank(s) {
  const r = SEVERITY_ORDER[String(s || '').toLowerCase()];
  return r === undefined ? 9 : r;
}

// parseFindings(body) → { headline, adherence, items, extras }
//
// `items` is what the Fix dialog ticks. Everything that is not a finding —
// the headline, the adherence arithmetic, the promotion invitation, the
// press-this-button line — is kept out of it, because a checkbox next to a
// sentence nobody can act on is a checkbox that wastes a decision.
export function parseFindings(body) {
  const lines = String(body || '').split('\n');
  const items = [];
  let headline = '';
  let adherence = '';
  const extras = [];
  let seq = 0;

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    const m = BULLET.exec(line);
    if (m) {
      const [, severity, where, rest] = m;
      const scope = where.trim();
      let issue = rest.trim();
      let fix = '';
      let kind = 'design';

      const split = issue.indexOf(' — fix: ');
      if (split !== -1) {
        fix = issue.slice(split + ' — fix: '.length).trim();
        issue = issue.slice(0, split).trim();
      }
      let rule = '';
      if (CODE.test(scope)) {
        kind = 'adherence';
      } else if (!fix) {
        const tail = AXE_TAIL.exec(issue);
        if (tail) {
          kind = 'accessibility';
          rule = tail[1];
          issue = issue.replace(AXE_TAIL, '').trim();
        }
      }
      seq += 1;
      items.push({
        id: `f${seq}`,
        severity: severity.toLowerCase(),
        scope,
        issue,
        fix,
        kind,
        rule,
      });
      continue;
    }

    if (!headline && /^Design review \(/.test(line)) { headline = line; continue; }
    // TWO FORMS, one line: it reads "Design adherence: The app uses …"
    // normally and "**Visual drift** — … The app uses …" when a high-severity
    // adherence finding fired. Matching only the calm one sent the alarming one
    // to the bottom of the card as loose text, which is precisely backwards.
    if (/^(Design adherence:|\*\*Visual drift\*\*)/.test(line)) { adherence = line; continue; }
    // Section headers and the button prompt are noise once the list exists.
    if (/^Accessibility \(axe-core\):/.test(line)) continue;
    // Loose on purpose: the button's label has already changed once ("Fix
    // these" → "Fix these…"), and an exact match would silently start
    // rendering the UI prompt as a finding.
    if (/^Press \*\*Fix/.test(line)) continue;
    extras.push(line);
  }

  return { headline, adherence, items, extras };
}

export const KIND_LABEL = Object.freeze({
  design: 'Design',
  accessibility: 'Accessibility',
  adherence: 'Adherence',
});

// composeFixInstruction(items, note) — the build prompt.
//
// Built from the TICKED findings rather than from the message, which is the
// whole point of the dialog: an operator who unticks four of seven has said
// something, and sending the original text would throw it away.
//
// The review already wrote a fix for each finding. Those are carried verbatim
// — they are specific, they name variables and breakpoints, and rewording them
// into a summary is how a precise instruction becomes a vague one.
export function composeFixInstruction(items, note = '') {
  const picked = items.filter(Boolean);
  const lines = [];
  if (picked.length) {
    lines.push(
      picked.length === 1
        ? 'Fix this design-review finding on the built app:'
        : `Fix these ${picked.length} design-review findings on the built app:`,
    );
    lines.push('');
    for (const f of picked) {
      lines.push(`- [${f.severity}] ${f.scope} — ${f.issue}`);
      if (f.fix) lines.push(`  Fix: ${f.fix}`);
    }
  }
  const extra = String(note || '').trim();
  if (extra) {
    // Labelled and last, and it WINS. A note that cannot override the findings
    // is not worth typing — the operator is looking at the running app and the
    // review is looking at six screenshots of it.
    lines.push('');
    lines.push('Also, from the operator — this wins wherever it disagrees with the list above:');
    lines.push(extra);
  }
  if (!lines.length) return '';
  lines.push('');
  lines.push('Change nothing else: no new features, and no screens these findings do not name.');
  return lines.join('\n');
}
