// Reading a design review back into the list of defects it actually is.
//
// The review posts one message: a headline, an adherence line, and then a
// bulleted list of findings — design critique, then axe-core violations, then
// adherence codes. As text it is five kilobytes somebody has to read, decide
// about, and then re-type an instruction from. As a LIST it is a set of things
// to tick.
//
// WHY PARSE RATHER THAN CARRY STRUCTURE. The message body is the durable record
// — it is what is stored, copied, saved and re-read — and a second structured
// copy stored beside it is a second thing to keep in sync. The format is
// generated by code in this repo (design-review-logic.js `reviewChatMessage`),
// so this is not scraping somebody else's output; it is reading our own. A
// backend ratchet runs this parser against a REAL generated message, so the two
// cannot drift apart silently.
//
// NO IMPORTS ON PURPOSE. The backend test suite imports this file directly to
// hold the two formats together, and it cannot resolve the frontend's `@/`
// alias or its JSX.

// `• [high] /admin@390: the issue — fix: the fix`
const BULLET = /^[•\-*]\s*\[([a-z]+)\]\s*([^:]+):\s*([\s\S]+)$/i;
// An adherence code is a SHOUTED token — TOKENDRIFT, TOKENCLEAN. That is what
// tells it apart from a screen like `/admin@390`, which is the only other thing
// that appears in the same position.
const CODE = /^[A-Z][A-Z0-9_]{2,}$/;
// axe lines end with the rule id in brackets: `… must have labels (label)`.
const AXE_TAIL = /\s*\(([a-z0-9-]+)\)\s*$/;

const SEVERITY_ORDER = { critical: 0, high: 1, serious: 2, medium: 3, moderate: 4, low: 5, minor: 6 };

export function severityRank(s) {
  const r = SEVERITY_ORDER[String(s || '').toLowerCase()];
  return r === undefined ? 9 : r;
}

// parseFindings(body) → { headline, adherence, items, extras }
//
// `items` is what the Fix dialog ticks. Everything that is not a finding —
// the headline, the adherence arithmetic, the promotion invitation, the
// press-this-button line — is kept out of it, because a checkbox next to a
// sentence nobody can act on is a checkbox that wastes a decision.
export function parseFindings(body) {
  const lines = String(body || '').split('\n');
  const items = [];
  let headline = '';
  let adherence = '';
  const extras = [];
  let seq = 0;

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    const m = BULLET.exec(line);
    if (m) {
      const [, severity, where, rest] = m;
      const scope = where.trim();
      let issue = rest.trim();
      let fix = '';
      let kind = 'design';

      const split = issue.indexOf(' — fix: ');
      if (split !== -1) {
        fix = issue.slice(split + ' — fix: '.length).trim();
        issue = issue.slice(0, split).trim();
      }
      let rule = '';
      if (CODE.test(scope)) {
        kind = 'adherence';
      } else if (!fix) {
        const tail = AXE_TAIL.exec(issue);
        if (tail) {
          kind = 'accessibility';
          rule = tail[1];
          issue = issue.replace(AXE_TAIL, '').trim();
        }
      }
      seq += 1;
      items.push({
        id: `f${seq}`,
        severity: severity.toLowerCase(),
        scope,
        issue,
        fix,
        kind,
        rule,
      });
      continue;
    }

    if (!headline && /^Design review \(/.test(line)) { headline = line; continue; }
    // TWO FORMS, one line: it reads "Design adherence: The app uses …"
    // normally and "**Visual drift** — … The app uses …" when a high-severity
    // adherence finding fired. Matching only the calm one sent the alarming one
    // to the bottom of the card as loose text, which is precisely backwards.
    if (/^(Design adherence:|\*\*Visual drift\*\*)/.test(line)) { adherence = line; continue; }
    // Section headers and the button prompt are noise once the list exists.
    if (/^Accessibility \(axe-core\):/.test(line)) continue;
    // Loose on purpose: the button's label has already changed once ("Fix
    // these" → "Fix these…"), and an exact match would silently start
    // rendering the UI prompt as a finding.
    if (/^Press \*\*Fix/.test(line)) continue;
    extras.push(line);
  }

  return { headline, adherence, items, extras };
}

export const KIND_LABEL = Object.freeze({
  design: 'Design',
  accessibility: 'Accessibility',
  adherence: 'Adherence',
});

// ---- grouped, short fix requests (harness redesign 6.c) ----
//
// P34's requests — the good baseline — were short and referent-anchored
// (median 170 chars): they named a screen and what to change, and leaned on
// what both sides had just looked at instead of restating it. The old
// composer emitted up to ~7KB of restated findings. Findings are now grouped
// by the screen the review named (a small related group), and each group's
// request targets <= GROUP_CHAR_TARGET chars; the full findings still reach
// the build through the design-findings ledger (state/design-findings.json
// is briefed into every build task), so clipping here loses nothing.

export const GROUP_CHAR_TARGET = 500;

// Small related groups, keyed by the screen/scope the review named.
export function groupFindings(items) {
  const map = new Map();
  for (const f of (items || []).filter(Boolean)) {
    const key = String(f.scope || '/').trim() || '/';
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(f);
  }
  return [...map.entries()].map(([screen, findings]) => ({ screen, findings }));
}

function clipTo(s, n) {
  s = String(s || '').replace(/\s+/g, ' ').trim();
  if (s.length <= n) return s;
  return `${s.slice(0, Math.max(0, n - 1)).replace(/[\s,;:.]+\S*$/, '')}…`;
}

// One screen's ticked findings as one short block. The review's own fix
// wording is carried intact when it fits the group budget, clipped when it
// does not — the verbatim detail is one scroll away in the review message and
// rides the findings ledger into the build either way.
export function composeGroupRequest({ screen, findings }) {
  const head = `On ${screen}:`;
  const budget = Math.max(80, GROUP_CHAR_TARGET - head.length - 2);
  const per = Math.max(60, Math.floor(budget / findings.length) - 8);
  const parts = findings.map((f) => {
    const both = `${f.issue}${f.fix ? ` — ${f.fix}` : ''}`;
    return both.length <= per ? both : clipTo(f.fix || f.issue, per);
  });
  let text = `${head} ${parts.join('; ')}`;
  if (text.length > GROUP_CHAR_TARGET) text = clipTo(text, GROUP_CHAR_TARGET);
  return text;
}

// composeFixInstruction(items, note) — the build prompt.
//
// Built from the TICKED findings rather than from the message, which is the
// whole point of the dialog: an operator who unticks four of seven has said
// something, and sending the original text would throw it away.
export function composeFixInstruction(items, note = '') {
  const picked = (items || []).filter(Boolean);
  const lines = [];
  if (picked.length) {
    lines.push(
      picked.length === 1
        ? 'Fix this design-review finding on the built app:'
        : `Fix these ${picked.length} design-review findings on the built app:`,
    );
    lines.push('');
    for (const g of groupFindings(picked)) lines.push(`- ${composeGroupRequest(g)}`);
    lines.push('');
    lines.push('Full detail (severities, exact fixes) is in the design review just posted; the open findings also ride state/design-findings.json into this build.');
  }
  const extra = String(note || '').trim();
  if (extra) {
    // Labelled and last, and it WINS. A note that cannot override the findings
    // is not worth typing — the operator is looking at the running app and the
    // review is looking at six screenshots of it.
    lines.push('');
    lines.push('Also, from the operator — this wins wherever it disagrees with the list above:');
    lines.push(extra);
  }
  if (!lines.length) return '';
  lines.push('');
  lines.push('Change nothing else: no new features, and no screens these findings do not name.');
  return lines.join('\n');
}
