/**
 * Render the bootstrap shell snippet the operator copies to a new
 * device. The script generates an ed25519 keypair locally, prints the
 * public half, and prints the exact `proxypilot ssh access add` heredoc
 * the operator pastes back into a server shell. The private key never
 * leaves the device. Same trust model as ssh-copy-id — no privileged
 * channel between the device and the server.
 *
 * `id` is validated against the same regex as the SSH access add path
 * so the snippet can never embed a quoting hazard.
 */
const ID_RE = /^[A-Za-z0-9][A-Za-z0-9._-]{0,62}$/;
const USER_RE = /^[a-z_][a-z0-9_-]{0,31}\$?$/;
const HOST_RE = /^[A-Za-z0-9._-]{1,253}$/;

export function renderBootstrapScript({ id, user = '<unix-user>', server = '<server>' } = {}) {
  if (!ID_RE.test(id ?? '')) {
    throw new Error(
      `invalid id "${id}": must match ${ID_RE} ` +
      `(letters/digits/dot/underscore/hyphen, max 63 chars, no leading punctuation)`,
    );
  }
  if (user !== '<unix-user>' && !USER_RE.test(user)) {
    throw new Error(`invalid --user "${user}"`);
  }
  if (server !== '<server>' && !HOST_RE.test(server)) {
    throw new Error(`invalid --server "${server}"`);
  }
  return `#!/usr/bin/env bash
# Generated by ProxyPilot for SSH access id "${id}".
# Run this on the *device* you want to add. The private key stays here;
# only the public key + one shell command are emitted to your terminal.
set -euo pipefail

ID="${id}"
UNIX_USER="${user}"
SERVER="${server}"

KEY_PATH="\${HOME}/.ssh/proxypilot_\${ID}_ed25519"
mkdir -p "\${HOME}/.ssh"
chmod 700 "\${HOME}/.ssh"
if [ -e "\${KEY_PATH}" ]; then
  echo "Key already exists at \${KEY_PATH} — refusing to overwrite." >&2
  echo "Delete it first if you really want to regenerate." >&2
  exit 1
fi
ssh-keygen -t ed25519 -f "\${KEY_PATH}" -N "" \\
  -C "proxypilot:\${ID}@$(hostname -s)"
chmod 600 "\${KEY_PATH}"

PUBKEY="$(cat "\${KEY_PATH}.pub")"
LABEL="$(hostname -s) ($(uname -s))"

cat <<EOF

==== Public key generated at \${KEY_PATH}.pub ====

Run this command on the ProxyPilot host (paste into a server shell):

proxypilot ssh access add "\${ID}" --user "\${UNIX_USER}" \\
  --label "\${LABEL}" \\
  --pubkey - <<KEY
\${PUBKEY}
KEY

Then connect with:

  ssh -i "\${KEY_PATH}" "\${UNIX_USER}@\${SERVER}"

EOF
`;
}
