/**
 * Render the bootstrap shell snippet the operator copies to a new
 * device. The script generates an ed25519 keypair locally, prints the
 * public half, and prints the exact `proxypilot ssh access add` heredoc
 * the operator pastes back into a server shell. The private key never
 * leaves the device. Same trust model as ssh-copy-id — no privileged
 * channel between the device and the server.
 *
 * `id` is validated against the same regex as the SSH access add path
 * so the snippet can never embed a quoting hazard.
 */
const ID_RE = /^[A-Za-z0-9][A-Za-z0-9._-]{0,62}$/;
const USER_RE = /^[a-z_][a-z0-9_-]{0,31}\$?$/;
const HOST_RE = /^[A-Za-z0-9._-]{1,253}$/;

export const BOOTSTRAP_SHELLS = ['bash', 'powershell'];

export function renderBootstrapScript({ id, user = '<unix-user>', server = '<server>', shell = 'bash' } = {}) {
  if (!ID_RE.test(id ?? '')) {
    throw new Error(
      `invalid id "${id}": must match ${ID_RE} ` +
      `(letters/digits/dot/underscore/hyphen, max 63 chars, no leading punctuation)`,
    );
  }
  if (user !== '<unix-user>' && !USER_RE.test(user)) {
    throw new Error(`invalid --user "${user}"`);
  }
  if (server !== '<server>' && !HOST_RE.test(server)) {
    throw new Error(`invalid --server "${server}"`);
  }
  if (!BOOTSTRAP_SHELLS.includes(shell)) {
    throw new Error(`invalid --shell "${shell}": must be one of ${BOOTSTRAP_SHELLS.join(', ')}`);
  }
  if (shell === 'powershell') return renderPowerShell({ id, user, server });
  return renderBash({ id, user, server });
}

function renderBash({ id, user, server }) {
  return `#!/usr/bin/env bash
# Generated by ProxyPilot for SSH access id "${id}".
# Run this on the *device* you want to add. The private key stays here;
# only the public key + one shell command are emitted to your terminal.
set -euo pipefail

ID="${id}"
UNIX_USER="${user}"
SERVER="${server}"

KEY_PATH="\${HOME}/.ssh/proxypilot_\${ID}_ed25519"
mkdir -p "\${HOME}/.ssh"
chmod 700 "\${HOME}/.ssh"
if [ -e "\${KEY_PATH}" ]; then
  echo "Key already exists at \${KEY_PATH} — refusing to overwrite." >&2
  echo "Delete it first if you really want to regenerate." >&2
  exit 1
fi
ssh-keygen -t ed25519 -f "\${KEY_PATH}" -N "" \\
  -C "proxypilot:\${ID}@$(hostname -s)"
chmod 600 "\${KEY_PATH}"

PUBKEY="$(cat "\${KEY_PATH}.pub")"
LABEL="$(hostname -s) ($(uname -s))"

cat <<EOF

==== Public key generated at \${KEY_PATH}.pub ====

Run this command on the ProxyPilot host (paste into a server shell):

proxypilot ssh access add "\${ID}" --user "\${UNIX_USER}" \\
  --label "\${LABEL}" \\
  --pubkey - <<KEY
\${PUBKEY}
KEY

Then connect with:

  ssh -i "\${KEY_PATH}" "\${UNIX_USER}@\${SERVER}"

EOF
`;
}

/**
 * PowerShell variant for Windows operators. ssh-keygen ships with the
 * built-in OpenSSH client capability on Windows 10/11 / Server 2019+,
 * but it isn't always installed. Probe for ssh-keygen up front and
 * fail with an actionable install hint instead of a confusing
 * `command not found`. Same trust model as the bash variant: the
 * private key never leaves the device.
 *
 * Defensive notes:
 *   - $ErrorActionPreference = 'Stop' so a failed ssh-keygen aborts
 *     the script instead of continuing to a misleading later step.
 *   - Single-quoted PowerShell string literals are passthrough
 *     (no `$var` expansion). Variables we want PowerShell to expand
 *     use double-quoted strings.
 *   - The here-string for the printed `proxypilot ssh access add`
 *     command uses a single-quoted opener (`@'`) so PowerShell does
 *     NOT expand `${PUBKEY}` — the operator copies it literally and
 *     the server-side bash parses the heredoc.
 */
function renderPowerShell({ id, user, server }) {
  return `# Generated by ProxyPilot for SSH access id "${id}".
# Run this on the *device* you want to add (Windows PowerShell 5.1 or
# PowerShell 7+). The private key stays here; only the public key
# + one shell command are emitted to your terminal.
$ErrorActionPreference = 'Stop'

$ID         = '${id}'
$UNIX_USER  = '${user}'
$SERVER     = '${server}'

if (-not (Get-Command ssh-keygen -ErrorAction SilentlyContinue)) {
    Write-Host ''
    Write-Host 'ssh-keygen not found.' -ForegroundColor Red
    Write-Host 'Install the OpenSSH Client capability (admin PowerShell):' -ForegroundColor Yellow
    Write-Host '  Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0'
    Write-Host 'Or via Settings: System > Optional features > Add a feature > "OpenSSH Client".'
    exit 1
}

$SshDir   = Join-Path $HOME '.ssh'
$KeyPath  = Join-Path $SshDir ("proxypilot_{0}_ed25519" -f $ID)

if (-not (Test-Path $SshDir)) {
    New-Item -ItemType Directory -Path $SshDir | Out-Null
}
if (Test-Path $KeyPath) {
    Write-Host "Key already exists at $KeyPath - refusing to overwrite." -ForegroundColor Red
    Write-Host 'Delete it first if you really want to regenerate:' -ForegroundColor Yellow
    Write-Host "  Remove-Item '$KeyPath','$KeyPath.pub'"
    exit 1
}

$KeyComment = "proxypilot:{0}@{1}" -f $ID, $env:COMPUTERNAME
# Defer to cmd.exe for the ssh-keygen call: PowerShell drops empty
# string args to native commands across 5.1 and 7.x default modes,
# which would silently keep ssh-keygen's interactive passphrase
# prompt running. cmd parses the literal "" reliably as empty.
$KeygenCmd = 'ssh-keygen -t ed25519 -q -f "' + $KeyPath + '" -N "" -C "' + $KeyComment + '"'
cmd.exe /c $KeygenCmd | Out-Host
if ($LASTEXITCODE -ne 0) {
    Write-Host "ssh-keygen failed (exit $LASTEXITCODE)" -ForegroundColor Red
    exit 1
}

# ssh-keygen on Windows occasionally writes a CRLF-terminated pubkey;
# normalize to LF so the server parses one line.
$PubKey = ((Get-Content -Raw "$KeyPath.pub") -replace "\`r", '').TrimEnd()
$Label  = "{0} ({1})" -f $env:COMPUTERNAME, [System.Environment]::OSVersion.VersionString

Write-Host ''
Write-Host "==== Public key generated at $KeyPath.pub ===="
Write-Host ''
Write-Host 'Run this command on the ProxyPilot host (paste into a server shell):'
Write-Host ''

@"
proxypilot ssh access add "$ID" --user "$UNIX_USER" \\
  --label "$Label" \\
  --pubkey - <<KEY
$PubKey
KEY
"@ | Write-Host

Write-Host ''
Write-Host 'Then connect with:'
Write-Host ''
Write-Host "  ssh -i \`"$KeyPath\`" \`"$UNIX_USER@$SERVER\`""
Write-Host ''
`;
}
