// Mock2 network isolation — the PURE decision layer (Phase M4, ADR-010).
//
// Every M4 decision that can be made without better-sqlite3, Incus, nftables, or
// squid lives here so it is unit-testable at the module boundary (stub-first,
// risk R9) — the same split the module already uses for domain-logic.js /
// project-logic.js / slug.js. This file imports NOTHING native; the host-acting
// shells (network.js, firewall.js, egress.js, allowlist.js, port-check.js) each
// import their pure helpers from here.
//
// Contents:
//   * per-project bridge naming + /24 subnet derivation + gateway
//   * the nftables fence renderer (`table inet mock2`) + its plan builder
//   * the squid ACL renderer + its plan builder + allowlist host validation
//   * the manifest port-drift comparator
//
// Terminology (risk R7): nothing here is named "agent".

// The egress proxy port containers point HTTP(S)_PROXY at (squid default). The
// enable script guarantees squid listens here and the fence allows the bridge
// to reach the gateway on it. Overridable at deploy time.
export const EGRESS_PROXY_PORT = Number(process.env.MOCK2_EGRESS_PROXY_PORT || 3128);

// ---- per-project bridge naming + subnet ----

export function bridgeNameForProject(id) {
  return `m2br${Number(id)}`;
}

// Per-project /24 out of 10.200.0.0 – 10.255.255.0 — no collision with the
// shared bridge (10.0.100.0/24), the VPN subnet (10.100.0.0/24), or common LANs.
// 56 × 256 = 14 336 distinct subnets before wrap (far past dev-plane scale, Q5),
// and a pure function of the id so it needs no allocator. Widen the block range
// here if a deployment ever needs more.
export function bridgeCidrForProject(id) {
  const n = Number(id);
  if (!Number.isInteger(n) || n < 1) throw new Error(`bridgeCidrForProject: bad project id ${id}`);
  const block = 200 + (Math.floor((n - 1) / 256) % 56); // 200..255
  const third = (n - 1) % 256; // 0..255
  return `10.${block}.${third}.0/24`;
}

// Gateway (host side of the bridge) — the first host in the /24 (final octet 1).
export function gatewayForCidr(cidr) {
  const m = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.\d{1,3}\/\d{1,2}$/.exec(String(cidr || ''));
  if (!m) return null;
  return `${m[1]}.${m[2]}.${m[3]}.1`;
}

// ---- nftables fence (`table inet mock2`) ----

// buildFenceEntries(projects) — the per-project fence plan: one entry per LIVE
// project that has a bridge subnet, a container IP, and a declared web port.
// A project missing any of those (provisioning, archived, stopped, mid-launch)
// contributes nothing until the container is up and reconcile runs again.
export function buildFenceEntries(projects = []) {
  const entries = [];
  for (const p of projects) {
    if (!p || p.lifecycle !== 'active') continue;
    const cidr = p.bridge_cidr || (p.id ? bridgeCidrForProject(p.id) : null);
    const gateway = cidr ? gatewayForCidr(cidr) : null;
    if (!cidr || !gateway || !p.container_ip || !p.web_port) continue;
    entries.push({ id: Number(p.id), cidr, gateway, containerIp: p.container_ip, webPort: Number(p.web_port) });
  }
  return entries;
}

// renderMock2Nft(entries, { proxyPort }) — the full nft ruleset for
// `table inet mock2`. The add+flush pair makes `nft -f -` idempotent, scoped to
// OUR table so nothing else is flushed (see firewall.js for why a dedicated
// table). forward hook: established pass, inbound only to each declared web
// port, deny every other inbound to a container (Postgres 5432 etc. stay
// internal), deny all egress off a bridge. input hook: each bridge may reach
// ONLY its own gateway for DNS / DHCP-renew / the proxy port, deny the rest
// (the control plane — host :3001, the main bridge, every other host IP).
export function renderMock2Nft(entries = [], { proxyPort = EGRESS_PROXY_PORT } = {}) {
  const fwd = [];
  const inp = [];
  for (const e of entries) {
    const tag = `mock2 p${e.id}`;
    fwd.push(`    ip daddr ${e.containerIp} tcp dport ${e.webPort} accept comment "${tag} web"`);
    fwd.push(`    ip daddr ${e.containerIp} drop comment "${tag} deny-inbound"`);
    fwd.push(`    ip saddr ${e.cidr} drop comment "${tag} deny-egress"`);
    inp.push(`    ip saddr ${e.cidr} ip daddr ${e.gateway} udp dport 53 accept comment "${tag} dns"`);
    inp.push(`    ip saddr ${e.cidr} ip daddr ${e.gateway} tcp dport 53 accept comment "${tag} dns"`);
    inp.push(`    ip saddr ${e.cidr} ip daddr ${e.gateway} udp dport 67 accept comment "${tag} dhcp"`);
    inp.push(`    ip saddr ${e.cidr} ip daddr ${e.gateway} tcp dport ${proxyPort} accept comment "${tag} proxy"`);
    inp.push(`    ip saddr ${e.cidr} drop comment "${tag} deny-host"`);
  }
  const fwdBody = fwd.length ? fwd.join('\n') : '    # (no active project bridges)';
  const inpBody = inp.length ? inp.join('\n') : '    # (no active project bridges)';
  return `# Generated by ProxyPilot Mock2 (Phase M4, ADR-010). Do not edit by hand.
# A dedicated table so the CLI firewall's \`flush table inet proxypilot\` can
# never clobber it, and so a disabled host has no Mock2 nftables state at all.
add table inet mock2
flush table inet mock2

table inet mock2 {
  chain forward {
    type filter hook forward priority -10; policy accept;
    ct state established,related accept
    ct state invalid drop
${fwdBody}
  }

  chain input {
    type filter hook input priority -10; policy accept;
    ct state established,related accept
${inpBody}
  }
}
`;
}

// ---- squid egress ACL ----

// The default allowlist a project is born with (ADR-010). apt/pypi are included
// because the template installs its runtime over the proxy (setup bakes
// HTTP(S)_PROXY), so a fresh container must reach the Debian + Python mirrors.
// The model-API hosts are the static seed M5 replaces with connector-driven
// entries (ADR-003). In M4 the bare repo is a local disk mount (ADR-011), so no
// git-remote host is needed yet (M5 adds external remotes).
export const DEFAULT_EGRESS_ALLOWLIST = Object.freeze([
  'registry.npmjs.org',
  'deb.debian.org',
  'security.debian.org',
  'pypi.org',
  'files.pythonhosted.org',
  'api.anthropic.com',
  'api.openai.com',
  'generativelanguage.googleapis.com',
]);

// isAllowlistHost(host) — a conservative validator. A squid dstdomain entry is a
// bare hostname or a domain suffix (leading dot allowed, squid's subdomain
// form); reject anything with a scheme, path, port, whitespace, or out-of-set
// character so a bad value can't smuggle a squid directive into the ACL file.
export function isAllowlistHost(host) {
  const h = String(host || '').trim().toLowerCase();
  if (h.length === 0 || h.length > 253) return false;
  // Reject bare IPv4 literals: squid `dstdomain` matches the request's Host
  // header domain, so an IP belongs in a `dst` ACL, not here. Rejecting it keeps
  // the allowlist meaning "hostnames only" and avoids a silently-ineffective row.
  if (/^\.?\d{1,3}(\.\d{1,3}){3}$/.test(h)) return false;
  return /^\.?([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$/.test(h);
}

export function normalizeAllowlistHost(host) {
  return String(host || '').trim().toLowerCase();
}

// buildEgressPlan(projects, allowlists) — one entry per project whose bridge
// exists (bridge_cidr set or derivable, not archived/failed). Provisioning
// projects ARE included: the container's setup installs its runtime over the
// proxy, so the ACL must be live before setup runs. `allowlists` is a
// Map(projectId → host[]).
export function buildEgressPlan(projects = [], allowlists = new Map()) {
  const plan = [];
  for (const p of projects) {
    if (!p) continue;
    if (p.lifecycle === 'archived' || p.lifecycle === 'failed_provisioning') continue;
    const cidr = p.bridge_cidr || (p.id ? bridgeCidrForProject(p.id) : null);
    if (!cidr) continue;
    const hosts = allowlists.get(Number(p.id)) || allowlists.get(p.id) || [];
    plan.push({ id: Number(p.id), cidr, hosts: [...hosts] });
  }
  return plan;
}

// renderSquidAcl(plan) — the ACL-only squid drop-in. Per project: a src ACL for
// its bridge subnet, a dstdomain ACL for its allowlist, an allow pairing them.
// A trailing deny for the union of mock2 subnets is defence in depth (squid's
// default deny-all also backstops it). An empty allowlist emits no allow line,
// so that project is denied by default.
export function renderSquidAcl(plan = []) {
  const lines = [
    '# Generated by ProxyPilot Mock2 (Phase M4, ADR-010). Do not edit by hand.',
    '# Per-project egress allowlist. Each bridge subnet may reach ONLY its',
    '# allowlisted hosts; the bridge default-deny (nftables) blocks any bypass.',
    '',
  ];
  const allSrc = [];
  for (const e of plan) {
    allSrc.push(e.cidr);
    lines.push(`acl mock2_p${e.id}_src src ${e.cidr}`);
    if (e.hosts.length > 0) {
      lines.push(`acl mock2_p${e.id}_dst dstdomain ${e.hosts.join(' ')}`);
      lines.push(`http_access allow mock2_p${e.id}_src mock2_p${e.id}_dst`);
    } else {
      lines.push(`# project ${e.id}: empty allowlist — all egress denied`);
    }
    lines.push('');
  }
  if (allSrc.length > 0) {
    lines.push('# Defence in depth: deny anything else originating from a Mock2 bridge.');
    lines.push(`acl mock2_all_src src ${allSrc.join(' ')}`);
    lines.push('http_access deny mock2_all_src');
  }
  lines.push('');
  return lines.join('\n');
}

// ---- manifest port-drift (ADR-005 inbound half) ----

// Benign OS-plumbing ports a stock Debian/systemd container binds on all
// interfaces that are NOT the app's surface, so they must not raise port_drift
// (they are noise, not an exposed workload — the drift check exists to catch an
// undeclared APP port, ADR-005). systemd-resolved binds LLMNR on tcp+udp/5355
// and multicast DNS on udp/5353; the DHCP client holds udp/68 (v4) and the
// DHCPv6 client udp/546. These are the recurring false positives on the M4
// scan. An app that genuinely wants one of these must still declare it as `web`,
// so ignoring them here changes only the noise, never a routed port.
export const BENIGN_SYSTEM_TCP_PORTS = Object.freeze([5355]);
export const BENIGN_SYSTEM_UDP_PORTS = Object.freeze([68, 546, 5353, 5355]);

// computePortDrift({ declared, tcpAnyHost, udpAnyHost }) → the exposed ports the
// manifest does NOT account for. The declared web port is the only allowed
// publicly-bound TCP listener; every other non-loopback TCP bind is drift, and
// ANY non-loopback UDP bind is drift (the manifest declares no UDP). Loopback
// binds (in-container Postgres on 127.0.0.1:5432, ADR-008) never count, and the
// benign OS-plumbing ports above are filtered out as scan noise.
export function computePortDrift({ declared, tcpAnyHost = [], udpAnyHost = [] }) {
  const w = Number(declared);
  const tcp = tcpAnyHost.filter((p) => Number(p) !== w && !BENIGN_SYSTEM_TCP_PORTS.includes(Number(p)));
  const udp = udpAnyHost.filter((p) => !BENIGN_SYSTEM_UDP_PORTS.includes(Number(p)));
  return { tcp, udp, hasDrift: tcp.length > 0 || udp.length > 0 };
}
