// Synthetic configured-service fixtures verify UI requests and explicit human transitions.
// They do not prove broker authorization, OpenBao custody or runner enforcement.
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {exact,uuid,input as validateInput} from '../../../services/credential-broker/schema.mjs';
import { createServer } from 'vite';
import { fileURLToPath } from 'node:url';
import { mkdirSync, writeFileSync } from 'node:fs';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || '../../backend/node_modules/playwright-core/index.mjs');
const vite = await createServer({root:fileURLToPath(new URL('..',import.meta.url)),server:{host:'127.0.0.1',port:0}});await vite.listen();
const origin=`http://127.0.0.1:${vite.httpServer.address().port}`;
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXE||'/usr/bin/chromium',args:['--no-sandbox',...(process.env.LIGHTHOUSE_DIR?['--remote-debugging-port=9339']:[])]});
const user={id:'00000000-0000-4000-8000-000000000001',username:'Fixture owner',role:'user',permissions:[]};
const project={id:'00000000-0000-4000-8000-000000000002',name:'Fixture project',owner_name:user.username,own_role:'owner',revision:1,description:'Synthetic UI fixture',current_version:{id:'20000000-0000-4000-8000-000000000001',content_hash:'a'.repeat(64),version_number:1}};
const connection={id:'00000000-0000-4000-8000-000000000003',name:'Fixture ledger',adapter_id:'synthetic-ledger-v1',rights:['view','use','assign','manage'],operations:['item.read'],resources:['00000000-0000-4000-8000-000000000004'],limits:{max_actions:20,max_seconds:300},owner_id:user.id,project_id:project.id,revision:1,policy_revision:1,status:'active',credential_version:1,readiness:{state:'ready',code:'SYNTHETIC_ONLY'},sessions:[]};
const readiness={state:'blocked',can_start:false,execution_enabled:false,checks:[{kind:'broker',state:'ready',code:'BROKER_REACHABLE',next_action:null},{kind:'guide',state:'ready',code:'GUIDE_APPROVED',next_action:null},{kind:'environment',state:'unverified',code:'ENVIRONMENT_UNVERIFIED',next_action:'verify_environment'}]};
let mode='configured',compatible=true,execution=true,preflight=true,reviewExpired=false,taskRows=[];
const taskId='10000000-0000-4000-8000-000000000001',attempt='10000000-0000-4000-8000-000000000002',fence='10000000-0000-4000-8000-000000000003',grantId='10000000-0000-4000-8000-000000000004';
const agentId='20000000-0000-4000-8000-000000000002',sessionId='20000000-0000-4000-8000-000000000003',approvalId='20000000-0000-4000-8000-000000000004',cancelTaskId='20000000-0000-4000-8000-000000000005';
const proposalId='30000000-0000-4000-8000-000000000001',environmentId='30000000-0000-4000-8000-000000000002',outputId='30000000-0000-4000-8000-000000000003';
const proposalBase=`/api/operational-projects/${project.id}/agent-configurations/${agentId}/task-proposals`;
const taskBase=`/api/operational-projects/${project.id}/agent-configurations/${agentId}/tasks`;
// Canonical runner pending request: runner.mjs drive() and broker-task-dispatch.js receipt schema.
const pending={session_id:sessionId,request:{connection_id:connection.id,operation:'item.set_state',input:{resource_id:connection.resources[0],state:'closed'}}};
exact(pending,['session_id','request']);uuid(pending.session_id);exact(pending.request,['connection_id','operation','input']);uuid(pending.request.connection_id);validateInput(pending.request.operation,pending.request.input);
function taskRow(state,id=taskId){const identities={id,user_id:user.id,project_id:project.id,agent_id:agentId,configuration_revision:agents[0].revision,attempt,fence};return {...identities,state,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),receipt:{...identities,state,session_id:sessionId,step_index:state==='completed'?1:0,end_confirmed:['completed','cancelled'].includes(state),receipts:state==='completed'?[{id:'20000000-0000-4000-8000-000000000007',state:'succeeded',operation:pending.request.operation}]:[],pending_approval:state==='awaiting_approval'?structuredClone(pending):null,code:state==='cancelled'?'TASK_CANCELLED':null}};}

const requests=[],agents=[],errors=[],report={synthetic:true,source_commit:process.env.SOURCE_COMMIT||execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),generated_at:new Date().toISOString(),journeys:[],layout:[]};let forbidden=false,failEnrollment=false,failAssignment=false,syntheticIntake=false;
connection.operations=['item.read','item.set_state'];connection.assignments=[{id:grantId,connection_id:connection.id,user_id:user.id,agent_id:agentId,project_id:project.id,revision:1,revoked:false,operations:connection.operations,resources:connection.resources,limits:connection.limits,expires_at:Date.now()+3600000}];
agents.push({id:agentId,revision:1,lifecycle:'draft',work:{name:'Synthetic task operator',role:'',task:'One permitted item action',expected_outcome:'',inputs:[],supporting_material:[],guide_ref:{id:project.current_version.id,hash:project.current_version.content_hash},environment_ref:'20000000-0000-4000-8000-000000000006'},controls:{operations:connection.operations,resources:connection.resources,max_actions:20,max_seconds:60,approval_policy:'writes',escalation_user_ids:[],output_ref:null}});
const page=await browser.newPage({viewport:{width:1280,height:1000}});page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{if(!localStorage.getItem('pp-theme'))localStorage.setItem('pp-theme','office');});
await page.route('**/api/**',async route=>{
 const r=route.request(),path=new URL(r.url()).pathname,method=r.method(),body=r.postDataJSON();requests.push({path,method,body});
 const answer=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
 if(path==='/api/auth/sudo')return answer({success:true});
 if(path.endsWith('/broker-registrations'))return answer({environments:[{id:environmentId,name:'Registered fixture worker',workload_id:'fixture-worker',workflow_type:'typed_api_v1',status:'ready',revision:1},{id:'30000000-0000-4000-8000-000000000004',name:'Offline worker',workflow_type:'typed_api_v1',status:'unavailable',revision:1},{id:'30000000-0000-4000-8000-000000000005',name:'Unsupported browser worker',workflow_type:'browser',status:'ready',revision:1}],outputs:[{id:outputId,name:'Project activity',kind:'project_activity',status:'ready',revision:1}]});
 if(path===proposalBase)return preflight?answer({proposal:{id:proposalId,expires_at:Date.now()+60000,...body},readiness:{ready:true,expires_at:Date.now()+(reviewExpired?-1000:30000)}}):answer({error:{code:'SOURCE_TASK_NOT_READY',message:'Current registered checks have not been verified.'}},409);
 if(path===proposalBase+`/${proposalId}/start`){taskRows=[taskRow('awaiting_approval')];return answer({task:taskRows[0]},201);}
 if(path===taskBase)return answer({tasks:taskRows});
 if(path===taskBase+`/${taskId}/approval`){taskRows[0]=taskRow('completed');return answer({task:taskRows[0]});}
 if(path===taskBase+`/${cancelTaskId}/cancel`){taskRows[1]=taskRow('cancelled',cancelTaskId);return answer({task:taskRows[1]});}
 if(path===taskBase+`/${taskId}`)return answer({task:taskRows[0]});
 if(path===taskBase+`/${cancelTaskId}`)return answer({task:taskRows[1]});
 if(path==='/api/auth/verify')return answer({user});
 if(path==='/api/operational-projects/capabilities')return answer({enabled:true,ui_available:true,agents_metadata_enabled:true,evidence_enabled:false,agent_runs_enabled:false});
 if(path==='/api/connections/capabilities')return answer({mode,compatible,intake_enabled:true,intake_origin:'https://broker.fixture.example',execution_enabled:execution,reason:'READY'});
 if(path==='/api/connections')return answer({connections:forbidden?[]:[connection],next_cursor:null});
 if(path.endsWith('/rotation-intents'))return answer({intent:{id:'rotation',state:'reserved',intake_url:`${origin}/intake/rotation`,expires_at:Date.now()+300000}});
 if(path.endsWith('/enrollment-intents/rotation'))return answer({intent:{id:'rotation',state:'committed',connection_id:connection.id}});
 if(path.endsWith('/enrollment-intents'))return failEnrollment?answer({sudo_required:true},401):answer({intent:syntheticIntake?{id:'intent',state:'reserved',intake_url:`${origin}/intake/intent`,expires_at:Date.now()+300000}:{id:'intent',status:'awaiting_activation'},intake_enabled:syntheticIntake});
 if(path.endsWith('/enrollment-intents/intent'))return answer({intent:{id:'intent',state:'committed',connection_id:connection.id}});
 if(path.endsWith('/assignments')&&method==='POST')return failAssignment?answer({error:{code:'REVISION_MISMATCH',message:'Connection changed. Refresh before assigning.'}},409):answer({assignment:{id:'assignment'}});
 if(path.endsWith('/assignments'))return answer({assignments:[{id:'assignment',agent_id:'fixture-agent',revision:1,status:'active'}]});
 if(path.endsWith('/sessions'))return answer({sessions:[{id:'session',status:'stale',expires_at:'2030-01-01T00:00:00Z'}]});
 if(path.endsWith('/activity'))return answer({events:[{id:'event',action:'item.read',status:'succeeded'}]});
 if(path.endsWith('/revoke')||(path===`/api/connections/${connection.id}`&&method==='PATCH'))return answer({connection});
 if(path.endsWith('/agent-configurations')&&method==='POST'){const agent={...body,id:agentId,revision:1,lifecycle:'draft',execution_enabled:false};agents.push(agent);return answer({agent,readiness},201);}
 if(path.endsWith(`/agent-configurations/${agentId}`)&&method==='PATCH'){Object.assign(agents[0],body);agents[0].revision+=1;return answer({agent:agents[0],readiness});}
 if(path.endsWith('/agent-profiles'))return answer({profiles:[]});
 if(path.endsWith('/agent-configurations'))return answer({agents});
 if(path.endsWith('/readiness'))return answer(readiness);
 if(path==='/api/operational-projects')return method==='POST'?answer({project}):answer({projects:[project],next_cursor:null});
 if(path===`/api/operational-projects/${project.id}`)return answer({project});
 if(path.endsWith('/draft'))return answer({draft:{title:'',instructions:'',revision:1,status:'draft'}});
 if(path.endsWith('/versions'))return answer({versions:[],next_cursor:null});
 if(path.endsWith('/runs'))return answer({runs:[],next_cursor:null});
 if(path.endsWith('/events'))return answer({events:[],next_cursor:null});
 if(path.endsWith('/access'))return answer({members:[],events:[]});
 if(path.endsWith('/directory'))return answer({projects:[]});
 return answer({notifications:[],unread_count:0});
});

const panel=()=>page.getByRole('region',{name:'Broker tasks'});
const posts=()=>requests.filter(r=>(r.path.startsWith(taskBase)||r.path.startsWith(proposalBase))&&r.method==='POST');
async function openSaved(){await page.goto(`${origin}/operational-projects/${project.id}?section=Agents`);await page.getByRole('button',{name:'View readiness'}).click();await page.getByRole('heading',{name:'Readiness checklist'}).waitFor();}
async function prepareFields(){const p=panel();await p.getByLabel('Assigned connection').selectOption(grantId);await p.getByLabel('Action').selectOption('item.set_state');await p.getByLabel('Allowed resource').selectOption(connection.resources[0]);assert.equal(await p.getByLabel('Task ID',{exact:true}).count(),0);}
async function authenticate(){const d=page.getByRole('dialog');await d.getByLabel('Password',{exact:true}).fill('synthetic-ui-password');await d.getByLabel('Authenticator Code').fill('123456');await d.locator('button[type=submit]').click();await d.waitFor({state:'hidden'});}
async function journey(name,fn){await fn();report.journeys.push(name);console.log('ok - '+name);}
async function capture(name){if(!process.env.BROWSER_ARTIFACTS)return;mkdirSync(process.env.BROWSER_ARTIFACTS,{recursive:true});await panel().evaluate(el=>{el.scrollIntoView({block:'start'});for(let parent=el.parentElement;parent;parent=parent.parentElement)if(parent.scrollTop>0)parent.scrollTop=Math.max(0,parent.scrollTop-72);});await page.screenshot({animations:'disabled',path:`${process.env.BROWSER_ARTIFACTS}/${name}.png`,fullPage:true});}
try {
 await journey('only compatible configured capability mounts task controls',async()=>{for(const pair of [['synthetic',true],['configured',false]]){[mode,compatible]=pair;const before=requests.filter(r=>r.path===taskBase).length;await openSaved();assert.equal(await panel().count(),0);assert.equal(requests.filter(r=>r.path===taskBase).length,before);const registrationsBefore=requests.filter(r=>r.path.endsWith('/broker-registrations')).length;await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/connections/capabilities')),page.getByRole('button',{name:'Edit draft',exact:true}).click()]);await page.getByLabel('Execution environment').waitFor();await page.getByRole('button',{name:'3. Controls'}).click();assert.equal(requests.filter(r=>r.path.endsWith('/broker-registrations')).length,registrationsBefore);await page.getByRole('button',{name:'Cancel setup'}).click();}mode='configured';compatible=true;execution=false;await openSaved();await panel().waitFor();assert(await panel().getByRole('button',{name:'Review action readiness'}).isDisabled());assert.equal(posts().length,0);execution=true;});
 await journey('saving configuration and opening readiness never starts a task',async()=>{await openSaved();await page.getByRole('button',{name:'Edit draft',exact:true}).click();await page.getByLabel('Agent name',{exact:true}).fill('Synthetic saved agent');assert(await page.getByRole('option',{name:'Offline worker — unavailable',exact:true}).isDisabled());assert.equal(await page.getByRole('option',{name:'Unsupported browser worker',exact:true}).count(),0);await page.getByLabel('Execution environment',{exact:true}).selectOption(environmentId);await page.getByRole('button',{name:'3. Controls'}).click();await page.getByLabel('Output destination',{exact:true}).selectOption(outputId);await page.getByRole('button',{name:'4. Review'}).click();await page.getByRole('button',{name:'Save agent configuration'}).click();await panel().waitFor();assert.equal(agents[0].work.environment_ref,environmentId);assert.equal(agents[0].controls.output_ref,outputId);assert.equal(posts().length,0);});
 await journey('failed independent preflight cannot expose start',async()=>{await prepareFields();preflight=false;await panel().getByRole('button',{name:'Review action readiness'}).click();await panel().getByRole('alert').waitFor();assert.equal(await panel().getByRole('button',{name:'Start reviewed task'}).count(),0);assert.equal(posts().filter(r=>r.path.endsWith('/start')).length,0);preflight=true;});
 await journey('expired independent readiness cannot start a saved agent',async()=>{reviewExpired=true;await panel().getByRole('button',{name:'Review action readiness'}).click();await panel().getByRole('button',{name:'Start reviewed task'}).click();await authenticate();await panel().getByRole('alert').filter({hasText:'expired'}).waitFor();assert.equal(posts().filter(r=>r.path.endsWith('/start')).length,0);reviewExpired=false;});
 await journey('typed review emits bounded fields and starts only after explicit authentication',async()=>{await panel().getByRole('button',{name:'Review action readiness'}).click();await panel().getByRole('button',{name:'Start reviewed task'}).waitFor();const body=posts().at(-1).body;assert.deepEqual(body,{configuration_revision:agents[0].revision,connection_id:connection.id,grant_id:grantId,operation:'item.set_state',resource_id:connection.resources[0],state:'closed'});assert.equal(posts().filter(r=>r.path.endsWith('/start')).length,0);await capture('typed-task-reviewed');await panel().getByRole('button',{name:'Start reviewed task'}).click();await page.getByRole('dialog').waitFor();assert.equal(posts().filter(r=>r.path.endsWith('/start')).length,0);await authenticate();await panel().getByText('awaiting_approval',{exact:true}).waitFor();assert.deepEqual(posts().find(r=>r.path.endsWith('/start')).body,{});});
 await journey('pending approval displays exact request and continuation uses issued reference',async()=>{assert.equal(await panel().getByRole('link',{name:'Open broker approval surface'}).getAttribute('href'),'https://broker.fixture.example/');assert.deepEqual(JSON.parse(await panel().locator('pre').textContent()),pending);assert(await panel().getByRole('button',{name:'Continue with issued approval'}).isDisabled());await capture('typed-task-pending-approval');await panel().getByLabel('Issued approval ID').fill(approvalId);await panel().getByRole('button',{name:'Continue with issued approval'}).click();await authenticate();await panel().getByText('completed',{exact:true}).waitFor();assert.deepEqual(posts().find(r=>r.path.endsWith('/approval')).body,{approval_id:approvalId});});
 await journey('refresh observes status and cancellation is explicit',async()=>{taskRows.push(taskRow('awaiting_approval',cancelTaskId));await panel().getByRole('button',{name:'Refresh task status'}).click();await page.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Refresh task status').disabled);assert(requests.some(r=>r.path===taskBase+`/${taskId}`&&r.method==='GET'));await panel().getByRole('button',{name:'Cancel task'}).click();assert.equal(posts().filter(r=>r.path.endsWith('/cancel')).length,0);await authenticate();await panel().getByRole('status').filter({hasText:'cancelled'}).waitFor();assert.equal(await panel().getByRole('button',{name:'Cancel task'}).count(),0);assert.equal(posts().filter(r=>r.path.endsWith('/start')).length,1);});
 if(process.env.BROWSER_ARTIFACTS)for(const theme of ['midnight','latte','office'])for(const width of [390,1536]) {
 await page.evaluate(v=>localStorage.setItem('pp-theme',v),theme);await page.setViewportSize({width,height:1100});taskRows=[taskRow('awaiting_approval')];await openSaved();await prepareFields();await panel().getByRole('button',{name:'Review action readiness'}).click();await panel().getByRole('button',{name:'Start reviewed task'}).waitFor();await page.addStyleTag({content:'html,body{overflow-x:visible!important}'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),`task overflow ${theme} ${width}`);await capture(`task-panel-${theme}-${width}`);await panel().getByRole('button',{name:'Start reviewed task'}).scrollIntoViewIfNeeded();await page.screenshot({animations:'disabled',path:`${process.env.BROWSER_ARTIFACTS}/task-panel-reviewed-start-${theme}-${width}.png`,fullPage:true});await panel().getByRole('button',{name:'Cancel task'}).scrollIntoViewIfNeeded();await page.screenshot({animations:'disabled',path:`${process.env.BROWSER_ARTIFACTS}/task-panel-approval-footer-${theme}-${width}.png`,fullPage:true});report.layout.push({theme,width});
 }
 assert.deepEqual(errors,[]);if(process.env.BROWSER_ARTIFACTS)writeFileSync(`${process.env.BROWSER_ARTIFACTS}/broker-tasks-ui-report.json`,JSON.stringify({...report,limitation:'Synthetic UI request fixtures only; no authority, vault or runner enforcement proof'},null,2));
} catch(e){await page.screenshot({animations:'disabled',path:'/tmp/broker-tasks-failure.png',fullPage:true});console.error(errors);throw e;} finally{await browser.close();await vite.close();}
