// Real app shell and components, scripted transport/API. No external website proof.
import assert from 'node:assert/strict';
import { readFileSync, mkdirSync } from 'node:fs';
import { createServer } from 'vite';
import { chromium } from '../../backend/node_modules/playwright-core/index.mjs';
const vite=await createServer({root:new URL('..',import.meta.url).pathname,server:{host:'127.0.0.1',port:0}});await vite.listen();
const origin=`http://127.0.0.1:${vite.httpServer.address().port}`,browser=await chromium.launch({executablePath:process.env.BROWSER_EXE||chromium.executablePath(),args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.stack));
const pid='11111111-1111-4111-8111-111111111111';let rid='22222222-2222-4222-8222-222222222222';
const budget={cpu:1,memory_mib:1024,temporary_disk_mib:512,max_seconds:900,max_actions:60,max_tokens:50000,max_usd:1};
const guide={id:'guide-1',version_number:2,content_hash:'f'.repeat(64),title:'Website review'};
const project={id:pid,name:'Website review',description:'Review tagarmor.com and summarize its services.',owner_name:'fixture-owner',owner_user_id:1,own_role:'owner',revision:1,agent_limits:budget,current_version:guide};
const config={name:project.name,work:{instructions:'## Objective\nReview tagarmor.com and summarize its services.\n\n## Procedure\n1. Open the website\n2. Review its services\n3. Summarize the findings\n\n## Completion\nA summary with source links.',guide_ref:{id:guide.id,sha256:guide.content_hash}},destinations:{entry_urls:['https://tagarmor.com'],allowed_origins:[]},model:{name:'fixture-model'},budgets:budget,artifacts:{record_video:false,retention_days:7}};
let state=null,revision=1,starts=0,stops=0,pending=[],submitted=[],failed=false,revoked=false;
const approval=(id,hash)=>({id,kind:'network_effect',state:'pending',action_sha256:hash.repeat(64),binding_sha256:hash.repeat(64),body_sha256:'c'.repeat(64),method:'GET',body_bytes:0,no_contact:true,origin:'https://cdn.example.com',purpose:`Load ${id} stylesheet`,expires_at:new Date(Date.now()+600000).toISOString()});
const data=()=>({authorization:{elevated:true,control_verified:true},run:{id:rid,configuration_name:project.name,attempt_id:`attempt-${starts}`,fence:1,revision,state,budgets:budget,usage:{actions:2,model_calls:1,usd:0.02},started_at:new Date(Date.now()-38000).toISOString()},controls:{can_cancel:['running','awaiting_approval'].includes(state),can_live:['running','awaiting_approval'].includes(state),can_approve:pending.length>0},pending_approvals:pending,uncertainties:[],activity:[{id:1,kind:'START_AUTHORIZED',created_at:'2026-10-05T11:15:00Z'},{id:2,kind:'LAUNCH_ACCEPTED',created_at:'2026-10-05T11:15:01Z'}],receipts:[]});
await page.addInitScript(()=>{
 localStorage.setItem('pp-theme','midnight');localStorage.setItem('user',JSON.stringify({id:1,username:'fixture-owner',role:'admin',permissions:[]}));window.__liveCalls=0;
 const RealWebSocket=WebSocket;window.WebSocket=class{constructor(url,protocols){if(!String(url).includes('/api/'))return new RealWebSocket(url,protocols);window.__liveCalls++;setTimeout(()=>this.onmessage?.({data:JSON.stringify({type:'ready',viewer:'fixture-viewer',ice_servers:[]})}),10);}readyState=1;close(){this.readyState=3;}send(){}};
 window.RTCPeerConnection=class{connectionState='new';constructor(){setTimeout(()=>{this.connectionState='connected';this.onconnectionstatechange?.();const canvas=document.createElement('canvas');canvas.width=960;canvas.height=600;const draw=()=>{const c=canvas.getContext('2d');c.fillStyle='#fafafa';c.fillRect(0,0,960,600);c.fillStyle='#111';c.font='36px sans-serif';c.fillText('Services — illustrative website view',50,80);for(const [i,title]of ['Consulting','Implementation','Support'].entries()){c.strokeStyle='#ddd';c.strokeRect(30+i*310,150,290,250);c.font='24px sans-serif';c.fillText(title,50+i*310,200);}c.font='16px sans-serif';c.fillText(String(Date.now()),50,550);};draw();this.tick=setInterval(draw,100);this.stream=canvas.captureStream(10);this.ontrack?.({track:this.stream.getVideoTracks()[0],streams:[this.stream]});},20);}close(){clearInterval(this.tick);this.stream?.getTracks().forEach(t=>t.stop());}};
});
await page.route('**/api/**',async route=>{
 const r=route.request(),p=new URL(r.url()).pathname,answer=(body,status=200)=>route.fulfill({status,json:body});
 if(p==='/api/auth/verify')return answer({user:{id:1,username:'fixture-owner',role:'admin',permissions:[]}});
 if(p==='/api/services')return answer([]);
 if(p.endsWith('/capabilities'))return answer({enabled:true,ui_available:true,streamlined_project_setup:true,agents_metadata_enabled:true,agent_runs_enabled:true,selected_browser_contract:'selected-browser.v1'});
 if(p==='/api/operational-projects')return answer({projects:[project]});
 if(p.endsWith('/'+pid))return answer({project});
 if(p.endsWith('/task'))return answer({task:{revision:1,can_edit:true,configuration:{id:'configuration-1',revision:1,configuration:config},defaults:{version:'project-defaults.v2',model:'fixture-model',budgets:budget}},schedules:[]});
 if(p.endsWith('/task/readiness'))return answer({can_start:!state||state==='cancelled',checks:[],active_run:state&&state!=='cancelled'?data().run:null,latest_run:state?data().run:null});
 if(p.endsWith('/project-defaults'))return answer({authorization:{control_verified:true,elevated:true}});
 if(p.endsWith('/task/start')){starts++;if(starts>1)rid='22222222-2222-4222-8222-222222222223';state='running';pending=[];revision++;return answer({run:data().run},202);}
 if(p.endsWith('/draft'))return answer({draft:{title:'Website review',instructions:config.work.instructions,revision:1,status:'published'}});
 if(p.endsWith('/versions'))return answer({versions:[guide],next_cursor:null});
 if(p.endsWith('/events'))return answer({events:[{id:'event-1',action:'project_task_saved',created_at:'2026-10-05T11:14:00Z'}],next_cursor:null});
 if(p.endsWith('/access'))return answer({owner:{username:'fixture-owner'},members:[]});
 if(p.endsWith('/browser-agent-configurations'))return answer({configurations:[],next_cursor:null});
 if(p.endsWith('/browser-agent-runs'))return answer({runs:state?[data().run]:[]});
 if(p.endsWith('/'+rid))return revoked?answer({error:'Project access is unavailable.'},403):answer(data());
 if(p.endsWith('/decision')){if(failed){failed=false;return answer({error:'Request changed',code:'APPROVAL_STALE'},409);}const id=p.split('/').at(-2);submitted.push({id,...r.postDataJSON(),revision:r.headers()['if-match']});revision++;pending=pending.filter(a=>a.id!==id);if(!pending.length)state='running';return answer(data());}
 if(p.endsWith('/cancel')){stops++;state='cancelled';revision++;return answer(data());}
 if(p.endsWith('/runs'))return answer({runs:[],next_cursor:null});
 return answer({});
});
await page.route('**/flightdeck-test*',async route=>route.fulfill({contentType:'text/html',body:await vite.transformIndexHtml('/flightdeck-test','<!doctype html><html lang="en"><head><title>Project workspace fixture</title></head><body><div id="root"></div><script type="module" src="/tests/browser-flightdeck-fixture.jsx"></script></body></html>')}));
const directory=process.env.BROWSER_ARTIFACTS||'.artifacts/browser-project-workspace';mkdirSync(directory,{recursive:true});
const axe=readFileSync(new URL('../../backend/node_modules/axe-core/axe.min.js',import.meta.url),'utf8');
const nav=()=>page.getByRole('navigation',{name:'Project panels'}).filter({visible:true});
const tab=name=>nav().getByRole('button',{name:new RegExp(name,'i')});
async function audit(name){if(await page.getByRole('dialog').count())await page.getByRole('dialog').evaluate(el=>Promise.all(el.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await page.evaluate(axe);const result=await page.evaluate(()=>axe.run(document.querySelector('[role=dialog]')||document.querySelector('[data-browser-flightdeck]'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));assert.deepEqual(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[],name);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),page.viewportSize().width);}
try{
 await page.goto(origin+'/flightdeck-test?integrated=1&workspace=1');await page.getByRole('button',{name:'Run now',exact:true}).waitFor();assert.equal(starts,0);assert.equal(await page.evaluate(()=>window.__liveCalls),0);await audit('Activity entry');await page.screenshot({path:`${directory}/activity-mobile.png`});
 await page.getByRole('button',{name:'Edit goal & settings',exact:true}).click();await page.getByRole('dialog').locator('summary').filter({hasText:'Advanced settings'}).click();await page.getByRole('button',{name:'Other agent, model & connection settings',exact:true}).click();await page.getByRole('heading',{name:'Training & reference files'}).waitFor();assert.equal(await page.locator('details').filter({has:page.locator('summary').filter({hasText:'Advanced agent configuration'})}).getAttribute('open'),'');await tab('Activity').click();await page.getByRole('button',{name:'Run now',exact:true}).click();await page.locator('[data-testid=live-browser][data-live-state=live]').waitFor();assert.equal(starts,1);assert.equal(await tab('Browser').getAttribute('aria-pressed'),'true');const video=page.locator('[data-testid=live-browser] video');await video.evaluate(e=>window.__originalViewer=e);
 for(const name of ['Activity','Resources','Details','Browser']){await tab(name).click();assert.equal(await page.evaluate(()=>window.__originalViewer===document.querySelector('[data-testid=live-browser] video')),true);assert.equal(await page.evaluate(()=>window.__liveCalls),1);await audit(name);}
 await page.screenshot({path:`${directory}/browser-mobile.png`});await page.locator('[data-browser-view-card] > header').getByRole('button',{name:'Open fullscreen browser',exact:true}).click();await page.locator('[data-browser-fullscreen=true]').waitFor();await tab('Activity').click();await page.getByRole('button',{name:'Edit goal & settings',exact:true}).click();await page.waitForFunction(()=>!document.fullscreenElement);await page.getByRole('dialog').getByRole('heading',{name:'Edit goal & settings'}).waitFor();await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await tab('Browser').click();
 pending=[approval('first','a'),approval('second','b')];state='awaiting_approval';await page.getByRole('button',{name:'Refresh run',exact:true}).click();await page.locator('[data-browser-view-card] > header').getByRole('button',{name:'Open fullscreen browser',exact:true}).click();await page.locator('[data-browser-fullscreen=true]').waitFor();await page.getByRole('button',{name:'Review requests',exact:true}).filter({visible:true}).click();await page.waitForFunction(()=>!document.fullscreenElement);const modal=page.getByRole('dialog',{name:'Review 2 items'});await modal.waitFor();assert.equal(await modal.getByRole('radio',{name:'Approve',exact:true}).count(),2);assert.equal(await modal.getByRole('radio',{checked:true}).count(),0);assert.equal(await modal.getByRole('button',{name:'Submit & continue'}).isDisabled(),true);
 await modal.getByRole('radio',{name:'Approve',exact:true}).first().check();await modal.getByRole('radio',{name:'Deny',exact:true}).nth(1).check();assert.equal(submitted.length,0);await audit('Review dialog');const titleBox=await modal.getByRole('heading',{name:'Review 2 items'}).boundingBox(),submitBox=await modal.getByRole('button',{name:'Submit & continue'}).boundingBox();assert(titleBox.y>=0&&submitBox.y+submitBox.height<=page.viewportSize().height,'review title and submission stay visible');await modal.locator('[data-review-scroll]').evaluate(e=>e.scrollTop=0);await page.screenshot({path:`${directory}/review-mobile.png`});
 await modal.getByRole('button',{name:'Submit & continue'}).click();await modal.waitFor({state:'hidden'});assert.deepEqual(submitted.map(s=>s.decision),['approve','deny']);assert.equal(submitted[1].revision,'"'+(Number(submitted[0].revision.replaceAll('"',''))+1)+'"');assert.equal(await tab('Browser').getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>window.__liveCalls),1);
 pending=[approval('third','c')];state='awaiting_approval';await page.getByRole('button',{name:'Refresh run',exact:true}).click();await page.getByRole('button',{name:'Review requests',exact:true}).filter({visible:true}).click();await page.getByRole('dialog').getByRole('radio',{name:'Approve',exact:true}).check();failed=true;await page.getByRole('dialog').getByRole('button',{name:'Submit & continue'}).click();await page.getByRole('dialog').getByRole('alert').waitFor();assert.equal(await page.getByRole('dialog').isVisible(),true,'failed decision retains modal');assert.equal(submitted.length,2);await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
 for(const width of [360,375,390,768,1280,1920]){await page.setViewportSize({width,height:width<768?844:1000});await tab('Resources').click();await audit(`Resources ${width}`);if(width===390)await page.screenshot({path:`${directory}/resources-mobile.png`});await tab('Details').click();await audit(`Details ${width}`);if(width===390)await page.screenshot({path:`${directory}/details-mobile.png`});if(width>=1024){const panes=await page.locator('[data-browser-deck-columns]').evaluate(e=>[...e.children].map(c=>c.getBoundingClientRect().width));assert(Math.abs(panes[0]/(panes[0]+panes[1])-.64)<.01);}if(width===1280){await tab('Activity').click();await page.locator('[data-project-activity]:not([hidden])').waitFor();await page.screenshot({path:`${directory}/desktop.png`});}}
 await page.setViewportSize({width:390,height:640});await tab('Activity').click();const scroll=page.locator('[data-browser-information-scroll]');await scroll.evaluate(e=>e.scrollTop=0);const touch=await page.context().newCDPSession(page);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:195,y:500}]});for(let i=1;i<=10;i++){await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:195,y:500-i*20}]});await page.waitForTimeout(20);}await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(250);assert(await scroll.evaluate(e=>e.scrollTop)>40,'center content scrolls on mobile');await touch.detach();
 await tab('Browser').click();await page.getByRole('button',{name:'Stop browser run',exact:true}).click();assert.equal(stops,1);await tab('Activity').click();await page.waitForFunction(()=>!document.querySelector('[data-project-task] button').disabled);await page.getByRole('button',{name:'Run again',exact:true}).click();await page.locator('[data-testid=live-browser][data-live-state=live]').waitFor();assert.equal(starts,2);revoked=true;await page.getByRole('button',{name:'Refresh run',exact:true}).click();await page.getByRole('alert').filter({hasText:'Project access is unavailable.'}).waitFor();assert.equal(await page.locator('[data-project-workspace]').count(),0);assert.equal(await page.locator('[data-testid=live-browser]').count(),0);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({synthetic:true,starts,stops,decisions:submitted.length,viewports:[360,375,390,768,1280,1920],accessibility_violations:0,checks:['Activity entry','Run selects browser','mounted viewer through navigation','fullscreen review and settings dialogs','individual batch decisions','failure retains modal','center touch scroll','Stop and Run again','advanced settings destination','revoked access clears workspace']}));
}catch(error){await page.screenshot({path:`${directory}/failure.png`});console.error(JSON.stringify({errors,layout:await page.evaluate(()=>{const e=document.querySelector('[data-browser-information-scroll]');return e?{height:e.clientHeight,scrollHeight:e.scrollHeight,scrollTop:e.scrollTop,box:e.getBoundingClientRect().toJSON()}:null}),body:await page.locator('body').innerText()}));throw error;}finally{await browser.close();await vite.close();}
