// The end-to-end contract for "the apps it builds are well made and lean on
// the base app".
//
// Three reported failures drive this file:
//   1. the shipped app had none of the base app's new features,
//   2. its UI/UX was poor,
//   3. the mockup preview didn't work.
//
// (1) happened because the build prompt never mentioned src/platform, and
// because a project seeded before a feature existed could never receive it.
// (2) happened because the default path — MVP build, then quick updates —
// ran a gate battery of literally ZERO. (3) happened because every failure
// path answered an iframe with JSON.
//
// THE LOAD-BEARING TEST in here is the last one: a FRESHLY SCAFFOLDED app,
// generated by the real scaffold functions, must pass every gate in the MVP
// profile. If it does not, every new project starts red and the gates get
// switched off instead of the app getting fixed.
//
// Native-free (risk R9) apart from running the gate scripts under /bin/sh,
// which is what the container does with them.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import {
  BASELINE_GATES, BASELINE_GATE_NAMES, baselineGatesForProfile, tierRank, asAdvisory,
  PLATFORM_INTACT_GATE_SCRIPT, MOBILE_OVERFLOW_GATE_SCRIPT, NO_DEAD_CONTROLS_GATE_SCRIPT,
  DESIGN_ADHERENCE_GATE_SCRIPT,
} from '../mock2/baseline-gates.js';
import {
  buildGateBattery, gateTier, gatesForProfile, gateProfileForMode, parseGateScripts,
  BUILD_MODE_QUICK, BUILD_MODE_MVP, BUILD_MODE_FULL,
} from '../mock2/cycle-logic.js';
import { buildRunnerSystemPrompt, buildRunnerClaudeMd, PLATFORM_SECTION } from '../mock2/runner-logic.js';
import {
  planBaseAppUpgrade, parsePlatformVersionFile, renderPlatformVersionFile,
  upgradeSummary, PLATFORM_OWNED_ALWAYS, isPlatformOwnedPath, PLATFORM_VERSION_PATH,
} from '../mock2/base-app-upgrade-logic.js';
import { detectPolishIntent } from '../mock2/ask-logic.js';
import {
  previewErrorCard, PREVIEW_ERRORS, escapePreviewHtml, renderDesignCssFromMockup,
  buildTokenBridgeCss, TOKEN_BRIDGE, TOKEN_BRIDGE_TARGETS, buildMockupSystemPrompt,
} from '../mock2/concept-logic.js';
import { buildPlatformFiles, buildPlatformRoutes, PLATFORM_MODULE_VERSION, PLATFORM_CSS } from '../mock2/scaffold-platform.js';
import { MOCK2_SCAFFOLD_VERSION, baseCss } from '../mock2/scaffold.js';
import { buildSeedFiles } from '../mock2/template.js';
import { buildAuthWiredFiles } from '../mock2/scaffold-auth.js';
import { MOCKUP_BASE_CSS } from '../mock2/mockup-template.js';

// ---- running a gate the way the container does ----

function runScript(script, files) {
  const dir = mkdtempSync(path.join(tmpdir(), 'pp-gate-'));
  try {
    for (const [rel, content] of Object.entries(files)) {
      const p = path.join(dir, rel);
      mkdirSync(path.dirname(p), { recursive: true });
      writeFileSync(p, content);
    }
    const sp = path.join(dir, '.gate.sh');
    writeFileSync(sp, script);
    try {
      return { code: 0, out: execFileSync('sh', [sp], { cwd: dir, encoding: 'utf8' }) };
    } catch (e) {
      return { code: e.status ?? 1, out: `${e.stdout || ''}${e.stderr || ''}` };
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// ---- fix 1: the build is told about the platform module ----

test('both prompt builders carry the platform contract — they cannot drift apart', () => {
  const system = buildRunnerSystemPrompt({ constitution: 'C', skills: [], buildMode: 'mvp' });
  const claudeMd = buildRunnerClaudeMd({ constitution: 'C', skills: [] });
  for (const [label, text] of [['system prompt', system], ['CLAUDE.md', claudeMd]]) {
    assert.ok(text.includes(PLATFORM_SECTION), `${label} embeds the shared section verbatim`);
    // The capabilities a build was silently discarding.
    for (const capability of ['theme.js', 'branding', 'legal', 'withApiKey', 'readonly.ts', '/api/meta']) {
      assert.ok(text.includes(capability), `${label} names ${capability}`);
    }
    assert.match(text, /NEVER delete it, re-implement it/, `${label} states the rule`);
    assert.ok(text.includes('platform-intact'), `${label} names the gate that enforces it`);
  }
});

// ---- fix 2: profiles — no build mode runs zero gates ----

test('profiles are cumulative and no mode runs an empty battery', () => {
  assert.ok(tierRank('quick') < tierRank('mvp'));
  assert.ok(tierRank('mvp') < tierRank('full'));
  assert.equal(tierRank('nonsense'), tierRank('full') + 1, 'an unknown tier is stricter than full, never looser');

  const quick = baselineGatesForProfile('quick').map((g) => g.name);
  const mvp = baselineGatesForProfile('mvp').map((g) => g.name);
  const full = baselineGatesForProfile('full').map((g) => g.name);
  for (const n of quick) assert.ok(mvp.includes(n), `${n} carries from quick into mvp`);
  for (const n of mvp) assert.ok(full.includes(n), `${n} carries from mvp into full`);
  assert.deepEqual(full.sort(), [...BASELINE_GATE_NAMES].sort(), 'full runs every baseline gate');

  for (const mode of [BUILD_MODE_QUICK, BUILD_MODE_MVP, BUILD_MODE_FULL]) {
    assert.ok(buildGateBattery([], mode).gates.length > 0, `${mode} runs at least one gate with NO framework gates`);
  }
});

test('gate tiering: declared wins, then the name, then full-only', () => {
  assert.equal(gateTier({ name: 'anything', tier: 'quick' }), 'quick', 'a declared tier wins');
  assert.equal(gateTier({ name: 'typecheck' }), 'quick');
  assert.equal(gateTier({ name: 'tsc' }), 'quick');
  assert.equal(gateTier({ name: 'ui-interaction' }), 'mvp');
  assert.equal(gateTier({ name: 'smoke' }), 'mvp');
  // The safe default: an operator's untagged four-minute check never lands in
  // the fast lanes just because nobody filled a field in.
  assert.equal(gateTier({ name: 'security-scan' }), 'full');
  assert.equal(gateTier({ name: 'some-bespoke-thing' }), 'full');
  assert.equal(gateProfileForMode('nonsense'), 'full', 'an unknown mode gets the strictest profile');
});

test('parseGateScripts carries an operator tier through (dropping it made every gate full-only)', () => {
  const parsed = parseGateScripts(JSON.stringify([
    { name: 'a', script: '#', order: 0, tier: 'quick' },
    { name: 'b', script: '#', order: 1, tier: 'NONSENSE' },
    { name: 'c', script: '#', order: 2 },
  ]));
  assert.equal(parsed[0].tier, 'quick');
  assert.equal(parsed[1].tier, undefined, 'a bogus tier is dropped, not trusted');
  assert.equal(parsed[2].tier, undefined);
  assert.deepEqual(gatesForProfile(parsed, 'quick').map((g) => g.name), ['a']);
});

test('advisory placement reports the failure and still exits 0', () => {
  const wrapped = asAdvisory('echo "the finding"\nexit 1\n', 'demo-gate');
  const r = runScript(wrapped, {});
  assert.equal(r.code, 0, 'never blocks');
  assert.match(r.out, /the finding/, 'the finding still reaches the report');
  assert.match(r.out, /not blocking in this build mode/);
});

// ---- the gates themselves, run for real ----

// A REAL project tree — the exact files provisioning writes, plus the auth
// wiring the base-app deploy pre-installs, plus the design.css that design
// approval produces.
//
// This used to hand-write its own app-shell.html, and that fixture LIED: the
// fabricated page carried a <script src="/theme.js"> that no real scaffold page
// had, so the suite reported green while the shipped base app had a theme
// toggle that applied to nothing. Fixtures for "does the real thing work" must
// be the real thing.
const GOOD_PLATFORM = () => {
  const files = {};
  for (const f of buildSeedFiles({ id: 1, name: 'Demo' }, {})) files[f.path] = f.content;
  for (const f of buildAuthWiredFiles()) files[f.path] = f.content;
  const design = renderDesignCssFromMockup(`<html><head><style>${MOCKUP_BASE_CSS}</style></head></html>`).css;
  files['state/design.css'] = design;
  files['public/design.css'] = design;
  return files;
};

test('GATE platform-intact: catches deletion, unmounting, a parallel store, and an unthemed page', () => {
  // Deleted.
  const gone = GOOD_PLATFORM(); delete gone['src/platform/readonly.ts'];
  const r1 = runScript(PLATFORM_INTACT_GATE_SCRIPT, gone);
  assert.equal(r1.code, 1);
  assert.match(r1.out, /lost files.*readonly\.ts/s);

  // Present but unmounted.
  const unmounted = GOOD_PLATFORM();
  unmounted['src/app.ts'] = '// nothing mounted here\n';
  const r2 = runScript(PLATFORM_INTACT_GATE_SCRIPT, unmounted);
  assert.equal(r2.code, 1);
  assert.match(r2.out, /no longer mounts/);

  // A second store for something the platform owns.
  const dup = GOOD_PLATFORM();
  dup['src/schema.ts'] = 'export const branding = pgTable("branding", { id: text("id") });\n';
  const r3 = runScript(PLATFORM_INTACT_GATE_SCRIPT, dup);
  assert.equal(r3.code, 1);
  assert.match(r3.out, /second store/);

  // A new page that will not theme.
  const unthemed = GOOD_PLATFORM();
  unthemed['public/reports.html'] = '<!doctype html><html><head><meta name="viewport" content="width=device-width"></head><body>x</body></html>';
  const r4 = runScript(PLATFORM_INTACT_GATE_SCRIPT, unthemed);
  assert.equal(r4.code, 1);
  assert.match(r4.out, /does not load \/theme\.js/);

  // An export the rest of the app imports.
  const noExport = GOOD_PLATFORM();
  noExport['src/platform/api-key-auth.ts'] = '// the exports are gone\n';
  const r5 = runScript(PLATFORM_INTACT_GATE_SCRIPT, noExport);
  assert.equal(r5.code, 1);
  assert.match(r5.out, /no longer exports withApiKey/);
});

test('GATE platform-intact: stands down for a project that never had the module', () => {
  const r = runScript(PLATFORM_INTACT_GATE_SCRIPT, { 'src/index.ts': 'console.log(1)', 'public/i.html': '<html></html>' });
  assert.equal(r.code, 0, 'a legacy app is not a deletion');
  assert.match(r.out, /Skipped/);
});

test('GATE mobile-overflow: fixed widths, uncollapsible grids, missing viewport', () => {
  const bad = runScript(MOBILE_OVERFLOW_GATE_SCRIPT, {
    'public/app.css': '.page{width:1200px}\n.rail{min-width:640px}\n.grid{grid-template-columns:repeat(4,1fr)}\n',
    'public/i.html': '<!doctype html><html><head></head><body></body></html>',
  });
  assert.equal(bad.code, 1);
  assert.match(bad.out, /fixed widths wider than a 390px phone/);
  assert.match(bad.out, /cannot collapse on a phone/);
  assert.match(bad.out, /no viewport meta/);

  const good = runScript(MOBILE_OVERFLOW_GATE_SCRIPT, {
    // max-width is fine at any size — only width/min-width cannot shrink.
    'public/app.css': '.wrap{max-width:1200px;margin:0 auto}\n.grid{grid-template-columns:repeat(3,1fr)}\n'
      + '@media (max-width:640px){.grid{grid-template-columns:1fr}}\n',
    'public/i.html': '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body></body></html>',
  });
  assert.equal(good.code, 0, good.out);
});

test('GATE no-dead-controls: a control works, submits, or is honestly disabled', () => {
  const bad = runScript(NO_DEAD_CONTROLS_GATE_SCRIPT, {
    'public/i.html': '<!doctype html><html><head></head><body><button>Export</button><a href="#">Settings</a></body></html>',
  });
  assert.equal(bad.code, 1);
  assert.match(bad.out, /nothing can reach/);
  assert.match(bad.out, /href="#" with no handler/);
  // The reported snippet must be the offending ELEMENT, not the whole file —
  // a no-op `tr` made every finding print the entire document.
  assert.match(bad.out, /^\s+<button>$/m);

  const good = runScript(NO_DEAD_CONTROLS_GATE_SCRIPT, {
    'public/i.html': '<!doctype html><html><head></head><body>'
      + '<button id="a">A</button><button type="submit">B</button>'
      + '<button disabled>Not built yet</button><a href="/x">go</a></body></html>',
  });
  assert.equal(good.code, 0, good.out);
});

// ---- fix 1b: the base-app upgrade path ----

test('base-app upgrade: never writes anything outside the platform-owned list', () => {
  const candidates = [
    { path: 'src/platform/schema.ts', content: 'ok' },
    { path: 'public/base.css', content: 'ok' },
    { path: 'src/app.ts', content: 'APPLICATION CODE — must never be rewritten' },
    { path: 'src/routes/orders.ts', content: 'APPLICATION CODE — must never be rewritten' },
  ];
  const plan = planBaseAppUpgrade({
    installed: { scaffold_version: 'v1', platform_version: 'p0' },
    currentScaffoldVersion: 'v2', currentPlatformVersion: 'p1',
    candidates, present: PLATFORM_OWNED_ALWAYS,
  });
  assert.ok(plan.needed);
  for (const p of plan.paths) assert.ok(isPlatformOwnedPath(p), `${p} is platform-owned`);
  assert.ok(!plan.paths.includes('src/app.ts'));
  assert.ok(!plan.paths.includes('src/routes/orders.ts'));
  assert.match(upgradeSummary(plan), /No application code was touched/);
});

test('base-app upgrade: auth-dependent files only when the project already has them', () => {
  const candidates = [
    { path: 'src/platform/schema.ts', content: 'a' },
    { path: 'src/platform/routes.ts', content: 'b' },
  ];
  const without = planBaseAppUpgrade({ candidates, present: ['src/platform/schema.ts'], currentPlatformVersion: 'p1' });
  assert.deepEqual(without.paths, ['src/platform/schema.ts']);
  const with_ = planBaseAppUpgrade({ candidates, present: ['src/platform/schema.ts', 'src/platform/routes.ts'], currentPlatformVersion: 'p1' });
  assert.deepEqual(with_.paths, ['src/platform/schema.ts', 'src/platform/routes.ts']);
});

test('base-app upgrade: no marker means first-time install; matching versions mean no-op', () => {
  const candidates = [{ path: 'src/platform/schema.ts', content: 'a' }];
  const first = planBaseAppUpgrade({ installed: null, currentScaffoldVersion: 'v2', currentPlatformVersion: 'p1', candidates, present: [] });
  assert.equal(first.needed, true);
  assert.equal(first.firstTime, true);
  assert.match(upgradeSummary(first), /for the first time/);

  const same = planBaseAppUpgrade({
    installed: { scaffold_version: 'v2', platform_version: 'p1' },
    currentScaffoldVersion: 'v2', currentPlatformVersion: 'p1', candidates, present: [],
  });
  assert.equal(same.needed, false);
  assert.match(upgradeSummary(same), /already up to date/);
});

test('the version marker round-trips, and a fresh seed stamps the CURRENT versions', () => {
  const text = renderPlatformVersionFile({ scaffoldVersion: 'sv', platformVersion: 'pv', at: '2026-01-01T00:00:00Z' });
  const back = parsePlatformVersionFile(text);
  assert.equal(back.scaffold_version, 'sv');
  assert.equal(back.platform_version, 'pv');
  assert.equal(parsePlatformVersionFile('not json'), null, 'tolerant of a corrupt marker');
  // A project seeded today must not immediately report an upgrade.
  const seeded = parsePlatformVersionFile(renderPlatformVersionFile({
    scaffoldVersion: MOCK2_SCAFFOLD_VERSION, platformVersion: PLATFORM_MODULE_VERSION,
  }));
  const plan = planBaseAppUpgrade({
    installed: seeded,
    currentScaffoldVersion: MOCK2_SCAFFOLD_VERSION, currentPlatformVersion: PLATFORM_MODULE_VERSION,
    candidates: [], present: [],
  });
  assert.equal(plan.needed, false, 'a brand-new project is already current');
  assert.equal(PLATFORM_VERSION_PATH, 'state/platform-version.json');
});

// ---- fix: polish is an Ask intent, not a build button ----

test('polish intent: catches a request to look, ignores a question about the design', () => {
  for (const q of ['polish this', 'review the design', 'check how the UI looks',
    'critique the visuals', 'look at the layout on mobile', 'audit the screens']) {
    assert.ok(detectPolishIntent(q), `"${q}" runs the design review`);
  }
  for (const q of ['how does the design token system work', 'why is design.css empty',
    'what does the branding endpoint return', 'explain the design system',
    'run the tests', 'add bob@example.com as an admin']) {
    assert.equal(detectPolishIntent(q), null, `"${q}" is a normal ask`);
  }
  assert.equal(detectPolishIntent('polish the design and fix the issues').apply, true, '"fix" queues the build too');
  assert.equal(detectPolishIntent('review the design').apply, false, 'a review alone changes nothing');
  // A long brief is an instruction, not "take a look".
  assert.equal(detectPolishIntent(`polish the design ${'x'.repeat(300)}`), null);
});

// ---- THE END-TO-END CHECK ----

test('a FRESHLY SCAFFOLDED app passes every gate in the MVP profile', () => {
  // If this fails, every new project starts red and the gates get switched off
  // instead of the app getting fixed. It is the reason the gates are blunt.
  const files = GOOD_PLATFORM();
  const battery = buildGateBattery([], BUILD_MODE_MVP).gates;
  assert.ok(battery.length >= BASELINE_GATES.length, 'the MVP profile runs the whole baseline');
  for (const gate of battery) {
    const r = runScript(gate.script, files);
    assert.equal(r.code, 0, `${gate.name} must pass on a fresh scaffold, got:\n${r.out}`);
  }
});

test('a fresh scaffold also passes the QUICK profile (a one-line edit is never wedged)', () => {
  const files = GOOD_PLATFORM();
  for (const gate of buildGateBattery([], BUILD_MODE_QUICK).gates) {
    const r = runScript(gate.script, files);
    assert.equal(r.code, 0, `${gate.name} must pass on a fresh scaffold, got:\n${r.out}`);
  }
});

test('the MVP battery CATCHES the app that shipped badly', () => {
  // The composite of every reported failure in one tree: the platform module
  // half-deleted, a parallel palette, a desktop-only width, and a dead button.
  const bad = GOOD_PLATFORM();
  delete bad['src/platform/readonly.ts'];
  bad['state/design.css'] = ':root{'
    + Array.from({ length: 20 }, (_, i) => `--app-t${i}:#10${i}`).join(';')
    + '}[data-theme="dark"]{--app-t0:#000}';
  bad['public/app.css'] = `:root{${Array.from({ length: 32 }, (_, i) => `--own-${i}:#ab${i}`).join(';')}}\n`
    + '.shell{width:1280px}\n'
    + Array.from({ length: 400 }, (_, i) => `.c${i}{color:var(--own-1);padding:8px}`).join('\n');
  bad['public/reports.html'] = '<!doctype html><html><head></head><body><button>Export</button></body></html>';

  const failed = [];
  for (const gate of buildGateBattery([], BUILD_MODE_MVP).gates) {
    if (runScript(gate.script, bad).code !== 0) failed.push(gate.name);
  }
  assert.deepEqual(failed.sort(), ['design-adherence', 'mobile-overflow', 'no-dead-controls', 'platform-intact']);
});

test('the same bad app on a QUICK update is only blocked by what a small edit should be blocked by', () => {
  const bad = GOOD_PLATFORM();
  bad['state/design.css'] = ':root{'
    + Array.from({ length: 20 }, (_, i) => `--app-t${i}:#10${i}`).join(';')
    + '}[data-theme="dark"]{--app-t0:#000}';
  bad['public/app.css'] = `:root{${Array.from({ length: 32 }, (_, i) => `--own-${i}:#ab${i}`).join(';')}}\n`
    + Array.from({ length: 400 }, (_, i) => `.c${i}{color:var(--own-1)}`).join('\n');

  const failed = [];
  for (const gate of buildGateBattery([], BUILD_MODE_QUICK).gates) {
    if (runScript(gate.script, bad).code !== 0) failed.push(gate.name);
  }
  // Pre-existing DESIGN debt must not wedge a one-line fix — it is advisory
  // here and blocking from the MVP build up.
  assert.deepEqual(failed, [], 'a quick update still goes through');
});

// ---- fix 3: the mockup preview says why, instead of rendering a JSON blob ----

test('preview failures render a readable HTML card, not JSON', () => {
  for (const key of ['offline', 'none', 'unreadable']) {
    const e = PREVIEW_ERRORS[key];
    const html = previewErrorCard(e);
    assert.match(html, /^<!doctype html>/, `${key} is a document the iframe can render`);
    assert.ok(html.includes(e.title), `${key} states what happened`);
    assert.ok(html.includes(e.detail), `${key} says what to do about it`);
    // It renders in a pane that is regularly 390px wide.
    assert.match(html, /name="viewport"/, `${key} is phone-safe`);
    assert.ok(!/width:\s*\d{3,}px/.test(html), `${key} has no fixed width`);
    // Not JSON — that was the bug.
    assert.ok(!html.trim().startsWith('{'), `${key} is not a JSON blob`);
  }
  assert.equal(PREVIEW_ERRORS.offline.status, 409, 'the status stays honest for programmatic callers');
  assert.equal(PREVIEW_ERRORS.none.status, 404);
});

test('a container error string is escaped into the card, never interpolated raw', () => {
  const html = previewErrorCard({
    title: 'The mockup could not be read',
    detail: 'cat: <script>alert(1)</script> & "quoted"',
  });
  assert.ok(!html.includes('<script>alert(1)</script>'));
  assert.ok(html.includes('&lt;script&gt;'));
  assert.equal(escapePreviewHtml(`<a href="x">&'`), '&lt;a href=&quot;x&quot;&gt;&amp;&#39;');
});

// ---- the shell must take the approved design, not a second palette ----

test('the token bridge covers EVERY variable the shell reads', () => {
  // Measured before this existed: the shell read 24 variables and an approved
  // design defined THREE. Fourteen --app-* names were declared nowhere at all,
  // every use falling back to a hardcoded hex — so the approved palette reached
  // the screens the build wrote and stopped at the edge of them.
  const design = renderDesignCssFromMockup(`<html><head><style>${MOCKUP_BASE_CSS}</style></head></html>`).css;
  const shell = baseCss() + PLATFORM_CSS;
  const declared = new Set([...design.matchAll(/(?:^|[;{\s])(--[a-z0-9-]+)\s*:/gi)].map((m) => m[1].toLowerCase()));
  const read = new Set([...shell.matchAll(/var\(\s*(--[a-z0-9-]+)/gi)].map((m) => m[1].toLowerCase()));
  const missing = [...read].filter((v) => !declared.has(v));
  assert.deepEqual(missing, [], 'every shell variable resolves from the approved design');
  assert.ok(read.size >= 20, `the shell really does read that many (${read.size})`);
});

test('the bridge is :root-only — a dark copy would be dead weight that can drift', () => {
  const css = buildTokenBridgeCss(':root{--bg:#fff;--surface-1:#fff;--text-1:#000;--accent:#08f}');
  assert.match(css, /==bridge==/);
  assert.ok(!/\[data-theme=[^\]]*\]\s*\{/.test(css), 'no dark RULE — custom properties re-substitute, so one block follows both themes');
  assert.equal((css.match(/:root\s*\{/g) || []).length, 1, 'exactly one block');
  assert.match(css, /--app-bg:\s*var\(--bg,/, 'mapped WITH the shell default as the fallback');
});

test('a sparse mockup narrows the bridge, it never blanks the shell', () => {
  const css = buildTokenBridgeCss(':root{--accent:#08f}');
  assert.match(css, /--app-primary:\s*var\(--accent,/);
  assert.ok(!css.includes('--app-text:'), 'no mapping for a token the design never defined');
  assert.equal(buildTokenBridgeCss(':root{--nothing-we-map:1}'), '', 'nothing to bridge → no block');
});

test('no page redefines a bridged name from an --app-* one (that is a var() cycle)', () => {
  // The sign-in page did exactly this (--bg: var(--app-bg)) while the bridge
  // defines --app-bg: var(--bg). CSS treats the cycle as invalid at
  // computed-value time and BOTH properties drop out — the page loses its
  // colours entirely.
  const sources = new Set(TOKEN_BRIDGE.map(([, src]) => src));
  const targets = new Set(TOKEN_BRIDGE_TARGETS);
  const pages = [...buildSeedFiles({ id: 1, name: 'T' }, {}), ...buildAuthWiredFiles()];
  const cycles = [];
  for (const f of pages) {
    for (const m of String(f.content || '').matchAll(/(--[a-z0-9-]+)\s*:\s*var\(\s*(--[a-z0-9-]+)/gi)) {
      if (sources.has(m[1].toLowerCase()) && targets.has(m[2].toLowerCase())) cycles.push(`${f.path}: ${m[1]} <- ${m[2]}`);
    }
  }
  assert.deepEqual(cycles, []);
});

test('design.css loads LAST on every page that links both', () => {
  // base.css re-declares five names the design also defines. Loaded second, the
  // platform silently overrode the approved values.
  let checked = 0;
  for (const f of [...buildSeedFiles({ id: 1, name: 'T' }, {}), ...buildAuthWiredFiles()]) {
    const c = String(f.content || '');
    const links = (c.match(/href="\/design\.css"/g) || []).length;
    if (!links) continue;
    assert.equal(links, 1, `${f.path} links design.css exactly once`);
    const d = c.indexOf('href="/design.css"');
    const b = c.indexOf('href="/base.css"');
    if (b < 0) continue;
    checked += 1;
    assert.ok(b < d, `${f.path} must link base.css before design.css`);
  }
  assert.ok(checked > 0, 'at least one page links both');
});

// ---- the base app is reachable, not just present ----

test('every generated page loads theme.js and platform.js', () => {
  // Shipped and loaded by NOTHING: the theme toggle applied to no page and the
  // branding/legal footer never rendered. The unit fixture missed it by
  // hand-writing a page that was correct.
  for (const f of [...buildSeedFiles({ id: 1, name: 'T' }, {}), ...buildAuthWiredFiles()]) {
    const c = String(f.content || '');
    if (!/<head[\s>]/.test(c) || f.path.endsWith('.js')) continue;
    assert.ok(c.includes('/theme.js'), `${f.path} loads theme.js, or its theme toggle does nothing`);
  }
});

test('the generated app has an ADMIN UI for the platform, not just endpoints', () => {
  const admin = buildAuthWiredFiles().find((f) => f.path === 'public/admin.html');
  assert.ok(admin, 'the admin console exists');
  for (const heading of ['Branding', 'Privacy policy', 'Images', 'API keys', 'Read-only database']) {
    assert.ok(admin.content.includes(heading), `the console surfaces ${heading}`);
  }
  assert.ok(admin.content.includes('/platform-admin.js'), 'and loads the script that drives it');
  const js = buildPlatformFiles().find((f) => f.path === 'public/platform-admin.js');
  assert.ok(js, 'the driver is platform-owned, so it rides the upgrade path');
  assert.ok(isPlatformOwnedPath('public/platform-admin.js'));
  // Every admin control must have something to talk to.
  for (const route of ['/branding', '/branding/pages/', '/branding/assets', '/api-keys', '/db/readonly']) {
    assert.ok(js.content.includes(route), `it calls ${route}`);
  }
});

test('the mockup is told the base app already exists', () => {
  // Without this the mockup depicts only the idea, the inventory carries only
  // those screens, and the built app has admin features with no way in.
  const p = buildMockupSystemPrompt({}).toLowerCase();
  for (const k of ['sign-in', 'admin', 'privacy', 'terms', 'api keys', 'asset library', 'read-only', 'footer']) {
    assert.ok(p.includes(k), `the mockup prompt names ${k}`);
  }
});

test('GATE design-adherence: an unbridged shell or a backwards load order is a failure', () => {
  const files = GOOD_PLATFORM();
  assert.equal(runScript(DESIGN_ADHERENCE_GATE_SCRIPT, files).code, 0, 'the real tree is green');

  // The check is SEMANTIC, not a marker grep: a mockup-derived design.css
  // drives the shell through the generated bridge, a preset-derived one
  // declares --app-* directly. Either satisfies it; neither does not.
  const noBridge = GOOD_PLATFORM();
  noBridge['state/design.css'] = noBridge['state/design.css'].replace(/==bridge==[\s\S]*?==\/bridge==/, '');
  const r1 = runScript(DESIGN_ADHERENCE_GATE_SCRIPT, noBridge);
  assert.equal(r1.code, 1, r1.out);
  assert.match(r1.out, /the app SHELL ignores the approved design/);

  const backwards = GOOD_PLATFORM();
  backwards['public/x.html'] = '<html><head>\n<link href="/design.css">\n<link href="/base.css">\n</head></html>';
  const r2 = runScript(DESIGN_ADHERENCE_GATE_SCRIPT, backwards);
  assert.equal(r2.code, 1);
  assert.match(r2.out, /links design\.css BEFORE base\.css/);
});
