import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,readFileSync,rmSync,mkdirSync,writeFileSync } from 'node:fs';
import { rootCertificates } from 'node:tls';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { makeDb,inputFor,apiFixture,dockerFixture,baoFixture } from './helpers/openbao-fixture.js';
import { save,apply,review,readOpenBao,secrets,state,acknowledge } from '../lib/setup-engine/openbao-store.js';
import { runOnce,executeJob,reconcile } from '../lib/setup-engine/executor.js';
import { sweepSetupEngineOnBoot } from '../lib/setup-engine/backend.js';
import { runBackendSteps } from '../lib/setup-engine/backend-steps.js';
import { backendStepDeps } from '../mock2/ops.js';
import { ensureRuntime } from '../lib/setup-engine/openbao-runtime.js';
import { initialize } from '../lib/setup-engine/openbao-handoff.js';
import { operatorAction } from '../lib/setup-engine/openbao-operator.js';
import { verifyMachine,verifyAccess } from '../lib/setup-engine/openbao-access.js';
import { verifyClient } from '../lib/setup-engine/openbao-identity.js';
import { createClient } from '../lib/setup-engine/openbao-api.js';
import { digest,namesFor,OPENBAO_APP,callbackFor } from '../lib/setup-engine/openbao-logic.js';
import { getJob,claimNextJob,acquireLock,releaseLock,createJob,startJob } from '../lib/setup-engine/store.js';
import { validateRunnerJob } from '../lib/setup-engine/logic.js';
const {buildDomainCaddyConfig}=await import('../routes/services.js');
const handle={id:'fixture',fence(){},checkpoint(){},generated(){}};
const withDb=async(fn,mode='install')=>{const dir=mkdtempSync(join(tmpdir(),'g6-')),db=makeDb(join(dir,'db.sqlite'),{mode});try{save(db,inputFor(mode));await fn(db,dir);}finally{db.close();rmSync(dir,{recursive:true,force:true});}};
const approval=db=>{const v=review(db);return {revision:v.revision,reviewToken:v.reviewToken,reviewed:true};};
function renderer(db,dir){mkdirSync(join(dir,'sites'),{recursive:true});let broken=false;return {caddyFilePath:d=>join(dir,'sites',d+'.caddy'),regenerate:async(db,d)=>{const rows=db.prepare('SELECT r.*,s.target_ip,s.kind,s.type FROM service_http_routes r JOIN services s ON s.id=r.service_id WHERE r.domain=?').all(d);writeFileSync(join(dir,'sites',d+'.caddy'),buildDomainCaddyConfig(rows,d));},adapt:async()=>{if(broken){broken=false;throw Error('Caddy fixture error');}},reload:async()=>{},writeConfig:async(p,s)=>writeFileSync(p,s),removeConfig:async p=>rmSync(p,{force:true}),break(){broken=true;}};}
function harness(db,dir,{initialized=false,sealed=true,...overrides}={}){const docker=dockerFixture(),api=baoFixture(db,{initialized,sealed}),render=renderer(db,join(dir,'caddy'));let now=Date.now();const deps={db,owner:'runner@g6#123:a',exec:docker,nowMs:()=>now,openbaoDeps:{root:join(dir,'owned'),recoveryRoot:join(dir,'recovery'),send:api.send,clientProbe:async()=>({fixture:true}),providerProbe:async()=>({fixture:true}),flow:async()=>({fixture:true}),sleep:async()=>{},attempts:1,...overrides}};
  const tick=async()=>{now+=35000;await runOnce(deps,{max:1,reconcileFirst:false});await runBackendSteps({db,owner:'backend@g6#124:a',nowMs:()=>now,sleep:async()=>{},deps:backendStepDeps({getDb:()=>db,renderDeps:render})});};
  return {api,docker,render,deps,advance:n=>now+=n,get now(){return now;},tick,async finish(){for(let i=0;i<5;i++){await tick();const j=getJob(db,readOpenBao(db).last_job_id);if(!['queued','running'].includes(j.status))return j;}throw Error('G6 job did not settle');}};
}
async function bootstrapReady(db,h){const r=readOpenBao(db);if(r.config.mode==='install')db.prepare('UPDATE setup_openbao SET handoff_ack=1').run();h.api.sealed=false;return operatorAction(db,'bootstrap',{...approval(db),bootstrapToken:'g6-bootstrap-token',databasePassword:'g6-database-password',revokeBootstrap:true},'admin',{send:h.api.send,clientProbe:async()=>({}),providerProbe:async()=>({}),databaseProbe:async()=>{}});}

test('G6.1 HTTP admin/CSRF/fresh-auth, inert saved plan and encrypted separate credentials',async()=>{const db=makeDb();try{const f=await apiFixture(db);try{assert.equal((await f.request('/openbao',{who:null})).status,401);assert.equal((await f.request('/openbao',{who:'user'})).status,403);for(const option of [{csrf:false},{who:'cold'}])assert([401,403].includes((await f.request('/openbao',{method:'PUT',body:inputFor('install'),...option})).status));assert.equal((await f.request('/openbao',{method:'PUT',body:{...inputFor('install'),rootToken:'not-allowed'}})).status,400);assert.equal((await f.request('/openbao',{method:'PUT',body:inputFor('install')})).status,200);assert.equal(db.prepare('SELECT count(*) n FROM setup_jobs').get().n,0);assert(db.prepare('SELECT value FROM setup_openbao_credentials').get().value.startsWith('enc:v1:'));assert(!JSON.stringify(state(db)).includes(inputFor('install').clientSecret));assert.equal((await f.request('/openbao/apply',{method:'POST',body:{...approval(db),reviewToken:'0'.repeat(64)}})).status,409);}finally{await f.close();}}finally{db.close();}});
test('G6.1 skipped/changed plan and unsupported external initialization install nothing',()=>withDb(db=>{const p=JSON.parse(db.prepare('SELECT choices_json FROM setup_platform_plan').get().choices_json);p.openbao.mode='skip';db.prepare('UPDATE setup_platform_plan SET choices_json=?').run(JSON.stringify(p));assert.throws(()=>apply(db,approval(db),'admin'),/skipped/);assert.equal(db.prepare('SELECT count(*) n FROM setup_jobs').get().n,0);}));
test('G6.1/.2 production Docker/Caddy adapters, encrypted initialization and receipt; retry never initializes twice',()=>withDb(async(db,dir)=>{const h=harness(db,dir);apply(db,approval(db),'admin');let j=await h.finish();assert.equal(j.status,'recovery_required',j.reason);assert.match(j.reason,/acknowledgement/);assert.equal(h.api.initCount,1);const r=readOpenBao(db),packagePath=join(dir,'recovery',r.credential_ref+'.json'),p=JSON.parse(readFileSync(packagePath));assert.equal(p.shares.length,3);const count=h.docker.calls.filter(a=>a.includes('create')).length;apply(db,approval(db),'admin');j=await h.finish();assert.equal(h.api.initCount,1);assert.equal(h.docker.calls.filter(a=>a.includes('create')).length,count);assert.throws(()=>acknowledge(db,{...approval(db),receipt:'wrong-receipt-long-enough'}),/receipt/);acknowledge(db,{...approval(db),receipt:p.receipt});assert(readOpenBao(db).handoff_ack);const caddy=readFileSync(join(dir,'caddy/sites/bao.example.com.caddy'),'utf8');assert(caddy.includes('127.0.0.1:18200'));assert(caddy.includes('192.0.2.10'));assert.equal(db.prepare("SELECT target_port FROM service_http_routes WHERE id='test-route'").get().target_port,18443);}));
test('G6.2 lost/interrupted handoff is recovery required without reset or second init',()=>withDb(async(db,dir)=>{const api=baoFixture(db),r=readOpenBao(db);await initialize(db,r,createClient(r.config.origin,{send:api.send}),{job:handle,recoveryRoot:join(dir,'recovery')});db.prepare('UPDATE setup_openbao SET handoff_digest=NULL').run();await initialize(db,readOpenBao(db),createClient(r.config.origin,{send:api.send}),{job:handle,recoveryRoot:join(dir,'recovery')});assert(readOpenBao(db).handoff_digest);rmSync(join(dir,'recovery',r.credential_ref+'.json'));await assert.rejects(initialize(db,readOpenBao(db),createClient(r.config.origin,{send:api.send}),{job:handle,recoveryRoot:join(dir,'recovery')}),/recovery required/);assert.equal(api.initCount,1);api.initialized=false;await assert.rejects(initialize(db,readOpenBao(db),createClient(r.config.origin,{send:api.send}),{job:handle,recoveryRoot:join(dir,'recovery')}),/never repeats/);}));
test('G6.2/.3 operator shares/bootstrap transient, scoped owned resources, repeatable credentials and preservation',()=>withDb(async(db,dir)=>{const h=harness(db,dir,{initialized:true});let result=await operatorAction(db,'unseal',{...approval(db),share:'validDisposableShare12345'},'admin',{send:h.api.send});assert.equal(result.result.state,'sealed');result=await operatorAction(db,'unseal',{...approval(db),share:'validDisposableShare12345'},'admin',{send:h.api.send});assert.equal(result.result.state,'unsealed');const before=db.prepare('SELECT * FROM sso_config').get();await bootstrapReady(db,h);assert.equal(h.api.revocations,1);const keys=secrets(db,readOpenBao(db));h.api.resetBootstrap();await bootstrapReady(db,h);assert.deepEqual(secrets(db,readOpenBao(db)),keys);assert.equal(h.api.secretIds.size,1);assert.deepEqual(db.prepare('SELECT * FROM sso_config').get(),before);const rows=JSON.stringify([state(db),db.prepare('SELECT * FROM setup_jobs').all(),db.prepare('SELECT * FROM setup_job_events').all()]);for(const x of ['validDisposableShare12345','g6-bootstrap-token','g6-database-password',keys.machine])assert(!rows.includes(x));},'connect'));
test('G6.3 machine positive/denied checks, broad policy and owned-config drift rejected',()=>withDb(async(db,dir)=>{const h=harness(db,dir,{initialized:true,sealed:false});await bootstrapReady(db,h);const r=readOpenBao(db),api=createClient(r.config.origin,{send:h.api.send}),token=await verifyMachine(r,secrets(db,r),api);assert((await verifyAccess(r,token,api)).machinePolicy);h.api.resources.get(`/v1/auth/${namesFor(r).oidc}/role/mapped`).bound_claims={};await assert.rejects(verifyAccess(r,token,api),/differs/);h.api.broad=true;await assert.rejects(verifyMachine(r,secrets(db,r),api),/limited policy/);},'connect'));
test('G6.3 dedicated Keycloak client exact callback/groups verified read-only; unsafe clients refused',()=>withDb(async db=>{const r=readOpenBao(db);const c={id:'client',clientId:r.config.clientId,protocol:'openid-connect',enabled:true,standardFlowEnabled:true,redirectUris:[callbackFor(r)],webOrigins:[r.config.origin]},m={protocolMapper:'oidc-group-membership-mapper',config:{'claim.name':'groups','id.token.claim':'true','full.path':'true'}};const getReader=async()=>async p=>p.includes('protocol-mappers')?[m]:[c];assert((await verifyClient(db,r,{getReader})).readOnly);c.redirectUris=['https://bao.example.com/*'];await assert.rejects(verifyClient(db,r,{getReader}),/callbacks/);c.redirectUris=[callbackFor(r)];c.directAccessGrantsEnabled=true;await assert.rejects(verifyClient(db,r,{getReader}),/dedicated/);}));
test('G6.5 connect runtime remains untouched; seal/unavailable and identity changes never verify',()=>withDb(async(db,dir)=>{const h=harness(db,dir,{initialized:true,sealed:false});await bootstrapReady(db,h);apply(db,approval(db),'admin');let j=await h.finish();assert.equal(j.status,'succeeded',j.reason);assert.equal(h.docker.calls.length,0);h.api.sealed=true;apply(db,approval(db),'admin');j=await h.finish();assert.equal(j.status,'recovery_required');assert.match(j.reason,/sealed/);assert.equal(readOpenBao(db).verified_json,null);h.api.sealed=false;h.api.unavailable=true;apply(db,approval(db),'admin');j=await h.finish();assert.match(j.reason,/unavailable/);h.api.unavailable=false;h.api.cluster='replaced-cluster';apply(db,approval(db),'admin');j=await h.finish();assert.match(j.reason,/identity changed/);},'connect'));
test('G6.5 runner restart reconciliation and backend refusal preserve the queued revision',()=>withDb(async(db,dir)=>{const h=harness(db,dir,{initialized:true,sealed:false});await bootstrapReady(db,h);apply(db,approval(db),'admin');const dead=claimNextJob(db,{owner:'runner@dead#1:a',kinds:['openbao_apply'],nowMs:h.now,leaseMs:1});assert(dead);h.advance(100000);await reconcile({...h.deps,nowMs:h.now});assert.equal((await h.finish()).status,'succeeded');apply(db,approval(db),'admin');h.advance(100000);const claimed=claimNextJob(db,{owner:'backend@fixture#4:a',kinds:['openbao_apply'],nowMs:h.now});assert.equal((await executeJob(claimed,{...h.deps,owner:'backend@fixture#4:a'})).outcome,'runner_unavailable');},'connect'));
test('G6.5 interrupted operator request is recorded without replay or a guest recovery instruction',()=>withDb(db=>{const owner='backend@dead#4:a',j=createJob(db,{kind:'openbao_operator',app:OPENBAO_APP,plan:{params:{revision:1,action:'bootstrap'}},nowMs:1000});startJob(db,{id:j.id,owner,nowMs:1000,leaseMs:1});acquireLock(db,{app:OPENBAO_APP,owner,operation:'openbao_operator',jobId:j.id,nowMs:1000,leaseMs:1});sweepSetupEngineOnBoot(db,{owner:'backend@new#5:a',nowMs:100000});const row=getJob(db,j.id);assert.equal(row.status,'recovery_required');assert.match(row.reason,/transient/);assert(!row.reason.includes('incus'));assert(acquireLock(db,{app:OPENBAO_APP,owner:'backend@new#5:a',operation:'openbao_operator',nowMs:100001}).ok);}));
test('G6.1/.5 foreign resources, runtime drift and missing configuration fail without replacement',()=>withDb(async(db,dir)=>{const r=readOpenBao(db),d=dockerFixture(),n=namesFor(r),root=join(dir,'owned');d.objects.volume.set(n.volume,{Labels:{}});await assert.rejects(ensureRuntime(r,{exec:d,job:handle,root}),/collision/);assert(!d.calls.some(a=>a[1]==='create'));d.objects.volume.clear();await ensureRuntime(r,{exec:d,job:handle,root});d.objects.container.get(n.server).HostConfig.PortBindings['8200/tcp'][0].HostIp='0.0.0.0';await assert.rejects(ensureRuntime(r,{exec:d,job:handle,root}),/profile/);rmSync(join(root,'owner.json'));await assert.rejects(ensureRuntime(r,{exec:d,job:handle,root}),/Restore/);}));
test('G6.5 runner job schema refuses command and secret additions',()=>withDb(db=>{const j=apply(db,approval(db),'admin').job;assert(validateRunnerJob(j).ok);assert(!validateRunnerJob({...j,plan_json:JSON.stringify({params:{revision:1,token:'forbidden'}})}).ok);}));
test('G6.2 plaintext initialization response is refused without writing recovery material or retrying init',()=>withDb(async(db,dir)=>{let initialized=false,count=0;const send=async(_o,p)=>{if(p==='/v1/sys/seal-status')return {status:200,body:{initialized,sealed:true}};initialized=true;count++;return {status:200,body:{keys_base64:['plain-share','plain-share','plain-share'],root_token:'plain-root-token'}};};const api=createClient('https://bao.example.com',{send});await assert.rejects(initialize(db,readOpenBao(db),api,{job:handle,recoveryRoot:join(dir,'recovery')}),/encrypted handoff/);assert.equal(readOpenBao(db).handoff_digest,null);await assert.rejects(initialize(db,readOpenBao(db),api,{job:handle,recoveryRoot:join(dir,'recovery')}),/recovery required/);assert.equal(count,1);}));
test('G6.3 connect collisions and missing registered machine credential preserve foreign resources and never reissue',()=>withDb(async(db,dir)=>{const h=harness(db,dir,{initialized:true,sealed:false}),r=readOpenBao(db),n=namesFor(r);h.api.mounts[n.database+'/']={type:'database',description:'external-owner'};await assert.rejects(bootstrapReady(db,h),/belongs/);assert(!h.api.calls.some(c=>['PUT','POST'].includes(c.method)));delete h.api.mounts[n.database+'/'];await bootstrapReady(db,h);h.api.resetBootstrap();h.api.secretIds.clear();const before=h.api.calls.filter(c=>c.path.endsWith('/custom-secret-id')).length;await assert.rejects(bootstrapReady(db,h),/registration.*uncertain/);assert.equal(h.api.calls.filter(c=>c.path.endsWith('/custom-secret-id')).length,before);},'connect'));
test('G6.5 slow recorded route child keeps parent queued; unrelated lock refuses operator share',()=>withDb(async(db,dir)=>{const h=harness(db,dir);apply(db,approval(db),'admin');await runOnce(h.deps,{max:1,reconcileFirst:false});const r=readOpenBao(db),child=getJob(db,r.edge_job_id);const held=acquireLock(db,{app:OPENBAO_APP,owner:'backend@slow#9:a',operation:'configure_openbao_route',jobId:child.id,leaseMs:999999,nowMs:h.now});h.advance(35000);await runOnce(h.deps,{max:1,reconcileFirst:false});assert.equal(getJob(db,r.last_job_id).status,'queued');releaseLock(db,{app:OPENBAO_APP,owner:'backend@slow#9:a',epoch:held.lock.epoch});await h.finish();acquireLock(db,{app:OPENBAO_APP,owner:'runner@other#9:a',operation:'openbao_apply',jobId:'other',leaseMs:999999});await assert.rejects(operatorAction(db,'unseal',{...approval(db),share:'validDisposableShare12345'},'admin',{send:h.api.send}),/lease/);}));
test('G6.1 managed transport refuses redirects and special-use destinations; sealed and unavailable states differ',async()=>{const {openbaoRequest,status}=await import('../lib/setup-engine/openbao-api.js');const {EventEmitter}=await import('node:events');let sent;const request=(url,options,cb)=>{sent={url,options};const req=new EventEmitter();req.end=()=>{const res=new EventEmitter();res.statusCode=302;cb(res);queueMicrotask(()=>{res.emit('data',Buffer.from('DO-NOT-LOG'));res.emit('end');req.emit('close');});};req.destroy=()=>req.emit('error',Error());return req;};assert.deepEqual(await openbaoRequest('https://bao.example.com','/v1/sys/seal-status',{resolve:async()=>[{address:'10.1.2.3'}],request}),{status:302,body:null});assert.equal(sent.options.agent,false);await assert.rejects(openbaoRequest('https://bao.example.com','/v1/sys/seal-status',{resolve:async()=>[{address:'169.254.169.254'}],request}),/blocked/);await assert.rejects(openbaoRequest('https://bao.example.com','https://other.example/v1/sys/init'),/outside/);assert.equal((await status(async()=>({status:200,body:{initialized:false,sealed:true}}))).state,'uninitialized');assert.equal((await status(async()=>({status:200,body:{initialized:true,sealed:true}}))).state,'sealed');assert.equal((await status(async()=>({status:200,body:{initialized:true,sealed:false}}))).state,'unsealed');assert.equal((await status(async()=>({status:503}))).state,'unavailable');});

test('G6.4 managed public CA mount is read-only, reused and drift-protected',()=>withDb(async(db,dir)=>{
  const r=readOpenBao(db);r.config.database.caPem=rootCertificates[0];const d=dockerFixture(),root=join(dir,'ca-owned');
  await ensureRuntime(r,{exec:d,job:handle,root});const before=d.calls.filter(a=>a[1]==='create').length;
  const mount=d.objects.container.get(namesFor(r).server).Mounts.find(m=>m.Destination==='/openbao/config/postgres-ca.pem');assert(mount);assert.equal(mount.RW,false);
  await ensureRuntime(r,{exec:d,job:handle,root});assert.equal(d.calls.filter(a=>a[1]==='create').length,before);
  writeFileSync(join(root,'postgres-ca.pem'),'drift');await assert.rejects(ensureRuntime(r,{exec:d,job:handle,root}),/public CA file drifted/);
}));
