import crypto from 'node:crypto';

const RFC1918 = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16'];
const VPN_CIDR = '10.100.0.0/24';
const LOCALHOST_V4 = '127.0.0.0/8';
const LOCALHOST_V6 = '::1/128';

/**
 * Resolve a rule's effective source restriction to a list of nft set
 * elements. `source_cidrs` overrides `scope` when present.
 */
function sourcesFor(rule) {
  if (rule.source_cidrs && rule.source_cidrs.length > 0) {
    return rule.source_cidrs;
  }
  switch (rule.scope) {
    case 'public':         return null; // any source
    case 'lan-only':       return RFC1918;
    case 'vpn-only':       return [VPN_CIDR];
    case 'localhost-only': return [LOCALHOST_V4];
    default:
      throw new Error(`unknown scope: ${rule.scope}`);
  }
}

function portMatch(rule) {
  if (rule.port_end && rule.port_end !== rule.port_start) {
    return `${rule.proto} dport ${rule.port_start}-${rule.port_end}`;
  }
  return `${rule.proto} dport ${rule.port_start}`;
}

function comment(rule) {
  const id = rule.id.replace(/"/g, '');
  const reason = (rule.reason ?? '').replace(/"/g, '');
  return `comment "${id}: ${reason}"`;
}

function renderAllowRule(rule) {
  const sources = sourcesFor(rule);
  const port = portMatch(rule);
  if (sources === null) {
    return `    ${port} accept ${comment(rule)}`;
  }
  // nft accepts an inline anonymous set { a, b, c }
  return `    ip saddr { ${sources.join(', ')} } ${port} accept ${comment(rule)}`;
}

/**
 * Render the full nft ruleset for `table inet proxypilot` from state.
 *
 * Layout:
 *   - base_input:        base allowlist + loopback + ct-state + ICMP
 *   - discovered_input:  enabled discovered + manual rules
 *   - container_egress:  per-container egress (placeholder this step)
 *   - nat_postrouting:   NAT (placeholder; populated when VPN lands)
 *
 * The host's main `input` chain is wired into base_input + discovered_input
 * once at install time; this function does NOT touch that chain.
 */
export function render(state) {
  const enabledBase = state.base.filter(r => r.enabled);
  const enabledDiscovered = state.discovered.filter(r => r.enabled);

  const baseInputBody = [
    '    iif lo accept',
    '    ct state established,related accept',
    '    ct state invalid drop',
    '    ip protocol icmp icmp type echo-request limit rate 5/second accept',
    '    ip6 nexthdr icmpv6 icmpv6 type echo-request limit rate 5/second accept',
    ...enabledBase.map(renderAllowRule),
  ].join('\n');

  const discoveredInputBody = enabledDiscovered.length
    ? enabledDiscovered.map(renderAllowRule).join('\n')
    : '    # (no enabled discovered rules)';

  // The leading `add table` + `flush table` pair makes the apply
  // idempotent: it creates the table on first run and empties every
  // chain on subsequent runs, so the redeclaration below replaces the
  // old ruleset rather than appending to it. nft applies the whole file
  // in one transaction, so the firewall is never half-flushed.
  const ruleset = `# Generated by ProxyPilot firewall manager. Do not edit by hand.
# Source of truth: /var/lib/proxypilot/firewall.json
add table inet proxypilot
flush table inet proxypilot

table inet proxypilot {
  chain base_input {
${baseInputBody}
  }

  chain discovered_input {
${discoveredInputBody}
  }

  chain container_egress {
    # populated by container-egress step
  }

  chain nat_postrouting {
    type nat hook postrouting priority 100;
    # populated when VPN module lands
  }
}
`;

  return ruleset;
}

/**
 * Stable checksum of the rendered ruleset. Logged on every reconcile so
 * drift between state and live can be detected without diffing rules
 * directly.
 */
export function checksum(ruleset) {
  return 'sha256:' + crypto.createHash('sha256').update(ruleset).digest('hex');
}
