import https from 'node:https';
import {readFileSync} from 'node:fs';
import {randomBytes,createHash,createPublicKey,verify,timingSafeEqual} from 'node:crypto';
import {exact,uuid,string,parseJson,fail} from './schema.mjs';

const identities=new WeakSet();
export const isConfiguredIdentity=value=>identities.has(value)&&value.health().ready;
export const DELEGATION_ACTIONS=Object.freeze(['list','get','assignments','sessions','activity','enroll','rotate','intent','test','update','revoke','assign','unassign']);
const token=()=>randomBytes(32).toString('base64url');
const hash=s=>createHash('sha256').update(s).digest('base64url');
const safeEqual=(a,b)=>typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
const cookieName='__Host-fractionate-human',flowCookie='__Host-fractionate-login';
const cookie=(name,value,seconds)=>`${name}=${value}; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=${seconds}`;
function cookies(req){const result=new Map();for(const item of (req.headers.cookie||'').split(';')){if(!item.trim())continue;const i=item.indexOf('='),key=item.slice(0,i).trim(),value=item.slice(i+1).trim();if(i<1||result.has(key))fail('AUTH_REQUIRED',401);result.set(key,value);}return result;}
function fixedHttps(value){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.hash||u.search)fail('INVALID_CONFIG');return u;}
function requestJson(url,{method='GET',body,ca}={}){return new Promise((resolve,reject)=>{const req=https.request(url,{method,ca,timeout:5000,rejectUnauthorized:true,maxHeaderSize:8192,headers:body?{'Content-Type':'application/x-www-form-urlencoded','Content-Length':Buffer.byteLength(body)}:{Accept:'application/json'}},res=>{let size=0;const chunks=[];if(res.statusCode!==200||res.headers['content-encoding']||!/^application\/json(?:;|$)/i.test(res.headers['content-type']||'')){res.resume();reject(Error('OIDC_FAILED'));return;}res.on('data',b=>{size+=b.length;if(size>65536)res.destroy(Error('OIDC_FAILED'));else chunks.push(b);});res.on('error',()=>reject(Error('OIDC_FAILED')));res.on('end',()=>{try{resolve(parseJson(Buffer.concat(chunks)));}catch{reject(Error('OIDC_FAILED'));}});});const deadline=setTimeout(()=>req.destroy(Error('OIDC_FAILED')),5000);req.on('close',()=>clearTimeout(deadline));req.on('timeout',()=>req.destroy());req.on('error',()=>reject(Error('OIDC_FAILED')));req.end(body);});}

/** Public-client OIDC code flow. No dashboard assertion, email match, refresh token,
 * implicit flow, dynamic discovery, arbitrary redirect, or production bypass. */
export function createIdentity({config,clock=Date.now}){
 config=structuredClone(config);
 exact(config,['issuer','authorization_endpoint','token_endpoint','jwks_endpoint','client_id','broker_origin','dashboard_origin','subject_map','required_acr','max_age_seconds','ca_file'],['issuer','authorization_endpoint','token_endpoint','jwks_endpoint','client_id','broker_origin','dashboard_origin','subject_map','required_acr','max_age_seconds']);
 for(const field of ['issuer','authorization_endpoint','token_endpoint','jwks_endpoint','broker_origin','dashboard_origin'])fixedHttps(config[field]);
 for(const field of ['broker_origin','dashboard_origin'])if(new URL(config[field]).origin!==config[field])fail('INVALID_CONFIG');
 if(config.broker_origin===config.dashboard_origin)fail('INVALID_CONFIG');
 string(config.client_id);string(config.required_acr);if(!Number.isSafeInteger(config.max_age_seconds)||config.max_age_seconds<1||config.max_age_seconds>300)fail('INVALID_CONFIG');
 if(!Array.isArray(config.subject_map)||!config.subject_map.length||config.subject_map.length>1000)fail('INVALID_CONFIG');const subjects=new Map();
 for(const row of config.subject_map){exact(row,['issuer','subject','user_id']);if(row.issuer!==config.issuer)fail('INVALID_CONFIG');string(row.subject,255);uuid(row.user_id);if(subjects.has(row.subject))fail('INVALID_CONFIG');subjects.set(row.subject,row.user_id);}
 const ca=config.ca_file?readFileSync(config.ca_file):undefined,redirect=config.broker_origin+'/auth/callback';
 const flows=new Map(),sessions=new Map(),delegations=new Map();let closed=false;
 const prune=()=>{for(const map of [flows,sessions,delegations])for(const[k,v]of map)if(v.expires_at<=clock())map.delete(k);};
 const authenticate=async proof=>{if(closed||typeof proof!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(proof))fail('AUTH_REQUIRED',401);prune();const key=hash(proof),s=sessions.get(key),d=delegations.get(key);if(s)return {user_id:s.user_id,fresh_until:s.expires_at,proof_type:'human',actions:[]};if(d&&sessions.has(d.parent))return {user_id:d.user_id,fresh_until:d.expires_at,proof_type:'delegation',actions:[...d.actions]};fail('AUTH_REQUIRED',401);};
 const sessionProof=req=>{if(!req.socket.encrypted||req.headers.host!==new URL(config.broker_origin).host)fail('AUTH_REQUIRED',401);const p=cookies(req).get(cookieName);if(!p||!sessions.has(hash(p))||sessions.get(hash(p)).expires_at<=clock()||closed)fail('AUTH_REQUIRED',401);return p;};
 const requestPrincipal=req=>{const proof=sessionProof(req);return{proof,csrf_token:sessions.get(hash(proof)).csrf};};
 const createDelegation=async(humanSession,actions)=>{const p=await authenticate(humanSession);if(p.proof_type!=='human'||!Array.isArray(actions)||!actions.length||actions.length>DELEGATION_ACTIONS.length||new Set(actions).size!==actions.length||actions.some(x=>!DELEGATION_ACTIONS.includes(x)))fail('NOT_PERMITTED',403);prune();if(delegations.size>=1000)fail('LIMIT_EXCEEDED',429);const bearer=token(),expires_at=Math.min(p.fresh_until,clock()+300000);delegations.set(hash(bearer),{user_id:p.user_id,parent:hash(humanSession),actions:[...actions],expires_at});return{bearer,expires_at,user_id:p.user_id,actions:[...actions]};};
 async function validateIdToken(jwt,flow){if(typeof jwt!=='string'||jwt.length>16384)throw Error();const parts=jwt.split('.');if(parts.length!==3||parts.some(p=>!p||!/^[A-Za-z0-9_-]+$/.test(p)))throw Error();const head=parseJson(Buffer.from(parts[0],'base64url')),claims=parseJson(Buffer.from(parts[1],'base64url'));exact(head,['alg','kid','typ'],['alg','kid']);if(head.alg!=='RS256'||(head.typ&&head.typ!=='JWT')||typeof head.kid!=='string')throw Error();
   const keys=await requestJson(config.jwks_endpoint,{ca});if(!Array.isArray(keys.keys)||keys.keys.length>32)throw Error();const matches=keys.keys.filter(k=>k.kid===head.kid&&k.kty==='RSA'&&(!k.use||k.use==='sig')&&(!k.alg||k.alg==='RS256')&&(!k.key_ops||(Array.isArray(k.key_ops)&&k.key_ops.includes('verify'))));if(matches.length!==1)throw Error();const key=createPublicKey({key:matches[0],format:'jwk'});if(key.asymmetricKeyDetails?.modulusLength<2048||!verify('RSA-SHA256',Buffer.from(parts[0]+'.'+parts[1]),key,Buffer.from(parts[2],'base64url')))throw Error();
   const now=clock()/1000,aud=claims.aud;if(Array.isArray(aud)&&(!aud.length||aud.length>8||aud.some(x=>typeof x!=='string')||new Set(aud).size!==aud.length))throw Error();if(claims.iss!==config.issuer||!(aud===config.client_id||(Array.isArray(aud)&&aud.includes(config.client_id)))||((Array.isArray(aud)&&aud.length>1)||claims.azp!==undefined)&&claims.azp!==config.client_id)throw Error();
   if(!Number.isFinite(claims.exp)||claims.exp<=now||!Number.isFinite(claims.iat)||claims.iat>now+30||claims.exp<=claims.iat||claims.nbf!==undefined&&(!Number.isFinite(claims.nbf)||claims.nbf>now+30)||!Number.isFinite(claims.auth_time)||claims.auth_time>now+30||claims.auth_time+config.max_age_seconds<=now||claims.acr!==config.required_acr||!safeEqual(claims.nonce,flow.nonce)||typeof claims.sub!=='string'||!subjects.has(claims.sub))throw Error();
   return{user_id:subjects.get(claims.sub),expires_at:Math.min(claims.exp*1000,(claims.auth_time+config.max_age_seconds)*1000)};
 }
 const readBody=async req=>{if(req.headers['content-type']!=='application/json'||req.headers['content-encoding'])fail('INVALID_REQUEST');let size=0;const chunks=[];const t=setTimeout(()=>req.destroy(),5000);try{for await(const b of req){size+=b.length;if(size>4096)fail('INVALID_REQUEST');chunks.push(b);}return parseJson(Buffer.concat(chunks));}finally{clearTimeout(t);}};
 const handle=async(req,res)=>{const u=new URL(req.url,config.broker_origin);if(!u.pathname.startsWith('/auth/'))return false;
   const nonce=token();res.setHeader('Cache-Control','no-store');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Security-Policy',`default-src 'none'; script-src 'nonce-${nonce}'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'`);
   const json=(code,v)=>{res.writeHead(code,{'Content-Type':'application/json'});res.end(JSON.stringify(v));};
   try{if(!req.url.startsWith('/')||req.url.startsWith('//'))fail('INVALID_REQUEST');if(closed||!req.socket.encrypted||req.headers.host!==new URL(config.broker_origin).host)fail('AUTH_REQUIRED',401);const names=req.rawHeaders.filter((_,i)=>i%2===0).map(x=>x.toLowerCase());if(new Set(names).size!==names.length)fail('INVALID_REQUEST');
     if(req.method==='GET'&&u.pathname==='/auth/login'){
       prune();if(flows.size>=1000)fail('LIMIT_EXCEEDED',429);if([...u.searchParams.keys()].some(x=>!['return_to','popup_state'].includes(x))||u.searchParams.getAll('return_to').length>1)fail('INVALID_REQUEST');const popup=u.searchParams.get('popup_state');if(popup&&!/^[A-Za-z0-9_-]{16,128}$/.test(popup))fail('INVALID_REQUEST');const next=u.searchParams.get('return_to')||'/auth/delegations';if(next!=='/auth/delegations'&&!/^\/intake\/[0-9a-f-]{36}$/.test(next))fail('INVALID_REQUEST');
       const state=token(),binding=token(),verifier=token(),oidcNonce=token();flows.set(hash(state),{binding:hash(binding),verifier,nonce:oidcNonce,next:next+(next==='/auth/delegations'?'?state='+(popup||token()):''),expires_at:clock()+300000});const url=new URL(config.authorization_endpoint);for(const[k,v]of Object.entries({client_id:config.client_id,redirect_uri:redirect,response_type:'code',scope:'openid',state,nonce:oidcNonce,code_challenge:hash(verifier),code_challenge_method:'S256',max_age:String(config.max_age_seconds),acr_values:config.required_acr}))url.searchParams.set(k,v);res.writeHead(302,{'Set-Cookie':cookie(flowCookie,binding,300),Location:url.href});res.end();return true;
     }
     if(req.method==='GET'&&u.pathname==='/auth/callback'){
       if([...u.searchParams.keys()].some(x=>!['state','code','iss','session_state'].includes(x))||['state','code','iss','session_state'].some(x=>u.searchParams.getAll(x).length>1))fail('AUTH_REQUIRED',401);const state=u.searchParams.get('state'),code=u.searchParams.get('code');if(!state||!code||code.length>2048)fail('AUTH_REQUIRED',401);const flow=flows.get(hash(state));flows.delete(hash(state));if(!flow||flow.expires_at<=clock()||!safeEqual(flow.binding,hash(cookies(req).get(flowCookie)||''))||(u.searchParams.has('iss')&&u.searchParams.get('iss')!==config.issuer))fail('AUTH_REQUIRED',401);
       const response=await requestJson(config.token_endpoint,{method:'POST',ca,body:new URLSearchParams({grant_type:'authorization_code',code,client_id:config.client_id,redirect_uri:redirect,code_verifier:flow.verifier}).toString()});const p=await validateIdToken(response.id_token,flow);prune();if(sessions.size>=1000)fail('LIMIT_EXCEEDED',429);const proof=token();const old=cookies(req).get(cookieName);if(old)sessions.delete(hash(old));sessions.set(hash(proof),{...p,csrf:token()});res.writeHead(303,{'Set-Cookie':[cookie(cookieName,proof,Math.max(1,Math.floor((p.expires_at-clock())/1000))),cookie(flowCookie,'',0)],Location:flow.next});res.end();return true;
     }
     if(req.method==='GET'&&u.pathname==='/auth/delegations'){
       const popup=u.searchParams.get('state');if(!popup||!/^[A-Za-z0-9_-]{16,128}$/.test(popup)||u.searchParams.getAll('state').length!==1||[...u.searchParams.keys()].some(x=>!['state','dashboard_origin'].includes(x))||(u.searchParams.has('dashboard_origin')&&u.searchParams.get('dashboard_origin')!==config.dashboard_origin))fail('INVALID_REQUEST');
       try{sessionProof(req);}catch{res.writeHead(303,{Location:'/auth/login?popup_state='+popup});res.end();return true;}
     }
     const {proof,csrf_token}=requestPrincipal(req),p=await authenticate(proof);
     if(req.method==='GET'&&u.pathname==='/auth/session'){json(200,{user_id:p.user_id,fresh_until:p.fresh_until,csrf_token});return true;}
     if(req.method==='POST'){
       if(req.headers.origin!==config.broker_origin||!safeEqual(req.headers['x-csrf-token'],csrf_token))fail('NOT_PERMITTED',403);
       if(u.pathname==='/auth/logout'){sessions.delete(hash(proof));for(const[k,d]of delegations)if(d.parent===hash(proof))delegations.delete(k);res.setHeader('Set-Cookie',cookie(cookieName,'',0));json(200,{signed_out:true});return true;}
       if(u.pathname==='/auth/delegations'){const b=await readBody(req);exact(b,['actions']);json(200,await createDelegation(proof,b.actions));return true;}
     }
     if(req.method==='GET'&&u.pathname==='/auth/delegations'){
       const cfg=JSON.stringify({csrf:csrf_token,origin:config.dashboard_origin,state:u.searchParams.get('state'),actions:DELEGATION_ACTIONS}).replace(/</g,'\\u003c');res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(`<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Authorize dashboard connection controls</title><h1>Authorize dashboard connection controls</h1><p>Allow the dashboard to view and manage connection metadata within your independently enforced permissions for up to five minutes. This does not permit secret submission, operation approval, workload session creation, or authority administration.</p><p>Actions: ${DELEGATION_ACTIONS.join(', ')}</p><button id="allow">Authorize dashboard</button><p role="status" id="status"></p><script nonce="${nonce}">const c=${cfg};document.querySelector('#allow').onclick=async()=>{document.querySelector('#allow').disabled=true;try{const r=await fetch('/auth/delegations',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':c.csrf},body:JSON.stringify({actions:c.actions})});if(!r.ok)throw Error();const d=await r.json();if(!window.opener)throw Error();window.opener.postMessage({type:'fractionate.broker.delegation',state:c.state,delegation:d.bearer,expires_at:d.expires_at,user_id:d.user_id},c.origin);document.querySelector('#status').textContent='Authorization sent. You can close this window.';}catch{document.querySelector('#status').textContent='Authorization unavailable. Sign in again.';}};</script></html>`);return true;
     }
     json(404,{error:{code:'NOT_FOUND'}});
   }catch{json(401,{error:{code:'AUTH_REQUIRED',retryable:false}});}return true;
 };
 const instance={authenticate,createDelegation,handle,requestPrincipal,sessionProof,health:()=>({ready:!closed,configured:true}),close:()=>{closed=true;flows.clear();sessions.clear();delegations.clear();}};identities.add(instance);return instance;
}
