import { randomBytes } from 'node:crypto';
import { encryptSecret,decryptSecret,isEncrypted } from '../secrets.js';
import { createJob,getJob,jobView } from './store.js';
import { verifiedProvider } from './pomerium-store.js';
import { issuerFor } from './keycloak-logic.js';
import { configSchema,OPENBAO_APP,OPENBAO_IMAGE,RECOVERY_ROOT,digest,fail,namesFor,callbackFor,policyFor,humanRoleFor,machineRoleFor,roleFor } from './openbao-logic.js';
export const OPENBAO_SCHEMA=`CREATE TABLE IF NOT EXISTS setup_openbao(id INTEGER PRIMARY KEY CHECK(id=1),revision INTEGER NOT NULL,config_json TEXT NOT NULL,credential_ref TEXT NOT NULL,last_job_id TEXT,edge_job_id TEXT,resources_json TEXT,verified_json TEXT,init_attempted INTEGER NOT NULL DEFAULT 0,handoff_digest TEXT,handoff_ack INTEGER NOT NULL DEFAULT 0,bootstrap_complete INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS setup_openbao_credentials(id TEXT PRIMARY KEY,value TEXT NOT NULL);`;
export function readOpenBao(db){if(!db.prepare("SELECT name FROM sqlite_master WHERE name='setup_openbao'").get())return null;const r=db.prepare('SELECT * FROM setup_openbao WHERE id=1').get();return r?{...r,config:JSON.parse(r.config_json),resources:r.resources_json?JSON.parse(r.resources_json):null}:null;}
export function secrets(db,r){try{const v=db.prepare('SELECT value FROM setup_openbao_credentials WHERE id=?').get(r.credential_ref)?.value;if(!isEncrypted(v))throw Error();return JSON.parse(decryptSecret(v));}catch{throw fail('Protected OpenBao credentials cannot be opened. Restore matching configuration and encryption key; do not regenerate credentials.');}}
export function putSecrets(db,r,v){db.prepare('UPDATE setup_openbao_credentials SET value=? WHERE id=?').run(encryptSecret(JSON.stringify(v)),r.credential_ref);}
function tx(db,fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
export function idle(db,r){if(r?.last_job_id&&['queued','running'].includes(getJob(db,r.last_job_id)?.status))throw fail('An OpenBao operation is pending. Wait for it before submitting another operation.');}
const plan=db=>{const r=db.prepare('SELECT * FROM setup_platform_plan WHERE id=1').get();return r?{revision:r.revision,...JSON.parse(r.choices_json).openbao}:null;};
export function currentPlan(db,r){const p=plan(db);if(!p||p.mode==='skip'||p.mode!==r.config.mode||p.url!==r.config.origin)throw fail('OpenBao is skipped or its platform choices changed. Restore and review the saved targets.');return p;}
export function state(db){const r=readOpenBao(db);return r?{revision:r.revision,config:r.config,credentialRef:r.credential_ref,resources:r.resources,initializationAttempted:!!r.init_attempted,handoffAvailable:!!r.handoff_digest,handoffAcknowledged:!!r.handoff_ack,bootstrapComplete:!!r.bootstrap_complete,job:r.last_job_id?jobView(getJob(db,r.last_job_id)):null,lastVerification:r.verified_json?JSON.parse(r.verified_json):null}:null;}
export function save(db,raw){const p=configSchema.parse(raw);return tx(db,()=>{
  const old=readOpenBao(db);idle(db,old);if((old?.revision||0)!==p.expectedRevision)throw fail('OpenBao settings changed. Reopen them.');
  const choice=plan(db);if(!choice||choice.revision!==p.expectedPlanRevision||choice.mode==='skip')throw fail('Save an active OpenBao platform plan first.');
  const u=new URL(choice.url);if(u.protocol!=='https:'||u.port||!/^([a-z0-9-]+\.)+[a-z0-9-]+$/.test(u.hostname))throw fail('Use a dedicated OpenBao HTTPS DNS origin on port 443.');
  let k;try{k=verifiedProvider(db,p.connectionId);}catch{throw fail('Select a verified Keycloak provider.');}
  const g3=JSON.parse(db.prepare('SELECT config_json FROM sso_config WHERE id=1').get()?.config_json||'{}');
  const g4=JSON.parse(db.prepare('SELECT config_json FROM setup_pomerium WHERE id=1').get()?.config_json||'{}');
  if([g3.clientId,g3.readerClientId,g4.clientId].includes(p.clientId))throw fail('Use a separate OpenBao Keycloak client. Existing service clients cannot be reused.');
  if([k.origin,g3.publicOrigin,g3.recoveryOrigin,g4.origin].includes(u.origin)||db.prepare("SELECT value FROM app_settings WHERE key='admin_domain'").get()?.value===u.hostname)throw fail('The OpenBao hostname conflicts with an existing identity or recovery service.');
  if(choice.mode==='install'&&(!p.initialize||p.pgpKeys?.length!==3||!p.rootPgpKey||new Set(p.pgpKeys).size!==3))throw fail('Review initialization with three distinct operator PGP public keys (2 of 3 required) and a root-token recipient public key.');
  if(choice.mode==='connect'&&(p.initialize||p.pgpKeys||p.rootPgpKey))throw fail('External initialization and seal changes are refused.');
  const config={mode:choice.mode,origin:u.origin,connectionId:k.id,issuer:issuerFor({url:k.origin,realm:k.realm}),clientId:p.clientId,group:p.group,database:p.database,allowedIps:[...new Set(p.allowedIps)].sort(),initialize:p.initialize,...(choice.mode==='install'?{pgpKeys:p.pgpKeys,rootPgpKey:p.rootPgpKey}:{})};
  if(old){if(digest(config)!==digest(old.config)||p.clientSecret&&p.clientSecret!==secrets(db,old).client)throw fail('G6 retry preserves targets, recipient keys and credentials. Restore the saved choices; rotation/migration is outside this slice.');return state(db);}
  if(!p.clientSecret)throw fail('Supply the dedicated Keycloak client credential once.');
  const ref='openbao-'+randomBytes(12).toString('hex');
  db.prepare('INSERT INTO setup_openbao_credentials VALUES (?,?)').run(ref,encryptSecret(JSON.stringify({client:p.clientSecret,machine:randomBytes(32).toString('base64url')})));
  db.prepare('INSERT INTO setup_openbao(id,revision,config_json,credential_ref,created_at) VALUES(1,1,?,?,?)').run(JSON.stringify(config),ref,new Date().toISOString());return state(db);
});}
export function review(db){const r=readOpenBao(db);if(!r)return null;const n=namesFor(r);return {revision:r.revision,reviewToken:digest([r.revision,r.config,r.credential_ref]),image:OPENBAO_IMAGE,names:n,callback:callbackFor(r),humanRole:humanRoleFor(r),machineRole:machineRoleFor(r),policy:policyFor(r),databaseRole:roleFor(r),recoveryPath:`${RECOVERY_ROOT}/${r.credential_ref}.json`,changes:['Managed apply creates only the named private Docker service, persistent Raft/log volumes and restricted Caddy route. Connect first reads status; no external runtime or seal changes.', 'Managed initialization is explicitly authorized once, only while confirmed uninitialized. OpenBao encrypts the 2-of-3 shares and initial root token to the reviewed PGP recipients.', 'After handoff acknowledgement and manual unseal, bootstrap creates only the named owned OIDC/AppRole/database mounts, policies and reader role. It revokes the submitted bootstrap token after success.', 'Only the explicitly selected disposable PostgreSQL database is tested. No other database, SSH or PKI engine is configured.']};}
export function assertReview(db,input){const r=readOpenBao(db),v=review(db);if(!r||r.revision!==input.revision||v.reviewToken!==input.reviewToken||input.reviewed!==true)throw fail('Review the current saved OpenBao configuration.');currentPlan(db,r);return r;}
export function apply(db,input,by){return tx(db,()=>{const r=assertReview(db,input);const old=r.last_job_id?getJob(db,r.last_job_id):null;if(old&&['queued','running'].includes(old.status))return {job:jobView(old),created:false};const j=createJob(db,{app:OPENBAO_APP,kind:'openbao_apply',plan:{params:{revision:r.revision}},configRefs:{credentials:r.credential_ref},requestedBy:by,via:'ui',retryOf:r.last_job_id,reason:'Reviewed OpenBao operation queued. Existing data, shares and identities are preserved.'});db.prepare('UPDATE setup_openbao SET last_job_id=?,edge_job_id=NULL,verified_json=NULL WHERE id=1').run(j.id);return {job:jobView(j),created:true};});}
export function acknowledge(db,input){return tx(db,()=>{const r=assertReview(db,input);idle(db,r);if(!r.handoff_digest||digest(input.receipt)!==r.handoff_digest)throw fail('The receipt does not match the protected recovery handoff. Retrieve the recorded package; do not initialize again.');db.prepare('UPDATE setup_openbao SET handoff_ack=1 WHERE id=1').run();return state(db);});}
