#!/usr/bin/env bash
# install-storage.sh — the one-time host preparation for ProxyPilot's ZFS
# storage management (Storage page, storage MCP tools). Run once as root on
# the host after install.sh / update.sh:
#
#   sudo bash scripts/install-storage.sh
#
# What it does (each step idempotent):
#   1. apt-get install zfsutils-linux smartmontools sanoid  (+ lvm2, mdadm are
#      NOT installed: lsblk/libblkid detects their signatures without them)
#   2. loads the zfs kernel module and enables zfs-import/zfs-mount services
#   3. installs the ProxyPilot units: proxypilot-zfs-scrub@.{service,timer},
#      proxypilot-syncoid@.{service,timer}
#   4. installs the helpers: /usr/local/sbin/proxypilot-storage-replicate,
#      /usr/local/sbin/proxypilot-storage-restore-guest
#   5. seeds /etc/sanoid/sanoid.conf (empty policy: no datasets yet) and
#      enables sanoid.timer; creates /etc/proxypilot/storage and
#      /var/lib/proxypilot/storage
#   6. restarts proxypilot-agent so the SupplementaryGroups=disk change in
#      its unit takes effect
#
# Nothing here touches a disk: pools are created only through the Storage
# page / create_zpool after the operator has seen and confirmed the plan.
set -euo pipefail
[[ $EUID -eq 0 ]] || { echo "run as root" >&2; exit 1; }
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export DEBIAN_FRONTEND=noninteractive

echo "[1/6] packages"
apt-get update -qq
apt-get install -y zfsutils-linux smartmontools sanoid pv mbuffer lzop
# sanoid's Debian package ships sanoid.timer (15 min) and the syncoid binary.

echo "[2/6] zfs module + import services"
modprobe zfs || { echo "zfs module did not load — on a distribution kernel this needs the zfs-dkms build to finish; reboot and re-run" >&2; exit 2; }
systemctl enable --now zfs-import-cache.service zfs-import.target zfs-mount.service zfs.target 2>/dev/null || true

echo "[3/6] units"
for u in proxypilot-zfs-scrub@.service proxypilot-zfs-scrub@.timer proxypilot-syncoid@.service proxypilot-syncoid@.timer; do
  install -m 0644 "$SCRIPT_DIR/deploy/$u" "/etc/systemd/system/$u"
done
# the agent unit gained SupplementaryGroups=disk (lets lsblk / zpool label scans read devices)
if [[ -f "$SCRIPT_DIR/deploy/proxypilot-agent.service" ]] && ! cmp -s "$SCRIPT_DIR/deploy/proxypilot-agent.service" /etc/systemd/system/proxypilot-agent.service; then
  install -m 0644 "$SCRIPT_DIR/deploy/proxypilot-agent.service" /etc/systemd/system/proxypilot-agent.service
fi
systemctl daemon-reload

echo "[4/6] helpers"
install -m 0755 "$SCRIPT_DIR/scripts/storage-replicate.sh" /usr/local/sbin/proxypilot-storage-replicate
install -m 0755 "$SCRIPT_DIR/scripts/storage-restore-guest.sh" /usr/local/sbin/proxypilot-storage-restore-guest

echo "[5/6] sanoid + directories"
mkdir -p /etc/sanoid /etc/proxypilot/storage /var/lib/proxypilot/storage/replication /var/lib/proxypilot/storage/restore /var/lib/proxypilot/storage/destroyed
chmod 0750 /etc/proxypilot/storage
if [[ ! -f /etc/sanoid/sanoid.conf ]]; then
  cat > /etc/sanoid/sanoid.conf <<'CONF'
# Generated by ProxyPilot (Storage → Backup policy). Empty until a managed pool exists.
CONF
fi
systemctl enable --now sanoid.timer 2>/dev/null || echo "sanoid.timer not available — check the sanoid package" >&2

echo "[6/6] agent restart"
systemctl try-restart proxypilot-agent.service 2>/dev/null || true

echo
echo "Done. Next, in the dashboard: Storage → Devices → Create pool (or set an existing pool as managed),"
echo "then Pools → Set as Incus storage pool, then Backup & replication."
echo "For replication over SSH create a key on this host (ssh-keygen -t ed25519 -f /root/.ssh/pp_replication -N '')"
echo "and authorize its public key on the target for a user allowed to run 'zfs receive' (sudo or zfs allow)."
