export {
  enable,
  disable,
  detectDefaultIface,
  generateServerKeypair,
  readVpnConfig,
  renderWg0Conf,
  writeWg0Conf,
  WG_INTERFACE,
  WG_CONFIG_FILE,
  WG_SERVER_PRIVATE,
  WG_DEFAULT_PORT,
  WG_DEFAULT_CIDR,
  WG_DEFAULT_DNS,
  WG_SERVER_IP,
} from './server.js';
