import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { getDb } from '../../db/index.js';
import { audit } from '../../db/audit.js';
import {
  enable as fwEnable,
  disable as fwDisable,
  readState as fwReadState,
  writeState as fwWriteState,
  reconcile as fwReconcile,
} from '../firewall/index.js';

export const WG_CONFIG_DIR = '/etc/wireguard';
export const WG_CONFIG_FILE = path.join(WG_CONFIG_DIR, 'wg0.conf');
export const WG_SERVER_PRIVATE = path.join(WG_CONFIG_DIR, 'server_private.key');
export const WG_INTERFACE = 'wg0';
export const WG_DEFAULT_PORT = 51820;
export const WG_DEFAULT_CIDR = '10.100.0.0/24';
export const WG_DEFAULT_DNS = '10.100.0.1';
export const WG_SERVER_IP = '10.100.0.1/24';

function run(cmd, args, opts = {}) {
  return spawnSync(cmd, args, { encoding: 'utf-8', ...opts });
}

/**
 * Detect the host's default-route interface. We prefer `ip -j route` JSON
 * because it is unambiguous; if the JSON form is unavailable on this
 * host we fall back to parsing the human-readable form. Either way we
 * validate the result against the same regex the firewall renderer
 * uses so a junk value can never reach the nft ruleset.
 */
export function detectDefaultIface() {
  const j = run('ip', ['-j', 'route', 'show', 'default']);
  if (j.status === 0 && j.stdout.trim()) {
    try {
      const arr = JSON.parse(j.stdout);
      const dev = arr?.[0]?.dev;
      if (dev && /^[A-Za-z0-9_.-]{1,15}$/.test(dev)) return dev;
    } catch { /* fall through */ }
  }
  const t = run('ip', ['route', 'show', 'default']);
  if (t.status === 0) {
    const m = t.stdout.match(/\bdev\s+([A-Za-z0-9_.-]{1,15})\b/);
    if (m) return m[1];
  }
  throw new Error('could not detect default-route interface (`ip route show default` returned nothing)');
}

export function generateServerKeypair() {
  const priv = run('wg', ['genkey']);
  if (priv.status !== 0) {
    throw new Error(`wg genkey failed: ${priv.stderr.trim() || priv.error?.message}`);
  }
  const privateKey = priv.stdout.trim();
  const pub = run('wg', ['pubkey'], { input: privateKey });
  if (pub.status !== 0) {
    throw new Error(`wg pubkey failed: ${pub.stderr.trim() || pub.error?.message}`);
  }
  return { private: privateKey, public: pub.stdout.trim() };
}

export function readVpnConfig() {
  const db = getDb();
  return db.prepare('SELECT * FROM vpn_config WHERE id = 1').get() ?? null;
}

function writeVpnConfig({ serverPublicKey, endpoint, listenPort, cidr, defaultIface, dns }) {
  const db = getDb();
  db.prepare(`
    INSERT INTO vpn_config (id, server_public_key, endpoint, listen_port, cidr, default_iface, dns)
    VALUES (1, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(id) DO UPDATE SET
      server_public_key = excluded.server_public_key,
      endpoint          = excluded.endpoint,
      listen_port       = excluded.listen_port,
      cidr              = excluded.cidr,
      default_iface     = excluded.default_iface,
      dns               = excluded.dns
  `).run(serverPublicKey, endpoint, listenPort, cidr, defaultIface, dns);
}

function readEnabledPeers() {
  const db = getDb();
  return db.prepare(`
    SELECT id, name, public_key, allowed_ip, preshared_key_hash
    FROM vpn_peers
    WHERE status = 'enabled'
    ORDER BY id
  `).all();
}

/**
 * Render `/etc/wireguard/wg0.conf`. Deterministic: identical state →
 * identical bytes. No PostUp/PostDown — NAT is emitted by the firewall
 * manager into proxypilot.nat_postrouting.
 */
export function renderWg0Conf({ privateKey, listenPort, serverIp, peers }) {
  const lines = [
    '# Generated by ProxyPilot VPN manager. Do not edit by hand.',
    '# NAT/forwarding live in nft table inet proxypilot, chain nat_postrouting.',
    '[Interface]',
    `Address = ${serverIp}`,
    `ListenPort = ${listenPort}`,
    `PrivateKey = ${privateKey}`,
  ];
  for (const p of peers) {
    lines.push('', `# ${p.name}`, '[Peer]', `PublicKey = ${p.public_key}`, `AllowedIPs = ${p.allowed_ip}/32`);
  }
  return lines.join('\n') + '\n';
}

function atomicWrite(filePath, content, mode = 0o600) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  const tmp = `${filePath}.tmp.${process.pid}.${Date.now()}`;
  fs.writeFileSync(tmp, content, { mode });
  fs.renameSync(tmp, filePath);
}

export function writeWg0Conf({ privateKey, listenPort, serverIp, peers }) {
  const body = renderWg0Conf({ privateKey, listenPort, serverIp, peers });
  atomicWrite(WG_CONFIG_FILE, body, 0o600);
}

function setNatIface(iface) {
  const state = fwReadState();
  state.nat = { ...(state.nat ?? {}), vpn_masquerade_iface: iface };
  fwWriteState(state);
}

function clearNatIface() {
  const state = fwReadState();
  if (state.nat?.vpn_masquerade_iface) {
    delete state.nat.vpn_masquerade_iface;
    if (Object.keys(state.nat).length === 0) delete state.nat;
    fwWriteState(state);
  }
}

/**
 * Bring up the VPN. Reuses the existing private key if `vpn_config`
 * + the on-disk private key are both present, so re-running enable is
 * idempotent and never silently rotates the server key.
 *
 * Order matters here: write config + start the interface BEFORE
 * touching the firewall. If wg-quick fails we abort without ever
 * having advertised an open port; the operator's previous state is
 * untouched.
 */
export async function enable({ endpoint, listenPort = WG_DEFAULT_PORT, dns = WG_DEFAULT_DNS, actor } = {}) {
  if (!endpoint) throw new Error('endpoint is required (host:port the peer dials)');
  const existing = readVpnConfig();
  const iface = detectDefaultIface();

  let privateKey;
  let publicKey;
  if (existing && fs.existsSync(WG_SERVER_PRIVATE)) {
    privateKey = fs.readFileSync(WG_SERVER_PRIVATE, 'utf-8').trim();
    publicKey = existing.server_public_key;
  } else {
    const kp = generateServerKeypair();
    privateKey = kp.private;
    publicKey = kp.public;
    if (!fs.existsSync(WG_CONFIG_DIR)) fs.mkdirSync(WG_CONFIG_DIR, { recursive: true, mode: 0o700 });
    atomicWrite(WG_SERVER_PRIVATE, privateKey + '\n', 0o600);
  }

  writeVpnConfig({
    serverPublicKey: publicKey,
    endpoint,
    listenPort,
    cidr: WG_DEFAULT_CIDR,
    defaultIface: iface,
    dns,
  });

  const peers = readEnabledPeers();
  writeWg0Conf({ privateKey, listenPort, serverIp: WG_SERVER_IP, peers });

  const up = run('systemctl', ['enable', '--now', `wg-quick@${WG_INTERFACE}`]);
  if (up.status !== 0) {
    throw new Error(`failed to start wg-quick@${WG_INTERFACE}: ${up.stderr.trim() || up.stdout.trim()}`);
  }

  fwEnable({ id: 'base-wireguard', actor });
  setNatIface(iface);
  const r = await fwReconcile({ actor });
  if (!r.ok) {
    throw new Error(`firewall reconcile failed: ${JSON.stringify(r.rejection)}`);
  }

  audit({
    subsystem: 'vpn',
    action: 'enable',
    resource: WG_INTERFACE,
    actor,
    after: { endpoint, listen_port: listenPort, default_iface: iface, public_key: publicKey },
  });

  return { endpoint, listenPort, defaultIface: iface, publicKey };
}

/**
 * Bring the VPN down without losing state. Peer rows, IP allocations,
 * the server keypair, and the SQLite vpn_config row are all preserved
 * — only the live interface, the base allowlist toggle, and the NAT
 * field are reverted. Reverse of `enable` so a follow-up `enable`
 * comes back up identically.
 */
export async function disable({ actor } = {}) {
  const down = run('systemctl', ['disable', '--now', `wg-quick@${WG_INTERFACE}`]);
  // Tolerate "Unit is not loaded" / already-down: surface only hard failures.
  if (down.status !== 0 && !/not loaded|not found/i.test(down.stderr || '')) {
    throw new Error(`failed to stop wg-quick@${WG_INTERFACE}: ${down.stderr.trim() || down.stdout.trim()}`);
  }

  try { fwDisable({ id: 'base-wireguard', actor }); } catch (e) {
    if (e.code !== 'NOT_FOUND') throw e;
  }
  clearNatIface();
  const r = await fwReconcile({ actor });
  if (!r.ok) {
    throw new Error(`firewall reconcile failed: ${JSON.stringify(r.rejection)}`);
  }

  audit({ subsystem: 'vpn', action: 'disable', resource: WG_INTERFACE, actor });
  return { ok: true };
}
