import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
const field=(id,label,props={})=><div className="space-y-2 min-w-0"><Label htmlFor={'bao-'+id}>{label}</Label><Input id={'bao-'+id} name={id} required autoComplete="off" {...props}/></div>;
const buttonClass='min-h-11 w-full sm:w-auto whitespace-normal';
export default function OpenBaoSetup({revision,dirty,choice,connections=[]}){
  const [data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reviewed,setReviewed]=useState(false);
  const state=data?.state,review=data?.review,pending=['queued','running'].includes(state?.job?.status),skipped=choice.mode==='skip';
  const matches=!state||state.config.mode===choice.mode&&state.config.origin===choice.url;
  const allowed=revision>0&&!dirty&&!skipped&&matches&&!busy&&!pending;
  useEffect(()=>{let active=true;const poll=async()=>{try{const v=await api.getOpenBaoSetup();if(active)setData(v);}catch{if(active){setData(null);setError('OpenBao status is unavailable. Reopen before applying.');}}};poll();const t=setInterval(poll,5000);return()=>{active=false;clearInterval(t);};},[]);
  useEffect(()=>setReviewed(false),[revision,dirty,choice.mode,choice.url,review?.reviewToken]);
  const approval=()=>({revision:state.revision,reviewToken:review.reviewToken,reviewed:true});
  async function run(fn){setBusy(true);setError('');setMessage('');setReviewed(false);try{await fn();setData(await api.getOpenBaoSetup());}catch(e){setError(e.message);}finally{setBusy(false);}}
  function save(e){e.preventDefault();const form=e.currentTarget,f=new FormData(form),input={expectedPlanRevision:revision,expectedRevision:0,connectionId:f.get('connectionId'),clientId:f.get('clientId'),clientSecret:f.get('clientSecret'),group:f.get('group'),allowedIps:String(f.get('allowedIps')).split(/[\s,]+/).filter(Boolean),database:{host:f.get('dbHost'),port:Number(f.get('dbPort')),name:f.get('dbName'),username:f.get('dbUser'),disposable:true},initialize:choice.mode==='install',reviewed:true,...(choice.mode==='install'?{pgpKeys:[f.get('pgp1'),f.get('pgp2'),f.get('pgp3')].map(x=>String(x).trim()),rootPgpKey:String(f.get('rootPgp')).trim()}:{})};form.elements.clientSecret.value='';run(async()=>{await api.saveOpenBaoSetup(input);setMessage('OpenBao settings saved. Review the named resources below, then explicitly apply.');});}
  function transient(e,action){e.preventDefault();const f=new FormData(e.currentTarget),input={...approval(),...(action==='handoff'?{receipt:f.get('receipt')}:action==='unseal'?{share:f.get('share')}:{bootstrapToken:f.get('bootstrapToken'),databasePassword:f.get('databasePassword'),revokeBootstrap:true})};e.currentTarget.reset();run(async()=>{const result=await api.openBaoOperator(action,input);setMessage(result.result?.label||(action==='handoff'?'Recovery handoff acknowledged. Keep its material separately.':'Operator action completed.'));});}
  return <Card id="openbao-setup" className="min-w-0"><CardHeader><CardTitle>Set up OpenBao</CardTitle><CardDescription>Guide a private secrets service through recovery handoff, Keycloak access and one disposable PostgreSQL credential test.</CardDescription></CardHeader><CardContent className="space-y-5 min-w-0">
    {skipped&&<p className="text-sm">OpenBao is skipped. Nothing is installed or removed. Saved resources are preserved.</p>}
    {(dirty||!revision)&&<p className="text-sm">Save the platform plan before configuring OpenBao.</p>}
    {!matches&&<p role="alert">Platform choices differ from the saved OpenBao targets. Restore the saved choices before applying.</p>}
    {error&&<p role="alert" className="text-destructive break-words">{error}</p>}{message&&<p role="status" className="border rounded-lg p-3 break-words">{message}</p>}
    {data&&<div className="rounded-lg bg-muted p-4 space-y-2 text-sm"><p className="font-medium">Service: {data.health.state.replaceAll('_',' ')}</p><p>{data.verification.label}</p>{data.health.state==='sealed'&&<p>Manual unseal is required after each restart. Submit {data.health.threshold||'the required'} shares separately. This guide does not configure automatic unseal.</p>}</div>}
    {!state&&allowed&&<form onSubmit={save} className="space-y-4"><h3 className="font-medium">1. Review service and disposable test targets</h3><p className="text-sm break-all">{choice.mode==='install'?'Install OpenBao 2.6.2 with persistent single-node Raft storage':'Connect to an existing OpenBao 2.6.2 instance'} · {choice.url}</p>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="space-y-2"><Label htmlFor="bao-connectionId">Verified Keycloak provider</Label><select id="bao-connectionId" name="connectionId" required className="border bg-background rounded-md min-h-11 p-2 w-full" defaultValue=""><option value="" disabled>Select provider</option>{connections.filter(c=>c.verifiedAt).map(c=><option key={c.id} value={c.id}>{c.origin} · {c.realm}</option>)}</select></div>{field('clientId','Dedicated Keycloak client ID',{defaultValue:'proxypilot-openbao'})}{field('clientSecret','Dedicated client secret',{type:'password'})}{field('group','Allowed Keycloak group (full path)',{defaultValue:'/proxypilot-openbao'})}{field('allowedIps','IPv4 addresses allowed through Caddy',{placeholder:'10.20.30.40, 192.0.2.10'})}</div>
      <div className="rounded-lg border p-4 space-y-3 text-sm"><p className="font-medium">PostgreSQL · explicitly selected disposable database</p><p>Prepare an empty test database named pp_g6_… with public.g6_probe(marker text), a dedicated non-superuser role with CREATEROLE, and PUBLIC CREATE permissions revoked. Its TLS certificate must cover the private IP. This guide configures only that database connection and a limited reader role in OpenBao.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{field('dbHost','Private database IPv4',{placeholder:'10.20.30.50'})}{field('dbPort','Database port',{type:'number',min:1024,max:65535,defaultValue:5432})}{field('dbName','Disposable database name',{defaultValue:'pp_g6_test'})}{field('dbUser','Dedicated database administrator',{defaultValue:'bao_g6_admin'})}</div><label className="flex gap-2 items-start min-h-11"><input type="checkbox" required className="mt-1"/><span>I selected a disposable test database and authorize only its limited credential test.</span></label></div>
      {choice.mode==='install'&&<fieldset className="border rounded-lg p-4 space-y-3 min-w-0"><legend className="px-1 font-medium">Protected initialization handoff</legend><p className="text-sm">Use three distinct custodians’ PGP public keys. OpenBao encrypts three shares; two are needed to unseal. Paste base64 of the binary public keys, without armor. Keep the private keys outside ProxyPilot.</p>{['pgp1','pgp2','pgp3','rootPgp'].map((k,i)=><div key={k} className="space-y-2"><Label htmlFor={'bao-'+k}>{i<3?`Custodian ${i+1} public key`:'Initial root-token recipient public key'}</Label><textarea id={'bao-'+k} name={k} required autoComplete="off" spellCheck={false} rows={2} className="w-full min-h-20 rounded-md border bg-background p-2 break-all"/></div>)}<label className="flex gap-2 items-start min-h-11"><input type="checkbox" required className="mt-1"/><span>I authorize initialization on explicit apply only if this managed instance is confirmed uninitialized, and understand the separate recovery handoff.</span></label></fieldset>}
      <Button className={buttonClass} type="submit" disabled={busy}>Save reviewed settings</Button><p className="text-xs text-muted-foreground">Saving is inert. Installation, initialization and access changes require separate explicit actions.</p></form>}
    {state&&<><div className="space-y-2 text-sm"><p className="font-medium break-all">Saved target: {state.config.origin}</p><p>Job: {state.job?.status||'not applied'}{state.job?.phase?` · ${state.job.phase}`:''}</p>{state.job?.reason&&<p className="break-words">{state.job.reason}</p>}<p>Recovery handoff: {state.config.mode==='connect'?'Held by the external instance owner':state.handoffAcknowledged?'Acknowledged':state.handoffAvailable?'Ready for operator acknowledgement':'Awaiting managed initialization'}</p></div>
      {review&&<details className="border rounded-lg p-4 min-w-0"><summary className="min-h-11 cursor-pointer font-medium">Review resources, policies and recovery</summary><div className="space-y-3 text-sm break-words">{review.changes.map(x=><p key={x}>{x}</p>)}<p className="font-medium">Dedicated Keycloak client handoff</p><p>Enable confidential authorization-code flow. Disable implicit flow, direct grants and service accounts. Set only this callback and the OpenBao origin as the web origin. Add a full-path groups mapper to the ID token. The existing read-only Keycloak observer verifies this client; it changes no realm settings.</p><p className="break-all">Callback: {review.callback}</p><p className="break-all">Allowed group: {state.config.group}. Unmapped users receive no token through this role.</p><pre className="whitespace-pre-wrap break-all rounded bg-muted p-3 text-xs">{JSON.stringify({resources:review.names,humanRole:review.humanRole,machineRole:review.machineRole,policy:review.policy,databaseRole:review.databaseRole},null,2)}</pre>
        {state.config.mode==='install'&&<><p className="break-all">Protected host handoff: {review.recoveryPath}</p><p>As the host operator, retrieve the file through your protected administrative channel. Base64-decode and PGP-decrypt each recipient’s encrypted value offline. Distribute shares to their separate custodians, retain the package separately, and enter its receipt below. A lost handoff after initialization requires recovery; never delete Raft data or initialize again.</p></>}
        <p>Back up a compatible OpenBao Raft snapshot and its server configuration using the service’s existing tools, plus ProxyPilot’s configuration database and matching encryption key. Keep the recovery package and unseal material separately. After restart, restore connectivity, manually unseal, then apply to repeat verification. This guide creates no backup or restore framework.</p></div></details>}
      <label className="flex gap-2 items-start min-h-11 text-sm"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)} disabled={!allowed} className="mt-1"/><span>I reviewed the named resources and current configuration.</span></label><Button className={buttonClass} disabled={!allowed||!reviewed||!review} onClick={()=>run(async()=>{await api.applyOpenBaoSetup(approval());setMessage('OpenBao operation queued. Progress survives closing this page.');})}>{pending?'Operation pending':'Apply / retry verification'}</Button>
      {state.config.mode==='install'&&state.handoffAvailable&&!state.handoffAcknowledged&&<form onSubmit={e=>transient(e,'handoff')} className="space-y-3"><h3 className="font-medium">2. Acknowledge protected recovery handoff</h3>{field('receipt','Receipt from the protected handoff file',{type:'password'})}<label className="flex gap-2 min-h-11 items-start text-sm"><input type="checkbox" required className="mt-1"/><span>I recovered the encrypted package, confirmed the custodians can decrypt it, and stored recovery material separately.</span></label><Button type="submit" className={buttonClass} disabled={!allowed}>Acknowledge handoff</Button></form>}
      {data.health.state==='sealed'&&<form onSubmit={e=>transient(e,'unseal')} className="space-y-3"><h3 className="font-medium">3. Submit one unseal share</h3>{field('share','Unseal share',{type:'password'})}<p className="text-sm">The share is cleared from this form on submit. It is forwarded transiently and never saved in a plan or job. Each custodian submits their own share.</p><Button type="submit" className={buttonClass} disabled={!allowed}>Submit share</Button></form>}
      {!state.bootstrapComplete&&data.health.state==='unsealed'&&<form onSubmit={e=>transient(e,'bootstrap')} className="space-y-3"><h3 className="font-medium">4. Apply owned access configuration</h3><p className="text-sm">Complete the dedicated Keycloak client handoff first. Supply a bootstrap token authorized for the named resources and the selected disposable database password. Both are transient; the bootstrap token is revoked after the separate machine identity is verified.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{field('bootstrapToken','Bootstrap token',{type:'password'})}{field('databasePassword','Disposable database administrator password',{type:'password'})}</div><label className="flex gap-2 min-h-11 items-start text-sm"><input type="checkbox" required className="mt-1"/><span>I authorize the exact owned mounts and policies in the review and revocation of this bootstrap token.</span></label><Button type="submit" className={buttonClass} disabled={!allowed||(state.config.mode==='install'&&!state.handoffAcknowledged)}>Configure owned access</Button></form>}
      {state.bootstrapComplete&&<p className="text-sm">Access configuration is ready. Apply verifies machine allow/deny, then issues, uses and revokes a limited PostgreSQL credential. Human browser acceptance should confirm a mapped Keycloak user succeeds and an unmapped user is refused.</p>}
    </>}
  </CardContent></Card>;
}
