import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
const buttonClass = 'min-h-11 w-full sm:w-auto whitespace-normal bg-green-700 hover:bg-green-800 text-white';
const field = (id, label, props = {}) => <div className="space-y-2 min-w-0"><Label htmlFor={'vw-' + id}>{label}</Label><Input id={'vw-' + id} name={id} required autoComplete="off" {...props} /></div>;
export default function VaultwardenSetup({ revision, dirty, choice, connections = [], managed = false }) {
  const [data, setData] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState(''), [reviewed, setReviewed] = useState(false);
  const state = data?.state, review = data?.review, pending = ['queued', 'running'].includes(state?.job?.status), skipped = choice.mode === 'skip';
  const matches = !state || state.config.mode === choice.mode && state.config.origin === choice.url;
  const allowed = !!data && revision > 0 && !dirty && !skipped && matches && !busy && !pending;
  useEffect(() => { let active = true; const poll = async () => { try { const v = await api.getVaultwardenSetup(); if (active) setData(v); } catch { if (active) { setData(null); setError('Vaultwarden status is unavailable. Reopen before applying.'); } } }; poll(); const t = setInterval(poll, 10000); return () => { active = false; clearInterval(t); }; }, []);
  useEffect(() => setReviewed(false), [revision, dirty, choice.mode, choice.url, review?.reviewToken]);
  const approval = () => ({ revision: state.revision, reviewToken: review.reviewToken, reviewed: true });
  async function run(fn) { setBusy(true); setError(''); setMessage(''); setReviewed(false); try { await fn(); setData(await api.getVaultwardenSetup()); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  function save(e) {
    e.preventDefault(); const form = e.currentTarget, f = new FormData(form);
    const input = { expectedPlanRevision: revision, expectedRevision: 0, connectionId: f.get('connectionId'), clientId: f.get('clientId'), clientSecret: f.get('clientSecret'), accessRole: f.get('accessRole'), matchExistingEmail: f.get('matchExistingEmail') === 'yes', allowedIps: String(f.get('allowedIps')).split(/[\s,]+/).filter(Boolean), reviewed: true, ...(choice.mode === 'connect' ? { adminToken: f.get('adminToken') } : {}) };
    form.elements.clientSecret.value = ''; if (form.elements.adminToken) form.elements.adminToken.value = '';
    run(async () => { await api.saveVaultwardenSetup(input); setMessage('Settings saved. Complete the dedicated client handoff, review the changes, then apply.'); });
  }
  function ceremony(e) { e.preventDefault(); run(async () => { await api.recordVaultwardenCeremony({ ...approval(), configurationFingerprint: state.lastVerification.configurationFingerprint,
    browserSso: true, vaultUnlock: true, harmlessItem: true, deniedUser: true, existingLogin: true, accountPreserved: true, disposable: true }); setMessage('Operator-observed browser checks recorded for this configuration. No vault secrets or item contents were submitted.'); }); }
  return <Card id="vaultwarden-setup" className="min-w-0"><CardHeader><CardTitle>Set up Vaultwarden</CardTitle><CardDescription>A separate password vault with Keycloak sign-in. Your vault still needs its own unlock secret.</CardDescription></CardHeader><CardContent className="space-y-5 min-w-0">
    {skipped && <p className="text-sm">Vaultwarden is skipped. No installation or removal is performed; existing data is preserved.</p>}
    {(dirty || !revision) && <p className="text-sm">Save the platform plan before configuring Vaultwarden.</p>}
    {!matches && <p role="alert">Platform choices differ from the saved Vaultwarden targets. Restore those choices before applying.</p>}
    {error && <p role="alert" className="text-destructive break-words">{error}</p>}{message && <p role="status" className="border rounded-lg p-3 break-words">{message}</p>}
    {data && <div className="rounded-lg bg-muted p-4 space-y-2 text-sm"><p className="font-medium">Service: {data.health.state.replaceAll('_', ' ')}</p><p>{data.verification.label}</p></div>}
    <div className="text-sm space-y-2"><p>Keycloak verifies who you are. Vaultwarden decrypts your vault separately using your master password or another unlock method supported by your client. A Keycloak passkey does not automatically unlock the vault.</p><p>Keep existing email/password login available while testing. SSO-only stays off; this guide does not activate it. Never enter a master password, recovery code or vault item in ProxyPilot.</p></div>
    {!managed && !state && allowed && <form onSubmit={save} className="space-y-4"><h3 className="font-medium">1. Review connection and access policy</h3><p className="text-sm break-all">{choice.mode === 'install' ? 'Install Vaultwarden 1.37.3 with persistent SQLite storage' : 'Connect to existing Vaultwarden 1.37.3 with read-only checks'} · {choice.url}</p>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="space-y-2"><Label htmlFor="vw-connectionId">Verified Keycloak provider</Label><select id="vw-connectionId" name="connectionId" required defaultValue="" className="border bg-background rounded-md min-h-11 p-2 w-full"><option value="" disabled>Select provider</option>{connections.filter(c => c.verifiedAt).map(c => <option key={c.id} value={c.id}>{c.origin} · {c.realm}</option>)}</select></div>
        {field('clientId', 'Dedicated Keycloak client ID', { defaultValue: 'proxypilot-vaultwarden' })}{field('clientSecret', 'Dedicated client secret', { type: 'password' })}{field('accessRole', 'Allowed client role', { defaultValue: 'vault-user' })}
        {choice.mode === 'connect' && field('adminToken', 'Existing Vaultwarden admin token', { type: 'password' })}
        {field('allowedIps', 'Allowed IPv4 addresses through managed Caddy (optional)', { required: false, placeholder: 'Empty allows public access to authenticated vault' })}
        <div className="space-y-2"><Label htmlFor="vw-matchExistingEmail">Existing account linking</Label><select id="vw-matchExistingEmail" name="matchExistingEmail" defaultValue="no" className="border bg-background rounded-md min-h-11 p-2 w-full"><option value="no">Do not link existing accounts by email</option><option value="yes">Link on first SSO login with verified matching email</option></select></div>
      </div><p className="text-sm">Assign this dedicated client role only to the selected users or group. The client flow denies users without the role. Existing password login remains an independent access path for existing users.</p>
      <p className="text-sm">Email linking preserves the existing user ID and vault keys. Review matching verified email addresses first. Do not delete accounts or SSO associations to fix a mismatch.</p>
      {choice.mode === 'connect' && <p className="text-sm">The admin credential is encrypted and reused only for effective configuration reads. This guide makes no configuration writes to the existing vault. Its owner applies the reviewed settings.</p>}
      <label className="flex gap-2 min-h-11 items-start text-sm"><input type="checkbox" required className="mt-1" /><span>I reviewed the selected target, access role and account-linking behavior.</span></label><Button type="submit" className={buttonClass}>Save reviewed Vaultwarden settings</Button><p className="text-xs text-muted-foreground">Saving is inert. No installation or identity change occurs.</p>
    </form>}
    {state && <><div className="text-sm space-y-2"><p className="font-medium break-all">Saved target: {state.config.origin}</p><p>Job: {state.job?.status || 'not applied'}{state.job?.phase ? ` · ${state.job.phase}` : ''}</p>{state.job?.reason && <p className="break-words">{state.job.reason}</p>}
      <p>Browser checks: {state.ceremony && state.ceremony.configurationFingerprint === state.lastVerification?.configurationFingerprint ? 'Recorded by an operator for this configuration' : 'Not recorded for this configuration'}</p></div>
      {review && <details className="border rounded-lg p-4 min-w-0"><summary className="min-h-11 cursor-pointer font-medium">2. Review changes and operator handoff</summary><div className="text-sm space-y-3 break-words">{review.changes.map(x => <p key={x}>{x}</p>)}
        <h4 className="font-medium">Dedicated Keycloak client</h4><p>Use confidential authorization-code flow. Disable full scope, implicit flow, direct grants and service accounts. Require S256 PKCE and RS256. Set this client’s access-token lifespan to 600 seconds; assign profile, email and offline_access scopes.</p>
        <p className="break-all">Only redirect URI: {review.callback}</p><p className="break-all">Only web origin: {state.config.origin}</p><p className="break-all">Create non-composite client role: {review.role}. Assign it only to the chosen users/group.</p>
        <p className="break-all">Create dedicated top-level basic flow {review.flow}. First add WebAuthn Passwordless Authenticator (REQUIRED). Next add a CONDITIONAL basic subflow with Condition – User Role (REQUIRED; role {review.role}; Negate enabled), then Deny Access (REQUIRED). Bind only this client’s Browser Flow override to that flow. Preserve the realm’s existing passwordless policy and all other clients.</p>
        <p>The existing read-only Keycloak observer verifies these settings. Use the existing Keycloak passkey enrollment; no new passkey registration is created in ProxyPilot.</p>
        <h4 className="font-medium">Vaultwarden settings</h4><p>For an existing instance, its owner updates only these reviewed values plus the dedicated SSO client secret through the existing administration/configuration mechanism. Retain all database, data-folder, server-key, mail and unrelated settings. Admin settings override environment values; apply verifies the effective result.</p>
        <pre className="whitespace-pre-wrap break-all rounded bg-muted p-3 text-xs">{JSON.stringify(review.settings, null, 2)}</pre>
        {review.adminHandoff && <p className="break-all">Managed administrator handoff: the host operator retrieves {review.adminHandoff} over their protected administrative channel. This administrative token does not unlock user vaults.</p>}
        <h4 className="font-medium">Recovery and clients</h4><p>Back up SQLite with Vaultwarden’s built-in backup command, plus attachments, sends, server keys, effective configuration and the protected ProxyPilot database/installation key using existing backup mechanisms. A complete stopped-service copy is another supported option. Restore compatible sets with Vaultwarden stopped; do not pair a database backup with a stale WAL.</p>
        <p>If Keycloak is down, use retained email/password login and Vaultwarden’s own second factor/recovery method. Losing a Keycloak device does not replace a vault-unlock secret. An administrator cannot recover an unknown master password merely by resetting Keycloak. ProxyPilot’s separate local recovery remains available.</p>
        <p>Test the bundled web vault first. Extension/mobile/desktop versions can differ in SSO support; desktop browser handoff has documented limitations. This guide installs no client integration and does not claim Keycloak session revocation clears offline decrypted vaults.</p>
      </div></details>}
      <label className="flex gap-2 items-start min-h-11 text-sm"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} disabled={!allowed} className="mt-1" /><span>I reviewed this configuration and completed the dedicated client handoff.</span></label>
      <Button className={buttonClass} disabled={!allowed || !reviewed || !review} onClick={() => run(async () => { await api.applyVaultwardenSetup(approval()); setMessage('Vaultwarden job queued. Progress survives closing this page.'); })}>{pending ? 'Operation pending' : 'Apply / retry Vaultwarden verification'}</Button>
      {state.lastVerification && <form onSubmit={ceremony} className="space-y-3"><h3 className="font-medium">3. Verify directly in the web vault</h3><p className="text-sm">Use disposable accounts and a harmless test item. Enter all passwords and item contents directly in Vaultwarden, never here. These checks record your observations; they are not an automated unlock test.</p>
        <a href={state.config.origin} target="_blank" rel="noreferrer" className="inline-flex items-center min-h-11 underline break-all">Open Vaultwarden in another tab</a>
        {['I signed in through Keycloak with the allowed disposable account.', 'I completed the separate supported vault unlock and created/read a harmless test item.', 'I locked the vault and unlocked it again; Keycloak sign-in alone did not decrypt it.', 'A fresh browser session for a user without the selected client role was refused SSO access.', 'Email/password login still works and account IDs, old items and vault keys are preserved, including any reviewed email linking.'].map(x => <label key={x} className="flex gap-2 items-start min-h-11 text-sm"><input type="checkbox" required className="mt-1" /><span>{x}</span></label>)}
        <Button type="submit" className={buttonClass} disabled={!allowed}>Record operator-observed checks</Button>
      </form>}
    </>}
  </CardContent></Card>;
}
