// The storage family: host block devices, ZFS pools and datasets, the Incus
// binding, sanoid/syncoid backup and replication, freshness. Every mutating
// tool follows the plan/confirm flow: dry_run: true returns the exact
// command plan and a plan_token (sha256 of that plan); the real call carries
// confirm: true and that token, and a changed plan invalidates the token.

import { P, tool } from './shared.js';

const plan_token = { type: 'string', description: 'The sha256 plan token returned by the dry_run call. The real call must carry it together with confirm: true; any change to the plan since (host state or parameters) invalidates it.' };
const wipe = { type: 'boolean', description: 'Clear existing signatures (old ZFS labels, md/LVM/LUKS, filesystems, partition tables) on the chosen devices. Never applies to the OS device, a mounted device, or a member of an imported pool.' };
const pool = { type: 'string', description: 'ZFS pool name.' };
const dataset = { type: 'string', description: 'ZFS dataset name (pool/child).' };
const snapshot = { type: 'string', description: 'Full snapshot name: dataset@name (list_zfs_snapshots).' };
const guest = { type: 'string', description: 'Incus guest name (as list_lxc_containers shows it, e.g. pp-web).' };

/** A plan/confirm tool: dry_run + confirm + plan_token on top of its own params. */
function planned(name, description, properties = {}, required = []) {
  return tool(name, `${description} Plan/confirm: dry_run: true returns the exact commands and a plan_token; re-call with confirm: true and that token to run it.`, { ...properties, dry_run: P.dry_run, confirm: P.confirm, plan_token }, required);
}

export const STORAGE_TOOLS = [
  tool('list_disks', 'Every block device on the host: model, serial, size, transport, rotational, partitions, filesystems, mountpoints, holders, /dev/disk/by-id paths, SMART health (temperature, reallocated/pending sectors, power-on hours, NVMe wear), signatures (ZFS labels, mdadm, LVM, LUKS), which imported pool it belongs to, importable pools found on it, and os: true on the device(s) backing / and /boot. Also reports eligibility for a new pool.', { smart: { type: 'boolean', description: 'Collect SMART data (default true; slower).' } }),
  tool('zpool_status', 'Imported ZFS pools: health, capacity, fragmentation, vdev tree with per-device errors, scrub/resilver state and last scrub, plus importable (exported) pools found on disk.', {}),
  tool('zfs_list', 'ZFS datasets with used/available/referenced, quota, compression and ratio, encryption and key status, mountpoint, recordsize, origin; optionally filtered to one pool or dataset subtree.', { pool, dataset }),
  tool('list_zfs_snapshots', 'ZFS snapshots (newest last) with creation time, used/referenced bytes, clones and who made them (sanoid, syncoid, incus, proxypilot, manual). Filter by dataset, guest, or kind. (Named list_zfs_snapshots because list_snapshots is the Incus snapshot tool.)', { dataset, guest, kind: { type: 'string', enum: ['sanoid', 'syncoid', 'incus', 'proxypilot', 'manual'] }, limit: P.limit }),
  planned('create_zpool', 'Create a ZFS pool from whole disks named by /dev/disk/by-id path: layout single | mirror | raidz1 | raidz2 | raidz3 with vdev groups, ashift 12, compression zstd, atime off, xattr sa, acltype posixacl by default, optional native encryption (passphrase on stdin at apply time, or a key file path on the host — nothing is stored). Refuses the OS device outright and any device with a mounted filesystem, an active md/LVM holder or membership of an imported pool; other signatures need wipe: true. Creates the managed datasets <pool>/incus, /backups, /exports and records the pool as managed.',
    { name: pool, layout: { type: 'string', enum: ['single', 'mirror', 'raidz1', 'raidz2', 'raidz3'] }, devices: { type: 'array', items: { type: 'string' }, description: 'by-id paths; one vdev (or, for single, one vdev per device).' }, vdevs: { type: 'array', items: { type: 'array', items: { type: 'string' } }, description: 'Explicit vdev groups of by-id paths (e.g. two mirrors).' }, ashift: { type: 'number' }, compression: { type: 'string' }, atime: { type: 'string', enum: ['on', 'off'] }, xattr: { type: 'string', enum: ['sa', 'on', 'off'] }, mountpoint: { type: 'string' }, encryption: { type: 'object', description: '{ keyformat: "passphrase" } (passphrase given on the confirm call) or { keyformat: "raw"|"hex"|"passphrase", keylocation: "file:///path" }.' }, passphrase: { type: 'string', description: 'Only on the confirm call of an encrypted pool with keylocation prompt; never stored or logged.' }, wipe, managed: { type: 'boolean', description: 'Create the managed datasets and record the pool (default true).' } }, ['name']),
  planned('set_managed_pool', 'Adopt an existing imported pool as the managed one (creating any missing <pool>/incus, /backups, /exports datasets), or clear the setting with pool: null.', { pool: { type: ['string', 'null'] }, incus_pool: { type: 'string', description: 'The Incus storage pool that lives on it, if already created.' }, datasets: { type: 'object', description: 'Override { incus, backups, exports } dataset names.' } }),
  planned('create_dataset', 'Create a dataset (or a zvol with volume_size) under an existing parent with optional properties.', { name: dataset, props: { type: 'object', description: 'compression, atime, quota, refquota, recordsize, mountpoint, canmount, readonly, xattr, acltype, …' }, volume_size: { type: 'string' }, sparse: { type: 'boolean' } }, ['name']),
  planned('set_dataset_props', 'Set properties on a dataset (allowlisted: compression, atime, relatime, quota, refquota, reservation, refreservation, recordsize, mountpoint, canmount, readonly, snapdir, sync, logbias, primarycache, secondarycache, xattr, acltype, dnodesize, copies, dedup, checksum, exec, setuid, devices).', { dataset, props: { type: 'object' } }, ['dataset', 'props']),
  planned('destroy_dataset', 'Destroy a dataset and its children AFTER taking a fresh recursive snapshot and streaming it (zfs send -R) into the backups location, so the data stays recoverable with zfs receive. Refuses guest storage, Incus pool sources and pools themselves.', { dataset }, ['dataset']),
  planned('zfs_snapshot', 'Take a snapshot of a dataset (name defaults to pp-manual-<timestamp>).', { dataset, name: { type: 'string' }, recursive: { type: 'boolean' } }, ['dataset']),
  planned('zfs_rollback', 'Roll a dataset back to a snapshot. Refuses when newer snapshots exist unless destroy_newer: true; refuses guest storage (use rollback_guest_dataset).', { snapshot, destroy_newer: { type: 'boolean' } }, ['snapshot']),
  planned('destroy_zfs_snapshot', 'Destroy one ZFS snapshot (not an Incus one, not one with clones).', { snapshot }, ['snapshot']),
  planned('replace_disk', 'zpool replace: swap a pool member (by path, name or guid as zpool_status shows it) for a new whole disk given by /dev/disk/by-id path; the resilver runs in the background and zpool_status shows its progress. Same eligibility rules as create_zpool.', { pool, old_device: { type: 'string' }, new_device: { type: 'string' }, wipe }, ['pool', 'old_device', 'new_device']),
  planned('zpool_scrub', 'Start, stop or pause a scrub, and optionally enable/disable the monthly scrub timer (proxypilot-zfs-scrub@<pool>.timer). Progress and the last scrub are in zpool_status.', { pool, action: { type: 'string', enum: ['start', 'stop', 'pause'] }, timer: { type: 'boolean', description: 'true enables the monthly timer, false disables it; omit to leave it.' } }, ['pool']),
  planned('import_pool', 'Import an exported pool found on disk (by name or id, always through /dev/disk/by-id). A pool that is not ONLINE needs force: true; readonly: true imports read-only; load_key: true prompts for the encryption passphrase.', { pool, force: { type: 'boolean' }, readonly: { type: 'boolean' }, load_key: { type: 'boolean' }, passphrase: { type: 'string' } }, ['pool']),
  planned('export_pool', 'Export (cleanly detach) a pool. Refused while Incus guests run on it; when Incus storage pools use it, force: true acknowledges they go offline until re-import. Exporting the managed pool clears the managed setting.', { pool, force: { type: 'boolean' } }, ['pool']),
  planned('set_incus_storage_pool', 'incus storage create <name> zfs source=<dataset> (skipped when it already exists on that dataset) and make it the default profile\'s root pool. Incus refuses to repoint that root disk while instances inherit it, so the plan first pins every such instance to the pool it is already on (incus config device override <guest> root pool=<current>) — no data is moved and existing guests stay where they are; only new guests land on the new pool (move_guest_storage moves an existing one). Reports the existing Incus storage pools and the pins in the plan.', { name: { type: 'string', description: 'Incus storage pool name (default "zfs").' }, dataset: { type: 'string', description: 'Default: the managed <pool>/incus dataset.' }, set_default: { type: 'boolean', description: 'Also point the default profile at it (default true).' }, pin_existing: { type: 'boolean', description: 'Pin instances that inherit the default profile\'s root disk to their current pool first (default true). false refuses instead of touching them.' } }),
  planned('set_default_storage_pool', 'Make an existing Incus storage pool the one NEW guests land in — containers, VMs, projects and migrations that do not name a pool of their own. Nothing moves: guests already running stay exactly where they are (the ones inheriting the default profile\'s root disk are pinned to their current pool first, because Incus refuses to repoint that disk while anything relies on it), and move_guest_storage is what moves one. The plan reports every pool, which one is default today, and the line that reverses it.', { pool: { type: 'string', description: 'The Incus pool name, as the storage overview lists it.' }, pin_existing: { type: 'boolean', description: 'Pin instances that inherit the default profile\'s root disk to their current pool first (default true). false refuses instead of touching them.' } }, ['pool']),
  planned('move_guest_storage', 'incus move <guest> --storage <pool> for one guest or a batch: each guest is stopped (only with stop: true), snapshotted, moved, started again and verified Running.', { guest, guests: { type: 'array', items: { type: 'string' } }, pool: { type: 'string', description: 'Incus storage pool name.' }, stop: { type: 'boolean' }, start_after: { type: 'boolean' } }, ['pool']),
  tool('get_backup_policy', 'The sanoid backup policy: retention per class (guests / backups / exports: frequent, hourly, daily, monthly), per-dataset and per-guest overrides, the effective retention of every dataset, and the rendered sanoid.conf.', {}),
  planned('set_backup_policy', 'Change retention for a class ({ class, retention }), a dataset ({ dataset, class?, enabled?, retention? }) or a guest ({ guest, enabled?, retention? }); rewrites /etc/sanoid/sanoid.conf and makes sure sanoid.timer runs.', { class: { type: 'string', enum: ['guests', 'backups', 'exports'] }, dataset, guest, enabled: { type: 'boolean' }, retention: { type: ['object', 'null'], description: '{ frequent, hourly, daily, monthly } counts; null clears an override.' } }),
  tool('replication_status', 'Every syncoid replication job: sources, target, schedule, timer state, last run / last success / last error, log tail, and freshness.', { name: { type: 'string' } }),
  planned('set_replication_target', 'Create or update a syncoid replication job: sources (datasets), target (pool/dataset on a second local pool, or [user@]host:pool/dataset over SSH with ssh_key_path on the host), schedule (hourly | daily | weekly | OnCalendar). Only the target string and schedule are stored in ProxyPilot; the key path lives in the host config file. remove: true deletes a job.', { name: { type: 'string' }, sources: { type: 'array', items: { type: 'string' } }, target: { type: 'string' }, ssh_key_path: { type: 'string' }, ssh_port: { type: 'number' }, schedule: { type: 'string' }, recursive: { type: 'boolean' }, enabled: { type: 'boolean' }, remove: { type: 'boolean' } }, ['name']),
  planned('run_replication', 'Run a replication job now through the ProxyPilot wrapper (waits and returns the result), or with wait: false start its systemd unit in the background and poll replication_status.', { name: { type: 'string' }, wait: { type: 'boolean' } }, ['name']),
  planned('restore_guest_from_snapshot', 'Create a NEW guest from a snapshot of an existing guest\'s dataset: an Incus snapshot is copied with incus copy; a sanoid/manual ZFS snapshot is cloned, packaged as an Incus backup and imported. The original guest is untouched.', { guest, snapshot, new_name: { type: 'string' }, start: { type: 'boolean' } }, ['guest', 'snapshot', 'new_name']),
  planned('rollback_guest_dataset', 'Roll a guest\'s own dataset back to a snapshot in place (stop with stop: true, zfs rollback, start again, verify Running). Refuses when newer Incus snapshots exist; destroy_newer: true accepts destroying newer ZFS snapshots.', { guest, snapshot, stop: { type: 'boolean' }, start_after: { type: 'boolean' }, destroy_newer: { type: 'boolean' } }, ['guest', 'snapshot']),
  tool('storage_freshness', 'Per pool: health, capacity, last scrub and scrub errors; per guest and dataset: last snapshot age against policy; per replication job: last success against schedule. Plus the active storage alerts (pool DEGRADED/FAULTED, SMART failures, scrub errors, stale snapshots/replication).', { alerts: { type: 'boolean', description: 'Also evaluate alert conditions (collects SMART; slower).' } }),
  tool('storage_preflight', 'Can this host install and run the ZFS storage stack? Every check with its status and remedy: apt, distribution, host agent, the root update runner, the installer script, the ZFS tools and kernel module, smartctl, sanoid, syncoid, the ProxyPilot units and helpers. With devices (default true) it also returns each disk with the safety verdict the block layer cannot give: mdadm superblocks including unassembled arrays, /etc/fstab references, EFI boot entries and active swap. Read-only.',
    { devices: { type: 'boolean', description: 'Include the per-disk safety verdict (default true).' } }),
  tool('install_storage_toolchain', 'Install or re-install the storage stack on the host: zfsutils-linux, smartmontools, sanoid and syncoid, the scrub and replication systemd units, and the ProxyPilot helper scripts. Runs the checkout\'s scripts/install-storage.sh through the root update runner, the same privilege path as a self-update; the caller supplies no arguments and no block device is touched. Refused when the preflight is blocked, when an update or install is already running, or when nothing is missing unless force is set. Poll get_storage_install_status for progress.',
    { confirm: P.confirm, dry_run: P.dry_run, force: { type: 'boolean', description: 'Run the installer again even when everything is already present.' } }, ['confirm']),
  tool('get_storage_install_status', 'Progress of a storage install run: status, phase, exit code and the tail of the install log. The host is briefly busy with apt; the dashboard stays up throughout.',
    { id: { type: 'string' }, log_tail_bytes: { type: 'number' } }),
  tool('storage_toolchain', 'What the host has installed for storage management (zfs, zpool, smartctl, sanoid, syncoid, wipefs, the ProxyPilot units and helpers) and the recent storage operations ledger.', { ops_limit: P.limit }),
];
