import { useEffect, useState } from 'react';
import { Check, Cpu, Database, Globe, ListChecks, Plus } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import { operationsApi as api, connectionsApi, brokerTasksApi } from '@/lib/api';
import { Action, Panel, Field, Choice } from './shared';
import { ConnectionCatalogue } from './Connections';
import { connectionAssignmentState, refreshConnectionSelections, operationLabel } from './connection-ui-logic';
import BrokerTasks from '@/components/BrokerTasks';

const steps = ['Work', 'Connections', 'Controls', 'Review'];
const emptyWork = { name: '', role: '', task: '', expected_outcome: '', inputs: [], guide_ref: null, supporting_material: [], environment_ref: null };
const emptyControls = { operations: [], resources: [], max_seconds: 300, max_actions: 20, approval_policy: 'writes', output_ref: null, escalation_user_ids: [] };

export function BrokerAgents({ project, onEditingChange }) {
  const { user } = useAuth();
  const [agents, setAgents] = useState([]), [open, setOpen] = useState(false), [step, setStep] = useState(0);
  const [work, setWork] = useState(emptyWork), [controls, setControls] = useState(emptyControls), [selected, setSelected] = useState([]);
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [created, setCreated] = useState(null), [readiness, setReadiness] = useState(null);
  const [editing,setEditing]=useState(null),[assignmentRevision,setAssignmentRevision]=useState(0);
  const [registrations,setRegistrations]=useState({environments:[],outputs:[]}),[registrationError,setRegistrationError]=useState('');
  useEffect(()=>{if(!open)return;let current=true;setRegistrations({environments:[],outputs:[]});setRegistrationError('');connectionsApi.get('/capabilities').then(caps=>caps.mode==='configured'&&caps.compatible===true?brokerTasksApi.registrations(project.id):{environments:[],outputs:[]}).then(r=>{if(current)setRegistrations({environments:r.environments||[],outputs:r.outputs||[]});}).catch(()=>{if(current)setRegistrationError('Registered environments and output destinations are unavailable. You can save unfinished configuration and try again later.');});return()=>{current=false;};},[project.id,open]);
  const [expiry, setExpiry] = useState(''), [assignmentMessage, setAssignmentMessage] = useState('');
  useEffect(()=>{onEditingChange?.(open);return()=>onEditingChange?.(false);},[open,onEditingChange]);
  const base = `/${project.id}/agent-configurations`;
  const editable = ['owner', 'editor'].includes(project.own_role) && !project.archived_at;
  async function load(signal) { try { const response = await api.get(base, signal); if (!signal?.aborted) setAgents(response.agents); } catch (e) { if (!signal?.aborted) { setAgents([]); setError(e.message); } } }
  useEffect(() => { const c = new AbortController(); load(c.signal); return () => c.abort(); }, [base]);
  function begin() { setEditing(null); setOpen(true); setCreated(null); setReadiness(null); setWork({ ...emptyWork }); setControls({ ...emptyControls }); setSelected([]); setStep(0); setError(''); setAssignmentMessage(''); setExpiry(''); }
  async function create() {
    if (busy) return; setBusy(true); setError('');
    try {
      const result = await api.write(editing ? `${base}/${editing.id}` : base, { ...(editing ? {} : {workflow_type: 'typed_api_v1'}), work, controls: { ...controls, operations: selected.length ? [...new Set(selected.flatMap(s => s.allowedOperations))] : controls.operations, resources: selected.length ? [...new Set(selected.flatMap(s => s.allowedResources))] : controls.resources } }, editing?.revision, editing ? 'PATCH' : 'POST');
      setCreated(result.agent); setReadiness(result.readiness); setOpen(false); await load();
      setAssignmentMessage(selected.length ? 'Draft saved. Review and explicitly assign the selected connections below.' : 'Draft saved. No connection assignment or run was started.');
    } catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  async function assign(selection) {
    setBusy(true); setError('');
    try {
      await connectionsApi.write(`/${selection.id}/assignments`, { user_id: user.id, project_id: project.id, agent_id: created.id, operations: selection.allowedOperations, resources: selection.allowedResources, limits: { max_actions: Math.min(controls.max_actions, selection.limits.max_actions), max_seconds: Math.min(controls.max_seconds, selection.limits.max_seconds) }, expires_at: new Date(expiry).toISOString() }, selection.revision);
      setSelected(old => old.filter(s => s.id !== selection.id)); setAssignmentMessage('Assignment saved. This does not start a run.'); setAssignmentRevision(v=>v+1);
      const result = await api.get(`${base}/${created.id}/readiness`); setReadiness(result.readiness || result);
    } catch (e) { setError(`Agent remains saved. Assignment failed: ${e.message}`); } finally { setBusy(false); }
  }
  async function refreshAssignments() {
    setBusy(true);setError('');
    try{const result=await connectionsApi.get(`?project_id=${project.id}&assignable_to_agent_id=${created.id}`);
      setSelected(old=>refreshConnectionSelections(old,result.connections));
      setAssignmentMessage('Permissions refreshed. Unavailable selections were removed; review the remaining narrowed scope before confirming.');
    }catch(e){setSelected([]);setError(e.message);}finally{setBusy(false);}
  }
  function choose(connection) { setSelected(old => old.some(s => s.id === connection.id) ? old.filter(s => s.id !== connection.id) : connectionAssignmentState(connection).selectable?[...old, { ...connection, allowedOperations: [...connection.operations], allowedResources: [...connection.resources] }]:old); }
  function toggle(id, field, value) { setSelected(old => old.map(s => s.id === id ? { ...s, [field]: s[field].includes(value) ? s[field].filter(v => v !== value) : [...s[field], value] } : s)); }
  const canSave=!busy&&!!work.name.trim()&&Number.isInteger(controls.max_actions)&&controls.max_actions>=1&&controls.max_actions<=20&&Number.isInteger(controls.max_seconds)&&controls.max_seconds>=1&&controls.max_seconds<=300;
  return <section className="operations-ui broker-colors space-y-4 min-w-0" aria-label="API agent setup">
    {!open&&<div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3"><div><h2 className="operations-heading">API agents</h2><p className="text-sm text-muted-foreground mt-1">Configure work and limited connection access. Each agent is saved as a disabled draft.</p></div>{editable&&<Action className="self-start shrink-0" onClick={begin}><Plus className="h-4 w-4 mr-2" aria-hidden="true"/>Add an agent</Action>}</div>}
    {error && <p role="alert" className="text-destructive break-words">{error}</p>}
    {open && <div className="space-y-4 min-w-0">
      <div className="flex flex-col gap-3 border-b sm:flex-row sm:items-end sm:justify-between"><div className="pb-3 min-w-0"><h3 className="operations-heading">{editing ? 'Edit agent' : 'Add an agent'}</h3><p className="text-sm text-muted-foreground break-words mt-1">{work.name||project.name} · Draft</p></div>
      <nav aria-label="Agent setup sections" className="w-full sm:w-auto sm:flex-1 sm:max-w-md"><ol className="flex w-full items-start gap-1">{steps.map((label,i)=><li key={label} className="flex-1 min-w-0"><button type="button" disabled={busy} aria-label={`${i+1}. ${label}`} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)} className={`w-full min-h-11 flex flex-col lg:flex-row items-center justify-center gap-1 lg:gap-2 pb-2 border-b-2 text-xs sm:text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${step===i?'border-primary text-primary font-semibold':'border-transparent text-muted-foreground'}`}><span aria-hidden="true" className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs ${step===i?'bg-primary text-primary-foreground':i<step?'bg-accent text-accent-foreground':'border bg-background'}`}>{i<step?<Check className="h-3.5 w-3.5"/>:i+1}</span><span>{label}</span></button></li>)}</ol></nav></div>

      {step === 0 && <Panel title="Work" description="Describe the task and its expected result.">
        <div className="rounded-md border bg-muted/20 p-3 space-y-1"><h3 className="font-medium text-sm flex items-center gap-2"><Database className="h-4 w-4" aria-hidden="true"/>Supported execution: synthetic ledger API</h3><p className="text-sm text-muted-foreground">Read a permitted ledger item or update its state. A role such as Researcher describes the work; it does not enable browser research, website sign-in, OAuth or other services.</p></div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{[['name','Agent name'],['role','Role']].map(([key,label])=><Field key={key} label={label} value={work[key]} maxLength={key==='name'?200:4096} required={key==='name'} onChange={e=>setWork({...work,[key]:e.target.value})}/>)}</div>
        {[['task','Task'],['expected_outcome','Expected outcome']].map(([key,label])=><Field key={key} label={label} value={work[key]} maxLength={4096} textarea rows={3} onChange={e=>setWork({...work,[key]:e.target.value})}/>)}
        <RegistrationChoice label="Execution environment" value={work.environment_ref} records={registrations.environments.filter(r=>r.workflow_type==='typed_api_v1')} onChange={value=>setWork({...work,environment_ref:value})}/>{registrationError&&<p role="status" className="text-sm text-muted-foreground">{registrationError}</p>}<Choice label="Approved guide" value={work.guide_ref?.id || ''} onChange={e => setWork({ ...work, guide_ref: e.target.value ? { id: project.current_version.id, hash: project.current_version.content_hash } : null })}><option value="">Choose or complete later</option>{project.current_version?.content_hash && <option value={project.current_version.id}>Reuse approved guide v{project.current_version.version_number}</option>}</Choice>
        <p className="text-sm text-muted-foreground">Reuse an applicable approved guide, or save the project guide first. Environment and connection checks can be completed after saving this draft.</p>
        <details className="border-t pt-2"><summary className="min-h-11 sm:min-h-9 cursor-pointer flex items-center text-sm font-medium">Inputs and supporting material</summary><div className="space-y-4 pt-2"><Field label="Inputs (one item per line)" textarea rows={3} value={work.inputs.join('\n')} onChange={e=>setWork({...work,inputs:e.target.value.split('\n').slice(0,32)})}/><Field label="Supporting material (one reference per line)" textarea rows={3} value={work.supporting_material.join('\n')} onChange={e=>setWork({...work,supporting_material:e.target.value.split('\n').slice(0,32)})}/></div></details>
      </Panel>}
      {step === 1 && <div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1fr)_13rem] gap-4"><Panel contained={false} title="Connections & credentials" description="Choose the services this agent may use.">
        <section className="rounded-md border p-3 space-y-2"><h3 className="font-medium text-sm flex items-center gap-2"><Cpu className="h-4 w-4" aria-hidden="true"/>Model provider <span className="ml-auto text-xs font-normal text-muted-foreground">Unavailable</span></h3><p className="text-xs text-muted-foreground">This API workflow has no model-provider connection. The synthetic sign-in pilot uses its own approved provider.</p></section>
        <ConnectionCatalogue projectId={project.id} agentId={editing?.id} onSelect={choose} onCatalogueChange={rows=>setSelected(old=>refreshConnectionSelections(old,rows))} selectedIds={selected.map(s => s.id)} renderSelected={connection=>{const s=selected.find(item=>item.id===connection.id);return s?<section key={s.id} className="relative"><div className="min-h-11 sm:min-h-9 flex items-center sm:pr-24"><p className="text-xs break-words">Agent scope: {s.allowedOperations.map(operationLabel).join(', ')||'No operations selected'} · {s.allowedResources.length} resources</p></div><details><summary className="min-h-11 sm:min-h-9 cursor-pointer text-xs font-medium flex items-center text-primary sm:absolute sm:top-0 sm:right-0">Edit scope</summary><p className="text-xs text-muted-foreground mb-2">Narrow this assignment within the owner's ceiling.</p>{[['allowedOperations', s.operations, 'Operation'], ['allowedResources', s.resources, 'Resource']].map(([field, values, label]) => <fieldset key={field}><legend className="text-sm font-medium">{label}</legend>{values.map(value => <label className="flex min-h-11 gap-3 items-center break-all" key={value}><input type="checkbox" checked={s[field].includes(value)} onChange={() => toggle(s.id, field, value)} /><span className="text-sm">{operationLabel(value)}</span></label>)}</fieldset>)}</details></section>:null;}} />
        <section className="rounded-md border p-3 space-y-1"><h3 className="font-medium text-sm flex items-center gap-2"><Globe className="h-4 w-4" aria-hidden="true"/>Browser accounts and mailboxes</h3><p className="text-xs text-muted-foreground">Unavailable for this API workflow. Browser passwords and OAuth credentials are not accepted.</p></section>
      </Panel><aside className="operations-card rounded-md border bg-card p-3 space-y-3 self-start" aria-label="Agent connection summary"><h3 className="text-sm font-semibold">Assigned to this agent</h3><p className="text-xs text-muted-foreground">Pending selections. Confirm each assignment after saving the draft.</p>{selected.length?<ul className="divide-y">{selected.map(s=><li key={s.id} className="flex items-start gap-2 py-3 first:pt-0"><Database className="h-5 w-5 shrink-0 mt-0.5" aria-hidden="true"/><div className="min-w-0"><p className="text-sm font-medium break-words">{s.name}</p><p className="text-xs text-muted-foreground mt-1">Pending · {s.allowedOperations.length} operations</p></div></li>)}</ul>:<p className="text-sm text-muted-foreground">No connections selected.</p>}</aside></div>}
      {step === 2 && <Panel title="Controls" icon={ListChecks} description="Set limits and decide where results and questions go."><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="Maximum actions" type="number" min={1} max={20} value={controls.max_actions} onChange={e => setControls({ ...controls, max_actions: Number(e.target.value) })} /><Field label="Maximum duration (seconds)" type="number" min={1} max={300} value={controls.max_seconds} onChange={e => setControls({ ...controls, max_seconds: Number(e.target.value) })} /></div><RegistrationChoice label="Output destination" value={controls.output_ref} records={registrations.outputs.filter(r=>r.kind==='project_activity')} onChange={value=>setControls({...controls,output_ref:value})}/>{registrationError&&<p role="status" className="text-sm text-muted-foreground">{registrationError}</p>}<Field label="Escalation account IDs (one per line, optional)" textarea rows={2} value={controls.escalation_user_ids.join('\n')} onChange={e=>setControls({...controls,escalation_user_ids:e.target.value.split('\n').filter(Boolean).slice(0,32)})}/><div className="rounded-md border bg-muted/20 p-3 space-y-1"><h3 className="text-sm font-medium">Approval for every write</h3><p className="text-sm text-muted-foreground">Approval is bound to the exact operation. Connection limits may further narrow these controls. Scheduling and browser actions are unavailable.</p></div><Field label="Assignment expiry (your local time)" type="datetime-local" value={expiry} onChange={e => setExpiry(e.target.value)} /><p className="text-sm text-muted-foreground">Expiry is required only when confirming an assignment. You can save a draft without one.</p></Panel>}
      {step === 3 && <Panel title="Review" description="Check the draft before saving. Assignment and execution follow separately."><div className="space-y-3"><h3 className="text-lg font-semibold break-words">{work.name || 'Name required'}</h3><p className="text-sm break-words">{work.task || 'Task to be completed'}</p><dl className="text-sm divide-y">{[['Workflow','Synthetic ledger API only'],['Connections',`${selected.length} selected · pending explicit assignment`],['Limits',`Up to ${controls.max_actions} actions / ${controls.max_seconds} seconds`],['Environment',registrations.environments.find(r=>r.id===work.environment_ref)?.name || (work.environment_ref?'Unavailable registration':'To be selected')],['Output',registrations.outputs.find(r=>r.id===controls.output_ref)?.name || (controls.output_ref?'Unavailable registration':'To be selected')],['Guide',work.guide_ref?'Approved version selected':'Save or select an approved guide']].map(([label,value])=><div key={label} className="grid grid-cols-1 sm:grid-cols-[7rem_minmax(0,1fr)] gap-1 sm:gap-3 py-2"><dt className="text-muted-foreground">{label}</dt><dd className="break-words">{value}</dd></div>)}</dl><p className="rounded-md bg-accent p-3 text-sm">Saving creates a disabled draft. It assigns no connections, grants no access and starts no run.</p></div></Panel>}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 border-t pt-4"><div className="flex flex-wrap gap-2"><Action variant="outline" onClick={() => setOpen(false)} disabled={busy}>Cancel setup</Action>{step > 0 && <Action variant="outline" disabled={busy} onClick={() => setStep(step - 1)}>Back</Action>}</div><div className="flex flex-col sm:flex-row gap-2"><Action variant={step===3?'default':'outline'} disabled={!canSave} onClick={create}>Save draft</Action>{step<3&&<Action disabled={busy} onClick={()=>setStep(step+1)}>Next: {steps[step+1]}</Action>}</div></div>{!work.name.trim()&&<p className="text-xs text-muted-foreground">An agent name is required to save a draft. Other setup can be completed later.</p>}
    </div>}
    {created && <section className="rounded-lg border p-4 space-y-4"><h3 className="font-semibold">{created.work.name} · Draft / disabled</h3><p role="status">{assignmentMessage}</p>{editable&&<Action variant="outline" onClick={()=>{setEditing(created);setWork(created.work);setControls(created.controls);setSelected([]);setCreated(null);setStep(0);setError('');setOpen(true);}}>Edit draft</Action>}{selected.length > 0 && <><Action variant="outline" disabled={busy} onClick={refreshAssignments}>Refresh assignment permissions</Action><Field label="Assignment expiry (your local time)" type="datetime-local" value={expiry} onChange={e => setExpiry(e.target.value)} />{selected.map(s => <div key={s.id} className="border rounded-lg p-3 space-y-3"><p className="break-words">Assign {s.name}: {s.allowedOperations.join(', ')} on {s.allowedResources.length} resources. Expires {expiry || 'not set'}.</p><Action disabled={busy || !expiry || Date.parse(expiry) <= Date.now() || !s.allowedOperations.length || !s.allowedResources.length} onClick={() => assign(s)}>Confirm assignment</Action></div>)}</> }<Readiness value={readiness} projectId={project.id} /><BrokerTasks projectId={project.id} agent={created} assignmentRevision={assignmentRevision}/></section>}
    {!open && <ul className="space-y-3">{agents.filter(a => a.id !== created?.id).map(a => <li key={a.id} className="rounded-lg border p-4 space-y-3"><h3 className="font-semibold break-words">{a.work.name} · Draft / disabled</h3>{editable&&<Action variant="outline" onClick={()=>{setEditing(a);setWork(a.work);setControls(a.controls);setSelected([]);setCreated(null);setStep(0);setError('');setOpen(true);}}>Edit configuration</Action>}<Action variant="outline" onClick={async () => { setError(''); try { const response = await api.get(`${base}/${a.id}/readiness`); setCreated(a); setSelected([]); setReadiness(response.readiness || response); setAssignmentMessage('Configuration saved. Readiness is assessed separately.'); } catch (e) { setError(e.message); } }}>View readiness</Action></li>)}</ul>}
  </section>;
}
const reasonText={BROKER_NOT_ACTIVATED:'The broker is not activated. A reviewed deployment is required.',BROKER_UNAVAILABLE:'The broker could not be reached. Check its deployment and retry.',BROKER_REACHABLE:'The broker responded to the current check.',GUIDE_REQUIRED:'Save the project guide, then select its current approved version in Work.',GUIDE_STALE:'The selected guide has changed. Select the current approved version.',GUIDE_APPROVED:'The selected guide matches the current approved version.',CONNECTION_REQUIRED:'Assign a supported connection.',ENVIRONMENT_REQUIRED:'Select a registered execution environment in Work.',ENVIRONMENT_UNVERIFIED:'The selected environment still needs verification by the broker operator.',ASSIGNMENT_UNVERIFIED:'No current assignment with a verified permitted scope is available.',ASSIGNMENT_REVOKED:'This agent no longer has connection access. Confirm a new permitted assignment.',ASSIGNMENT_CURRENT:'A current assignment covers the configured scope and limits.',PERMISSION_SCOPE_UNVERIFIED:'The available metadata cannot verify your permission ceiling. Ask the connection owner to check the grant.',VAULT_LIVENESS_UNVERIFIED:'A saved credential reference does not verify current vault access. Test the connection.',ADAPTER_SUPPORTED:'The synthetic ledger API adapter is supported.',CREDENTIAL_UNVERIFIED:'The credential needs a current read-only connection test.',CREDENTIAL_REVOKED:'Credential access has been revoked. Ask the owner to restore or replace it.',CREDENTIAL_TESTED:'The current credential passed its connection test.',PROJECT_ARCHIVED:'Restore the project before preparing work.',PROJECT_ACTIVE:'The project is active.',UNVERIFIED:'This requirement has not been verified.'};
const actionText={select_guide:'Save or choose the current approved guide in Work.',select_connection:'Choose a permitted connection, save the draft, then explicitly confirm its assignment.',verify_environment:'Ask the broker operator to complete environment registration and verification, then refresh this setup.',test_connection:'Open Connections and run the permitted read-only test before checking readiness again.',review_deployment:'Ask the broker operator to review its deployment and activation before credential use.',restore_project:'Ask the project owner to restore the project.'};
function Readiness({ value, projectId }) {
  return <div className="space-y-3 border-t pt-4"><h4 className="font-semibold">Readiness checklist</h4><p className="text-sm">Saving configuration starts no run. Check current readiness before explicitly starting a task.</p>{!value?.checks?.length&&<p className="text-sm text-muted-foreground">Readiness is unavailable. Refresh the saved configuration before starting a task.</p>}<ul className="space-y-2">{value?.checks?.map((check, i) => <li className="rounded-md border p-3 text-sm break-words space-y-1" key={`${check.kind}-${i}`}><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium capitalize">{check.kind.replaceAll('_',' ')}</span><span className="text-xs text-muted-foreground capitalize">{check.state}</span></div><p>{reasonText[check.code] || (check.state==='ready'?'Verified for this configuration.':'This requirement needs review before the agent can run.')}</p>{typeof check.next_action === 'string' && <p className="text-muted-foreground">{actionText[check.next_action] || 'Review the project configuration.'}</p>}</li>)}</ul><div className="flex flex-wrap gap-x-5 gap-y-2"><Link className="inline-flex min-h-11 items-center underline text-sm" to={`/operational-projects/${projectId}?section=Guide`}>Open project guide</Link><Link className="inline-flex min-h-11 items-center underline text-sm" to="/connections">Open connections</Link></div><p className="text-sm text-muted-foreground">Complete guide and supported environment checks. Practice and live execution require their own explicit controls and current authority.</p></div>;
}

function RegistrationChoice({label,value,records,onChange}) {
  return <div className="space-y-2"><Choice label={label} value={value||''} onChange={e=>onChange(e.target.value||null)}><option value="">Choose or complete later</option>{value&&!records.some(r=>r.id===value)&&<option value={value} disabled>Previously selected registration unavailable</option>}{records.map(r=><option key={r.id} value={r.id} disabled={r.status!=='ready'}>{r.name}{r.status!=='ready'?' — unavailable':''}</option>)}</Choice>{!records.some(r=>r.status==='ready')&&<p className="text-sm text-muted-foreground">No available registration. Saving a draft remains possible; execution requires a verified registration.</p>}</div>;
}
