import { useEffect, useState } from 'react';
import { Check, Cpu, Globe, ListChecks } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import { operationsApi as api, connectionsApi, brokerTasksApi } from '@/lib/api';
import { Action, Field, Choice } from './shared';
import { ConnectionCatalogue } from './Connections';
import BrokerTasks from '@/components/BrokerTasks';

const steps = ['Work', 'Connections', 'Controls', 'Review'];
const emptyWork = { name: '', role: '', task: '', expected_outcome: '', inputs: [], guide_ref: null, supporting_material: [], environment_ref: null };
const emptyControls = { operations: [], resources: [], max_seconds: 300, max_actions: 20, approval_policy: 'writes', output_ref: null, escalation_user_ids: [] };

export function BrokerAgents({ project, onEditingChange }) {
  const { user } = useAuth();
  const [agents, setAgents] = useState([]), [open, setOpen] = useState(false), [step, setStep] = useState(0);
  const [work, setWork] = useState(emptyWork), [controls, setControls] = useState(emptyControls), [selected, setSelected] = useState([]);
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [created, setCreated] = useState(null), [readiness, setReadiness] = useState(null);
  const [editing,setEditing]=useState(null),[assignmentRevision,setAssignmentRevision]=useState(0);
  const [registrations,setRegistrations]=useState({environments:[],outputs:[]}),[registrationError,setRegistrationError]=useState('');
  useEffect(()=>{if(!open)return;let current=true;setRegistrations({environments:[],outputs:[]});setRegistrationError('');connectionsApi.get('/capabilities').then(caps=>caps.mode==='configured'&&caps.compatible===true?brokerTasksApi.registrations(project.id):{environments:[],outputs:[]}).then(r=>{if(current)setRegistrations({environments:r.environments||[],outputs:r.outputs||[]});}).catch(()=>{if(current)setRegistrationError('Registered environments and output destinations are unavailable. You can save unfinished configuration and try again later.');});return()=>{current=false;};},[project.id,open]);
  const [expiry, setExpiry] = useState(''), [assignmentMessage, setAssignmentMessage] = useState('');
  useEffect(()=>{onEditingChange?.(open);return()=>onEditingChange?.(false);},[open,onEditingChange]);
  const base = `/${project.id}/agent-configurations`;
  const editable = ['owner', 'editor'].includes(project.own_role) && !project.archived_at;
  async function load(signal) { try { const response = await api.get(base, signal); if (!signal?.aborted) setAgents(response.agents); } catch (e) { if (!signal?.aborted) { setAgents([]); setError(e.message); } } }
  useEffect(() => { const c = new AbortController(); load(c.signal); return () => c.abort(); }, [base]);
  function begin() { setEditing(null); setOpen(true); setCreated(null); setReadiness(null); setWork({ ...emptyWork }); setControls({ ...emptyControls }); setSelected([]); setStep(0); setError(''); setAssignmentMessage(''); setExpiry(''); }
  async function create() {
    if (busy) return; setBusy(true); setError('');
    try {
      const result = await api.write(editing ? `${base}/${editing.id}` : base, { ...(editing ? {} : {workflow_type: 'typed_api_v1'}), work, controls: { ...controls, operations: selected.length ? [...new Set(selected.flatMap(s => s.allowedOperations))] : controls.operations, resources: selected.length ? [...new Set(selected.flatMap(s => s.allowedResources))] : controls.resources } }, editing?.revision, editing ? 'PATCH' : 'POST');
      setCreated(result.agent); setReadiness(result.readiness); setOpen(false); await load();
      setAssignmentMessage(selected.length ? 'Agent saved. Review and explicitly assign the selected connections below.' : 'Agent saved without connections.');
    } catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  async function assign(selection) {
    setBusy(true); setError('');
    try {
      await connectionsApi.write(`/${selection.id}/assignments`, { user_id: user.id, project_id: project.id, agent_id: created.id, operations: selection.allowedOperations, resources: selection.allowedResources, limits: { max_actions: Math.min(controls.max_actions, selection.limits.max_actions), max_seconds: Math.min(controls.max_seconds, selection.limits.max_seconds) }, expires_at: new Date(expiry).toISOString() }, selection.revision);
      setSelected(old => old.filter(s => s.id !== selection.id)); setAssignmentMessage('Assignment saved. This does not start a run.'); setAssignmentRevision(v=>v+1);
      const result = await api.get(`${base}/${created.id}/readiness`); setReadiness(result.readiness || result);
    } catch (e) { setError(`Agent remains saved. Assignment failed: ${e.message}`); } finally { setBusy(false); }
  }
  async function refreshAssignments() {
    setBusy(true);setError('');
    try{const result=await connectionsApi.get(`?project_id=${project.id}&assignable_to_agent_id=${created.id}`);
      setSelected(old=>old.flatMap(previous=>{const current=result.connections.find(c=>c.id===previous.id&&c.rights.includes('assign')&&c.status!=='revoked'&&c.readiness?.code!=='POLICY_REVALIDATION_REQUIRED');return current?[{...current,allowedOperations:previous.allowedOperations.filter(v=>current.operations.includes(v)),allowedResources:previous.allowedResources.filter(v=>current.resources.includes(v))}]:[];}));
      setAssignmentMessage('Permissions refreshed. Unavailable selections were removed; review the remaining narrowed scope before confirming.');
    }catch(e){setSelected([]);setError(e.message);}finally{setBusy(false);}
  }
  function choose(connection) { setSelected(old => old.some(s => s.id === connection.id) ? old.filter(s => s.id !== connection.id) : [...old, { ...connection, allowedOperations: [...connection.operations], allowedResources: [...connection.resources] }]); }
  function toggle(id, field, value) { setSelected(old => old.map(s => s.id === id ? { ...s, [field]: s[field].includes(value) ? s[field].filter(v => v !== value) : [...s[field], value] } : s)); }
  return <section className="broker-colors space-y-4 min-w-0" aria-label="API agent setup">
    {!open&&<><h2 className="text-xl font-semibold">API agents</h2><p className="text-sm text-muted-foreground">Configure work and limited connection access. Agents are created as disabled drafts; guide approval, checks and practice follow creation.</p></>}
    {error && <p role="alert" className="text-destructive break-words">{error}</p>}
    {!open && editable && <Action onClick={begin}>Add an agent</Action>}
    {open && <div className="space-y-5 min-w-0">
      <div><h3 className="text-xl font-semibold">{editing ? 'Edit agent' : 'Add an agent'}</h3><p className="text-sm text-muted-foreground">Draft configuration · {project.name}</p></div>
      <nav aria-label="Agent setup sections"><ol className="flex w-full items-start gap-1">{steps.map((label,i)=><li key={label} className="flex-1 min-w-0"><button type="button" aria-label={`${i+1}. ${label}`} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)} className={`w-full min-h-11 flex flex-col sm:flex-row items-center justify-center gap-1 sm:gap-2 pb-2 border-b-2 text-xs sm:text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${step===i?'border-primary font-semibold':'border-transparent text-muted-foreground'}`}><span aria-hidden="true" className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs ${step===i?'bg-primary text-primary-foreground':i<step?'bg-accent text-accent-foreground':'border bg-background'}`}>{i<step?<Check className="h-3.5 w-3.5"/>:i+1}</span><span>{label}</span></button></li>)}</ol></nav>

      {step === 0 && <div className="space-y-4"><h3 className="text-lg font-semibold">Work</h3>{[['name', 'Agent name'], ['role', 'Role'], ['task', 'Task'], ['expected_outcome', 'Expected outcome']].map(([key, label]) => <Field key={key} label={label} value={work[key]} maxLength={key === 'name' ? 200 : 4096} required={key === 'name'} textarea={key === 'task' || key === 'expected_outcome'} onChange={e => setWork({ ...work, [key]: e.target.value })} />)}
        <Field label="Inputs (one item per line)" textarea rows={3} value={work.inputs.join('\n')} onChange={e=>setWork({...work,inputs:e.target.value.split('\n').slice(0,32)})}/><Field label="Supporting material (one reference per line)" textarea rows={3} value={work.supporting_material.join('\n')} onChange={e=>setWork({...work,supporting_material:e.target.value.split('\n').slice(0,32)})}/><RegistrationChoice label="Execution environment" value={work.environment_ref} records={registrations.environments.filter(r=>r.workflow_type==='typed_api_v1')} onChange={value=>setWork({...work,environment_ref:value})}/>{registrationError&&<p role="status" className="text-sm text-muted-foreground">{registrationError}</p>}<Choice label="Approved guide" value={work.guide_ref?.id || ''} onChange={e => setWork({ ...work, guide_ref: e.target.value ? { id: project.current_version.id, hash: project.current_version.content_hash } : null })}><option value="">Choose or complete later</option>{project.current_version?.content_hash && <option value={project.current_version.id}>Reuse approved guide v{project.current_version.version_number}</option>}</Choice>
        <p className="text-sm text-muted-foreground">An applicable approved guide can be reused. An execution environment and remaining checks can be completed after creation.</p>
      </div>}
      {step === 1 && <div className="grid grid-cols-1 2xl:grid-cols-[minmax(0,1fr)_13rem] gap-4"><div className="space-y-4"><section className="rounded-lg border p-3 space-y-2"><h3 className="font-medium text-sm flex items-center gap-2"><Cpu className="h-4 w-4" aria-hidden="true"/>Model provider</h3><p className="text-sm text-muted-foreground">Not available for this API workflow. The existing synthetic sign-in pilot keeps its separate approved provider.</p></section><ConnectionCatalogue projectId={project.id} agentId={editing?.id} onSelect={choose} selectedIds={selected.map(s => s.id)} renderSelected={connection=>{const s=selected.find(item=>item.id===connection.id);return s?<section key={s.id} className="space-y-2"><p className="text-xs">Agent scope: {s.allowedOperations.length} actions · {s.allowedResources.length} resources</p><details><summary className="min-h-11 cursor-pointer text-sm font-medium flex items-center">Edit scope</summary><p className="text-xs text-muted-foreground mb-2">Narrow this assignment within the owner’s ceiling.</p>{[['allowedOperations', s.operations, 'Operation'], ['allowedResources', s.resources, 'Resource']].map(([field, values, label]) => <fieldset key={field}><legend className="text-sm font-medium">{label}</legend>{values.map(value => <label className="flex min-h-11 gap-3 items-center break-all" key={value}><input type="checkbox" checked={s[field].includes(value)} onChange={() => toggle(s.id, field, value)} /><span className="text-sm">{({'item.read':'Read item','item.set_state':'Change item state'})[value]||value}</span></label>)}</fieldset>)}</details></section>:null;}} /><section className="rounded-lg border p-3 space-y-2"><h3 className="font-medium text-sm flex items-center gap-2"><Globe className="h-4 w-4" aria-hidden="true"/>Browser accounts and mailboxes</h3><p className="text-sm text-muted-foreground">Unavailable for this API-only workflow. No browser password or OAuth credential is accepted.</p></section></div><aside className="rounded-lg border bg-muted/20 p-3 space-y-3 self-start"><h3 className="text-sm font-semibold flex items-center gap-2"><ListChecks className="h-4 w-4" aria-hidden="true"/>Selected for this agent</h3><p className="text-sm">Assignments are confirmed after saving the draft.</p>{selected.length ? selected.map(s => <p key={s.id} className="text-sm break-words">{s.name} · {s.allowedOperations.length} operations</p>) : <p className="text-sm">No connections selected.</p>}</aside></div>}
      {step === 2 && <div className="space-y-4"><h3 className="text-lg font-semibold">Controls</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="Maximum actions" type="number" min={1} max={20} value={controls.max_actions} onChange={e => setControls({ ...controls, max_actions: Number(e.target.value) })} /><Field label="Maximum duration (seconds)" type="number" min={1} max={300} value={controls.max_seconds} onChange={e => setControls({ ...controls, max_seconds: Number(e.target.value) })} /></div><RegistrationChoice label="Output destination" value={controls.output_ref} records={registrations.outputs.filter(r=>r.kind==='project_activity')} onChange={value=>setControls({...controls,output_ref:value})}/>{registrationError&&<p role="status" className="text-sm text-muted-foreground">{registrationError}</p>}<Field label="Escalation account IDs (one per line, optional)" textarea rows={2} value={controls.escalation_user_ids.join('\n')} onChange={e=>setControls({...controls,escalation_user_ids:e.target.value.split('\n').filter(Boolean).slice(0,32)})}/><p className="rounded-lg border p-4 text-sm">Writes require approval bound to the exact operation. Connection limits may further narrow these controls. Scheduling and browser actions are unavailable.</p><Field label="Assignment expiry (your local time)" type="datetime-local" value={expiry} onChange={e => setExpiry(e.target.value)} /><p className="text-sm text-muted-foreground">Expiry is required only when assigning a connection. You can save a draft without one.</p></div>}
      {step === 3 && <div className="space-y-4"><h3 className="text-lg font-semibold">Review</h3><div className="rounded-lg border p-4 space-y-3"><h4 className="font-medium break-words">{work.name || 'Name required'}</h4><p className="break-words">{work.task || 'Task to be completed'}</p><p>{selected.length} selected connections · up to {controls.max_actions} actions / {controls.max_seconds} seconds</p><p>Environment: {registrations.environments.find(r=>r.id===work.environment_ref)?.name || (work.environment_ref?'Unavailable registration':'To be selected')}</p><p>Output: {registrations.outputs.find(r=>r.id===controls.output_ref)?.name || (controls.output_ref?'Unavailable registration':'To be selected')}</p><p>Guide: {work.guide_ref ? 'Existing approved version selected' : 'To be completed'}</p><p className="text-sm">Creating saves a disabled draft. Connection assignments, readiness checks and any practice or live start are separate actions.</p></div><Action disabled={busy || !work.name.trim() || controls.max_actions < 1 || controls.max_seconds < 1} onClick={create}>{editing ? 'Save agent configuration' : 'Create agent'}</Action></div>}
      <div className="flex flex-wrap gap-3 border-t pt-4"><Action variant="outline" onClick={() => setOpen(false)} disabled={busy}>Cancel setup</Action>{step > 0 && <Action variant="outline" onClick={() => setStep(step - 1)}>Back</Action>}{step < 3 && <Action onClick={() => setStep(step + 1)}>Next: {steps[step + 1]}</Action>}</div>
    </div>}
    {created && <section className="rounded-lg border p-4 space-y-4"><h3 className="font-semibold">{created.work.name} · Draft / disabled</h3><p role="status">{assignmentMessage}</p>{editable&&<Action variant="outline" onClick={()=>{setEditing(created);setWork(created.work);setControls(created.controls);setSelected([]);setCreated(null);setStep(0);setError('');setOpen(true);}}>Edit draft</Action>}{selected.length > 0 && <><Action variant="outline" disabled={busy} onClick={refreshAssignments}>Refresh assignment permissions</Action><Field label="Assignment expiry (your local time)" type="datetime-local" value={expiry} onChange={e => setExpiry(e.target.value)} />{selected.map(s => <div key={s.id} className="border rounded-lg p-3 space-y-3"><p className="break-words">Assign {s.name}: {s.allowedOperations.join(', ')} on {s.allowedResources.length} resources. Expires {expiry || 'not set'}.</p><Action disabled={busy || !expiry || Date.parse(expiry) <= Date.now() || !s.allowedOperations.length || !s.allowedResources.length} onClick={() => assign(s)}>Confirm assignment</Action></div>)}</> }<Readiness value={readiness} projectId={project.id} /><BrokerTasks projectId={project.id} agent={created} assignmentRevision={assignmentRevision}/></section>}
    {!open && <ul className="space-y-3">{agents.filter(a => a.id !== created?.id).map(a => <li key={a.id} className="rounded-lg border p-4 space-y-3"><h3 className="font-semibold break-words">{a.work.name} · Draft / disabled</h3>{editable&&<Action variant="outline" onClick={()=>{setEditing(a);setWork(a.work);setControls(a.controls);setSelected([]);setCreated(null);setStep(0);setError('');setOpen(true);}}>Edit configuration</Action>}<Action variant="outline" onClick={async () => { setError(''); try { const response = await api.get(`${base}/${a.id}/readiness`); setCreated(a); setSelected([]); setReadiness(response.readiness || response); setAssignmentMessage('Configuration saved. Readiness is assessed separately.'); } catch (e) { setError(e.message); } }}>View readiness</Action></li>)}</ul>}
  </section>;
}
const reasonText={BROKER_NOT_ACTIVATED:'The broker is not activated. A reviewed deployment is required.',GUIDE_REQUIRED:'Select an approved guide or complete guide review.',GUIDE_STALE:'The selected guide has changed. Review the current approved version.',CONNECTION_REQUIRED:'Assign a supported connection.',ENVIRONMENT_REQUIRED:'An execution environment is still needed.',PROJECT_ARCHIVED:'Restore the project before preparing work.',UNVERIFIED:'This requirement has not been verified.'};
const actionText={select_guide:'Choose an approved guide in Work.',select_connection:'Choose a permitted connection in Connections.',verify_environment:'Complete environment registration and checks.',review_deployment:'Review and activate the broker deployment before credential use.',restore_project:'Ask the project owner to restore the project.'};
function Readiness({ value, projectId }) {
  return <div className="space-y-3"><h4 className="font-semibold">Readiness checklist</h4><p>Saving configuration starts no run. Check current readiness before explicitly starting a task.</p><ul className="space-y-2">{value?.checks?.map((check, i) => <li className="rounded border p-3 text-sm break-words" key={`${check.kind}-${i}`}>{check.kind.replaceAll('_',' ')}: {check.state} · {reasonText[check.code] || (check.state==='ready'?'Verified for this configuration.':'This requirement needs review before the agent can run.')}{typeof check.next_action === 'string' && <p>{actionText[check.next_action] || 'Review the project configuration.'}</p>}</li>)}</ul><Link className="inline-flex min-h-11 items-center underline" to={`/operational-projects/${projectId}?section=Guide`}>Open project guide</Link><p className="text-sm">Complete guide approval and supported environment checks. Practice and live execution require separate explicit controls and current authority.</p></div>;
}

function RegistrationChoice({label,value,records,onChange}) {
  return <div className="space-y-2"><Choice label={label} value={value||''} onChange={e=>onChange(e.target.value||null)}><option value="">Choose or complete later</option>{value&&!records.some(r=>r.id===value)&&<option value={value} disabled>Previously selected registration unavailable</option>}{records.map(r=><option key={r.id} value={r.id} disabled={r.status!=='ready'}>{r.name}{r.status!=='ready'?' — unavailable':''}</option>)}</Choice>{!records.some(r=>r.status==='ready')&&<p className="text-sm text-muted-foreground">No available registration. Saving a draft remains possible; execution requires a verified registration.</p>}</div>;
}
