import { useEffect, useRef, useState } from 'react';
import { FileText, Maximize2, Minimize2 } from 'lucide-react';
import { browserAgentsApi as api } from '@/lib/api';
import { requestAgentControl } from '@/lib/agent-control';
import { requestSudo } from '@/lib/sudo';
import { Action, Choice, Field, Panel } from './shared';
import { LiveBrowser } from './LiveBrowser';
import { BrowserAuthenticationReadback } from './BrowserAuthenticationReadback';
import { createBrowserFullscreen } from './browser-fullscreen';
import { BrowserConfigurations } from './BrowserConfigurations';
import { ARTIFACT_REVIEW, ASSET_REVIEW, BROWSER_CONSENT, CONVERSION_DISCLOSURE, TERMINAL, approvalPayload, assetRef,
  browserLiveEndpoint, browserPaths, filePayload, readyForStart, safeBrowserCitation, startPayload, verifyPrivateBlob } from './browser-agent-ui';

const words=value=>String(value??'').replaceAll('_',' ');
const pretty=value=>JSON.stringify(value,null,2);
const readinessText={GUIDE_REQUIRED:'Assign the current approved guide and save these settings.',GUIDE_STALE:'Assign the new approved guide and save a new settings revision.',
  INSTALLED_SELECTED_BROWSER_PROOF_REQUIRED:'An installed, isolated browser runner with verified destination policy is required. This installation cannot start the run yet.',CURRENT_APPROVED_GUIDE_REQUIRED:'Assign the current approved guide and save the settings.',PROJECT_LIMITS_REQUIRED:'The owner must set finite project limits that admit this configuration.',PRIVATE_INPUT_PINS_UNRESOLVED:'Review the private inputs and verify their exact hashes.',ATTEMPT_ALREADY_ACTIVE:'A browser attempt is already active for this configuration.',UNRESOLVED_EFFECT:'Reconcile the recorded uncertain effect before starting another attempt.',MODEL_ROUTE_UNAVAILABLE:'The reviewed model provider bridge is unavailable.',
  OWNER_MODEL_CONSENT_REQUIRED:'The owner must review and approve model disclosure for this exact revision.',SELECTED_BROWSER_RUNTIME_NOT_IMPLEMENTED:'The selected-browser runtime is unavailable.',
  RUNNER_REACHABILITY_UNVERIFIED:'Runner reachability to these exact destinations is unverified.',EXACT_TARGET_NETWORK_POLICY_UNVERIFIED:'The installed runner must verify the exact target network policy.',
  SELECTED_SITE_POLICY_UNVERIFIED:'Request and destination policies need verification.',ASSET_RESOLUTION_UNAVAILABLE:'The private input references need verification.',PROJECT_ARCHIVED:'Restore this project before starting.'};
function Readiness({value}) {
  return <div className="rounded-md border bg-muted/30 p-3 space-y-2 text-sm" aria-live="polite"><p className="font-medium">{value?.can_start?'Ready to start':'Start is blocked'}</p>
    {!value?<p>Check the saved revision before starting.</p>:<ul className="space-y-2">{value.checks?.map((check,i)=><li key={`${check.kind}-${i}`} className="break-words">{check.state==='ready'?'✓ ':''}{readinessText[check.code]||`${words(check.kind)}: ${words(check.code)}`}<span className="block text-xs text-muted-foreground">{check.code}</span></li>)}</ul>}
  </div>;
}
function Hash({label,value}) {return <div><dt>{label}</dt><dd className="font-mono text-xs break-all">{value?(typeof value==='object'?pretty(value):String(value)):'Unassigned'}</dd></div>;}

// Private source text stays in React memory and the versioned project record;
// never in browser storage, a URL, a console, or a provisioning request.
export function BrowserAgents({base,project,onChanged=async()=>{}}) {
  const paths=browserPaths(base),[runs,setRuns]=useState([]),[run,setRun]=useState(null),[assets,setAssets]=useState([]);
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[lost,setLost]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[conversion,setConversion]=useState(null);
  const [publicUrl,setPublicUrl]=useState(''),[publicReady,setPublicReady]=useState(null),publicStartKey=useRef(null);
  const controller=useRef(null),epoch=useRef(0),lock=useRef(false),mounted=useRef(false);
  const owner=project.own_role==='owner'&&!project.archived_at;
  const operator=['owner','editor','operator','reviewer'].includes(project.own_role)&&!project.archived_at;
  function clearPrivate() {setLost(true);setRun(null);setAssets([]);setRuns([]);setConversion(null);controller.current?.abort();}
  function fail(e) {
    if([401,403,404].includes(e.status)&&!['ELEVATION_REQUIRED','AGENT_CONTROL_VERIFICATION_REQUIRED'].includes(e.code))clearPrivate();
    setError(`${e.message}${e.code?` (${e.code})`:''}${e.status===412?' Your entered settings are retained. Reload or reconcile the current revision before retrying.':''}`);
  }
  async function load(signal) {
    const result=await api.get(paths.runs,signal);if(!signal?.aborted){setRuns(result.runs||[]);const active=result.runs?.find(item=>item.execution_mode==='public_navigation'&&!TERMINAL.includes(item.state));if(active){const current=await api.get(`${paths.runs}/${active.id}`,signal);if(!signal?.aborted)setRun(current);}}
  }
  useEffect(()=>{
    mounted.current=true;const c=new AbortController(),gen=++epoch.current;controller.current=c;setLoading(true);setLost(false);setError('');setRun(null);setAssets([]);setRuns([]);setConversion(null);
    load(c.signal).catch(e=>{if(!c.signal.aborted&&gen===epoch.current)fail(e);}).finally(()=>{if(!c.signal.aborted&&gen===epoch.current)setLoading(false);});
    return()=>{mounted.current=false;epoch.current++;c.abort();};
  },[base,project.own_role,project.archived_at]);
  useEffect(()=>{
    if(!run?.run?.id||TERMINAL.includes(run.run.state)||lost)return;
    const c=new AbortController(),gen=epoch.current,timer=setInterval(()=>api.get(`${paths.runs}/${run.run.id}`,c.signal).then(value=>{if(!c.signal.aborted&&gen===epoch.current)setRun(value);}).catch(e=>{if(!c.signal.aborted&&gen===epoch.current)fail(e);}),2000);
    return()=>{c.abort();clearInterval(timer);};
  },[base,run?.run?.id,run?.run?.state,lost]);
  async function perform(fn,success,{refresh=true}={}) {
    if(lock.current||lost)return;lock.current=true;setBusy(true);setError('');setMessage('');const gen=epoch.current,signal=controller.current?.signal;
    try{await fn(signal);if(!mounted.current||gen!==epoch.current||signal?.aborted)return;if(refresh)await load(signal);setMessage(success);if(refresh)await onChanged();}
    catch(e){if(mounted.current&&gen===epoch.current&&!signal?.aborted)fail(e);}
    finally{lock.current=false;if(mounted.current&&gen===epoch.current)setBusy(false);}
  }
  return <>{error&&<p role="alert" className="text-destructive break-words">{error}</p>}<Panel title="Public browser" description="Open a public website in the isolated browser and watch it live.">
    <Field label="Website" type="url" placeholder="https://example.com" value={publicUrl} disabled={busy||lost} onChange={e=>{setPublicUrl(e.target.value);setPublicReady(null);publicStartKey.current=null;}}/>
    <Action disabled={!operator||busy||loading||lost||!publicUrl.trim()||runs.some(item=>!TERMINAL.includes(item.state))} onClick={()=>perform(async signal=>{
      publicStartKey.current??=crypto.randomUUID();
      setRun(await api.write(`${base}/public-browser`,{url:publicUrl.trim(),project_revision:project.revision,idempotency_key:publicStartKey.current},null,'POST',signal));publicStartKey.current=null;
    },'Public browser requested. Inspect its activity and live view.')}>Open browser</Action>
    <Action variant="outline" disabled={!operator||busy||lost||!publicUrl.trim()} onClick={()=>perform(async signal=>setPublicReady((await api.get(`${base}/public-browser?url=${encodeURIComponent(publicUrl.trim())}`,signal)).readiness),'Browser readiness measured.',{refresh:false})}>Check browser readiness</Action>
    {publicReady&&<><Readiness value={publicReady}/><details><summary className="cursor-pointer min-h-11 py-3 text-sm">Measured browser capabilities</summary><pre className="text-xs whitespace-pre-wrap break-all">{pretty(publicReady)}</pre></details></>}
    <p className="text-sm text-muted-foreground">Model tasks, private sign-in, files and internal websites are unavailable in this mode.</p>
    <p role="status" className="text-sm">{busy?'Working…':message}</p>
    {run?.run?.execution_mode==='public_navigation'&&<PublicBrowserRun base={base} paths={paths} data={run} busy={busy} setData={setRun} perform={perform}/>}
  </Panel><BrowserConfigurations base={base} project={project} onChanged={onChanged} client={api} externalBusy={busy}
    privateUnavailable={lost} onPrivateClear={clearPrivate}
    renderPreparation={draft=>draft.editable&&<div className="space-y-4">
      <PrivateAssets paths={paths} assets={assets} setAssets={setAssets} busy={draft.busy} owner={owner} perform={perform}/>
      {Array.isArray(draft.configuration?.artifacts?.upload_asset_refs)&&<fieldset className="min-w-0"><legend className="text-sm font-medium">Exact approved website upload inputs</legend>{assets.filter(a=>a.state==='approved'&&a.available).map(asset=><label key={asset.id} className="flex min-h-11 items-start gap-3 py-2 text-sm"><input type="checkbox" className="mt-1 shrink-0" disabled={draft.busy||draft.conflict} checked={draft.configuration.artifacts.upload_asset_refs.some(ref=>ref?.id===asset.id&&ref.sha256===asset.sha256)} onChange={e=>draft.updateConfiguration({...draft.configuration,artifacts:{...draft.configuration.artifacts,upload_asset_refs:e.target.checked?[...draft.configuration.artifacts.upload_asset_refs,assetRef(asset)]:draft.configuration.artifacts.upload_asset_refs.filter(ref=>ref?.id!==asset.id)}})}/><span className="break-all">Allow this reviewed {asset.mime_type} input {asset.id} as an upload candidate. Each external upload still needs its own action approval.</span></label>)}</fieldset>}
      <Conversion paths={paths} project={project} source={draft.source} assets={assets} busy={draft.busy} owner={owner} value={conversion} setValue={setConversion} perform={perform} conflict={draft.conflict} generation={draft.generation} onDraft={draft.placeSuggestion} onAuthorizationFailure={fail}/>
    </div>}
    renderRuntime={draft=><section aria-label="Selected browser runtime" className="border-t pt-4 space-y-4 min-w-0">
      <h3 className="font-semibold">Selected browser runtime</h3>
      <div className="rounded-md border bg-muted/30 p-3 space-y-2 text-sm"><p>Exact public, authenticated or internal destinations require verified runner reachability and security policy before a run.</p><p>Every consequential external change needs its own approval. Off-list contact pauses for an exact destination and purpose. Conversion, consent and Start are separate explicit actions.</p></div>
      <p role="status" aria-live="polite" className="text-sm">{draft.busy?'Working…':loading?'Loading browser runs…':message}</p>
      <div className="flex flex-wrap gap-2"><Action variant="outline" disabled={draft.busy||loading} onClick={()=>perform(signal=>load(signal),'Browser runs refreshed.',{refresh:false})}>Refresh browser runs</Action>
        {operator&&<Action variant="outline" disabled={draft.busy} onClick={()=>perform(async()=>{await requestAgentControl();await requestSudo();},'Run authority verified. Submit the intended action explicitly.',{refresh:false})}>Verify run authority</Action>}</div>
      {draft.saved&&<BrowserExecution key={draft.saved.id} paths={paths} project={project} draft={draft} owner={owner} operator={operator} perform={perform} setRun={setRun}/>}
      <div className="space-y-3"><h3 className="font-semibold">Browser run history</h3>{!runs.length?<p className="text-sm text-muted-foreground">No selected-browser runs yet.</p>:<ul className="space-y-2">{runs.map(item=><li key={item.id} className="rounded-md border p-3 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 min-w-0"><div className="min-w-0"><p className="text-sm font-medium break-words">{draft.saved?.id===item.configuration_id?draft.saved.configuration.name:'Browser agent'} · {words(item.state)}</p><p className="text-xs text-muted-foreground break-all">{item.created_at||item.id}</p></div><Action variant="outline" disabled={draft.busy} onClick={()=>perform(async signal=>setRun(await api.get(`${paths.runs}/${item.id}`,signal)),'Run record loaded.',{refresh:false})}>Inspect browser run</Action></li>)}</ul>}</div>
      {run&&run.run.execution_mode!=='public_navigation'&&<BrowserRun base={base} paths={paths} data={run} project={project} busy={draft.busy} setData={setRun} perform={perform}/>}</section>}/></>;
}

function PublicBrowserRun({base,paths,data,busy,setData,perform}) {
  const run=data.run,active=!TERMINAL.includes(run.state),[liveState,setLiveState]=useState('connecting');
  const root=`${paths.runs}/${run.id}`;
  return <section aria-label="Public browser activity" className="space-y-3 min-w-0">
    <p role="status" className="text-sm">{words(run.state)} · {active?words(liveState):'Browser closed'} · {run.usage.requests} requests · {run.usage.response_bytes.toLocaleString()} response bytes</p>
    {run.result_code&&<p className="text-sm break-words">{words(run.result_code)}</p>}
    <Action variant="outline" disabled={busy||!data.controls.can_cancel} onClick={()=>perform(async signal=>{
      setData(await api.write(`${root}/cancel`,{},run.revision,'POST',signal));
    },'Browser stopped. Inspect the cleanup receipt.')}>Stop browser</Action>
    {active&&data.controls.can_live&&<LiveBrowser base={base} runId={run.id} endpoint={browserLiveEndpoint(base,run.id)} onState={setLiveState}/>}
    {data.receipts?.map((receipt,i)=><p key={i} className="text-sm">Cleanup: {Object.entries(receipt.closed||{}).map(([part,closed])=>`${words(part)} ${closed?'closed':'unverified'}`).join(' · ')}</p>)}
    {run.uncertain&&<p role="alert" className="text-sm text-destructive">Cleanup or an effect remains unverified. Inspect the run record before another launch.</p>}
    <details><summary className="cursor-pointer min-h-11 py-3 text-sm">Browser run record</summary><pre className="text-xs whitespace-pre-wrap break-all">{pretty(data)}</pre></details>
  </section>;
}

function BrowserExecution({paths,project,draft,owner,operator,perform,setRun}) {
  const {saved,dirty,conflict,busy}=draft;
  const [ready,setReady]=useState(null),[consent,setConsent]=useState(null),[reviewed,setReviewed]=useState(false),startKey=useRef(null);
  useEffect(()=>{setReady(null);setConsent(null);setReviewed(false);startKey.current=null;},[saved.id,saved.revision,saved.configuration_sha256,project.revision,project.current_version?.id,project.current_version?.content_hash,dirty,conflict,owner]);
  const blocked=busy||dirty||conflict;
  const execute=(fn,success)=>perform(async signal=>{try{await fn(signal);}catch(e){if(e.status===412)draft.markConflict();throw e;}},success);
  async function consentDecision(signal,allow) {
    setConsent(await api.write(`${paths.configurations}/${saved.id}/model-consent`,{configuration_revision:saved.revision,configuration_sha256:saved.configuration_sha256,allow,reviewed_statement:BROWSER_CONSENT},saved.revision,'PUT',signal));
    setReady((await api.get(`${paths.configurations}/${saved.id}/readiness`,signal)).readiness);
  }
  async function start(signal) {
    if(dirty||conflict)throw new Error('Save or reconcile the local draft before Start.');
    const current=(await api.get(`${paths.configurations}/${saved.id}/readiness`,signal)).readiness;
    setReady(current);if(!readyForStart(current,saved,project,draft))throw new Error('The server cannot start this exact revision. Review readiness.');
    startKey.current??=crypto.randomUUID();setRun(await api.write(`${paths.configurations}/${saved.id}/start`,startPayload(saved,project,startKey.current),saved.revision,'POST',signal));
  }
  return <section aria-label="Saved configuration execution" className="rounded-md border p-3 space-y-3 min-w-0">
    <h4 className="font-semibold">Runtime readiness for saved revision {saved.revision}</h4><Readiness value={ready}/>
    <Action variant="outline" disabled={blocked} onClick={()=>execute(async signal=>setReady((await api.get(`${paths.configurations}/${saved.id}/readiness`,signal)).readiness),'Runtime readiness refreshed.')}>Check readiness</Action>
    <div className="border-t pt-3 space-y-2"><p className="font-medium text-sm">Model disclosure consent: {ready?.model_consent?.allowed===true||ready?.checks?.find(c=>['model_consent','owner_consent'].includes(c.kind))?.state==='ready'||consent?.allowed===true?'given':consent?.allowed===false?'withdrawn':'check readiness'}</p><p className="text-sm text-muted-foreground">The model can receive the approved guide and bounded selected-page content. Only the owner can allow it for this saved revision; credentials stay in the controlled browser session.</p>
      {owner&&<><label className="flex min-h-11 items-start gap-3 py-2 text-sm"><input className="mt-1 shrink-0" type="checkbox" checked={reviewed} disabled={blocked} onChange={e=>setReviewed(e.target.checked)}/><span>I reviewed: {BROWSER_CONSENT}.</span></label><div className="flex flex-wrap gap-2"><Action disabled={blocked||!reviewed} onClick={()=>execute(signal=>consentDecision(signal,true),'Owner consent recorded for this revision. No run started.')}>Give model consent</Action><Action variant="outline" disabled={blocked} onClick={()=>execute(signal=>consentDecision(signal,false),'Model consent withdrawn.')}>Withdraw model consent</Action></div></>}
    </div>{operator&&<Action disabled={blocked||!readyForStart(ready,saved,project,draft)} onClick={()=>execute(start,'Run requested. Inspect the recorded state and receipts.')}>Start browser run</Action>}
    {(dirty||conflict)&&<p className="text-sm">{conflict?'Reconcile the saved revision conflict before consent or Start. Refresh keeps this conflict.':'Save or reload local edits before consent or Start.'}</p>}
  </section>;
}

function PrivateAssets({paths,assets,setAssets,busy,owner,perform}) {
  const picker=useRef(null);
  return <details className="rounded-md border p-3"><summary className="min-h-11 cursor-pointer py-3 font-medium">Private image and file inputs</summary><div className="space-y-3">
    <p className="text-sm text-muted-foreground">Choose a file explicitly. Staging is private; an owner reviews it before model disclosure or website upload. File names and contents are not added to audit messages.</p>
    <Action variant="outline" disabled={busy} onClick={()=>perform(async signal=>setAssets((await api.get(paths.assets,signal)).assets||[]),'Private input metadata refreshed.',{refresh:false})}>List private inputs</Action>
    {owner&&<><Field label="Choose private image or file (up to 16 MiB)" type="file" disabled={busy} onChange={e=>{picker.current=e.target.files?.[0]||null;}}/><Action variant="outline" disabled={busy} onClick={()=>perform(async signal=>{const payload=await filePayload(picker.current,crypto.randomUUID());await api.write(paths.assets,payload,null,'POST',signal);picker.current=null;setAssets((await api.get(paths.assets,signal)).assets||[]);},'Private file staged. Review before use.',{refresh:false})}>Stage selected private file</Action></>}
    <ul className="space-y-3">{assets.map(asset=><li key={asset.id} className="rounded-md border p-3 space-y-2 text-sm min-w-0"><p className="break-words">{asset.mime_type} · {asset.byte_count.toLocaleString()} bytes · {words(asset.state)}</p><p className="break-all font-mono text-xs">{asset.id} · SHA-256 {asset.sha256}</p>
      <PrivateAsset asset={asset} paths={paths} owner={owner} busy={busy} perform={perform} refresh={async signal=>setAssets((await api.get(paths.assets,signal)).assets||[])}/></li>)}</ul>
  </div></details>;
}
function PrivateAsset({asset,paths,owner,busy,perform,refresh}) {
  const [opened,setOpened]=useState(false),[reviewed,setReviewed]=useState(false),[modelReviewed,setModelReviewed]=useState(false),[preview,setPreview]=useState(null),[text,setText]=useState('');
  useEffect(()=>{setOpened(false);setReviewed(false);setModelReviewed(false);setPreview(null);setText('');},[asset.id,asset.sha256]);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  const root=`${paths.assets}/${asset.id}`,modelDecided=asset.reviews?.some(r=>r.purpose==='model_input'&&r.sha256===asset.sha256);
  return <div className="space-y-3"><Action variant="outline" disabled={busy||asset.available===false} onClick={()=>perform(async signal=>{
    const blob=await verifyPrivateBlob(await api.download(`${root}/content?purpose=review`,signal),asset);
    if(['image/png','image/jpeg'].includes(asset.mime_type))setPreview(URL.createObjectURL(blob));else if(['text/plain','text/csv'].includes(asset.mime_type))setText(await blob.text());else saveBlob(blob,`private-input-${asset.id}`);
    setOpened(true);
  },'Exact private input opened for review.',{refresh:false})}>Open exact private input for review</Action>
    {preview&&<img src={preview} alt="Exact private input selected for human review" className="max-w-full h-auto rounded-md border"/>}{text&&<pre className="whitespace-pre-wrap break-words [overflow-wrap:anywhere] max-h-64 overflow-y-auto rounded-md bg-muted p-3">{text}</pre>}
    {(preview||text)&&<Action variant="outline" onClick={()=>{setPreview(null);setText('');}}>Clear private input preview</Action>}
    {asset.reviews?.length>0&&<ul className="space-y-1">{asset.reviews.map(review=><li key={review.purpose}>{words(review.purpose)}: {words(review.decision)} · exact file SHA-256 reviewed</li>)}</ul>}
    {owner&&asset.state==='staged'&&<><label className="flex min-h-11 items-start gap-3 py-2"><input type="checkbox" className="mt-1 shrink-0" disabled={busy||!opened} checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/><span>{ASSET_REVIEW}</span></label><div className="flex flex-wrap gap-2"><Action disabled={busy||!opened||!reviewed} onClick={()=>perform(async signal=>{await api.write(`${root}/review`,{decision:'approve',reviewed_statement:ASSET_REVIEW},null,'PATCH',signal);await refresh(signal);},'Private input approved for explicit use.',{refresh:false})}>Approve input</Action><Action variant="outline" disabled={busy} onClick={()=>perform(async signal=>{await api.write(`${root}/review`,{decision:'reject',reviewed_statement:ASSET_REVIEW},null,'PATCH',signal);await refresh(signal);},'Private input rejected.',{refresh:false})}>Reject input</Action></div></>}
    {owner&&asset.state==='approved'&&!modelDecided&&<><label className="flex min-h-11 items-start gap-3 py-2"><input type="checkbox" className="mt-1 shrink-0" disabled={busy||!opened} checked={modelReviewed} onChange={e=>setModelReviewed(e.target.checked)}/><span>{ARTIFACT_REVIEW}. Purpose: model input.</span></label><div className="flex flex-wrap gap-2"><Action disabled={busy||!opened||!modelReviewed} onClick={()=>perform(async signal=>{await api.write(`${root}/model-review`,{decision:'approve',reviewed_statement:ARTIFACT_REVIEW},null,'POST',signal);await refresh(signal);},'Exact private input approved separately for model disclosure.',{refresh:false})}>Approve exact input for model disclosure</Action><Action variant="outline" disabled={busy} onClick={()=>perform(async signal=>{await api.write(`${root}/model-review`,{decision:'reject',reviewed_statement:ARTIFACT_REVIEW},null,'POST',signal);await refresh(signal);},'Private input model disclosure rejected.',{refresh:false})}>Reject model disclosure for this input</Action></div></>}
  </div>;
}
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function Conversion({paths,project,source,assets,busy,owner,value,setValue,perform,onDraft,conflict=false,generation,onAuthorizationFailure}) {
  const [reviewed,setReviewed]=useState(false),[selected,setSelected]=useState([]),[readiness,setReadiness]=useState(null),[limits,setLimits]=useState({max_seconds:120,max_tokens:30000,max_usd:0.1});
  const requestedGeneration=useRef(null),current=value&&requestedGeneration.current===generation;
  useEffect(()=>{setReviewed(false);},[source,project.revision,project.current_version?.id,selected.join(','),JSON.stringify(limits)]);
  useEffect(()=>{if(!value?.id||!['queued','converting','running'].includes(value.state))return;const c=new AbortController(),timer=setInterval(()=>api.get(`${paths.configurations}/conversions/${value.id}`,c.signal).then(r=>{if(!c.signal.aborted)setValue(r.conversion);}).catch(e=>{if(c.signal.aborted)return;if([401,403,404].includes(e.status)&&!['ELEVATION_REQUIRED','AGENT_CONTROL_VERIFICATION_REQUIRED'].includes(e.code))onAuthorizationFailure(e);else setValue({...value,state:'unavailable'});}),2000);return()=>{c.abort();clearInterval(timer);};},[paths.configurations,value?.id,value?.state]);
  return <details className="rounded-md border p-3"><summary className="min-h-11 cursor-pointer py-3 font-medium">Prepare a draft from instructions, images or files</summary><div className="space-y-3 text-sm">
    <p>The model suggests editable settings with assumptions and source provenance. Review the returned settings before validating and saving. Conversion never starts a run.</p>
    <Action variant="outline" disabled={busy} onClick={()=>perform(async signal=>setReadiness(await api.get(`${paths.configurations}/convert/readiness`,signal)),'Conversion readiness checked.',{refresh:false})}>Check conversion readiness</Action>
    {readiness&&<p className="break-words" role="status">{readiness.available?'Conversion provider available':`Conversion unavailable: ${words(readiness.code)}`}</p>}
    {assets.filter(a=>a.state==='approved'&&a.reviews?.some(r=>r.purpose==='model_input'&&r.decision==='approve'&&r.sha256===a.sha256)).map(asset=><label key={asset.id} className="flex min-h-11 items-start gap-3 py-2"><input type="checkbox" className="mt-1" checked={selected.includes(asset.id)} disabled={busy||!owner} onChange={e=>setSelected(e.target.checked?[...selected,asset.id]:selected.filter(id=>id!==asset.id))}/><span className="break-all">Include separately reviewed {asset.mime_type} input {asset.id}</span></label>)}
    {owner?<><label className="flex min-h-11 items-start gap-3 py-2"><input type="checkbox" className="mt-1 shrink-0" checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/><span>I reviewed: {CONVERSION_DISCLOSURE}.</span></label>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{[['max_seconds','Conversion seconds',10,180,1],['max_tokens','Conversion token ceiling',1000,4000000,1],['max_usd','Conversion spend ceiling (USD)',0.001,20,0.001]].map(([key,label,min,max,step])=><Field key={key} label={label} type="number" min={min} max={max} step={step} required value={limits[key]} disabled={busy} onChange={e=>setLimits({...limits,[key]:e.target.value===''?'':Number(e.target.value)})}/>)}</div>
      <p className="text-xs text-muted-foreground">Conversion source ceiling: 6,000 UTF-8 bytes and 8 separately approved inputs. Image bytes can require a larger explicitly reviewed token ceiling. The server verifies effective ceilings and disclosure before calling the provider.</p>
      <Action disabled={busy||!reviewed||!source.trim()||new TextEncoder().encode(source).length>6000||selected.length>8||!project.current_version||readiness?.available!==true} onClick={()=>perform(async signal=>{requestedGeneration.current=generation;setValue(null);const r=await api.write(`${paths.configurations}/convert`,{source_text:source,source_asset_refs:assets.filter(a=>selected.includes(a.id)&&a.state==='approved').map(assetRef),project_revision:project.revision,guide_ref:{id:project.current_version.id,sha256:project.current_version.content_hash},disclosure:{enabled:true,reviewed_statement:CONVERSION_DISCLOSURE},limits},null,'POST',signal);setValue(r.conversion);},'Draft conversion requested. Inspect the result before applying.',{refresh:false})}>Suggest editable draft</Action></>:<p>Only the owner can approve disclosure and request conversion.</p>}
    {value&&<div className="rounded-md border p-3 space-y-3"><p role="status">Conversion: {words(value.state)}</p>{value.result?.code&&<p>{value.result.code}</p>}{['queued','converting'].includes(value.state)&&owner&&<Action variant="outline" disabled={busy} onClick={()=>perform(async signal=>setValue((await api.write(`${paths.configurations}/conversions/${value.id}/cancel`,{},null,'POST',signal)).conversion),'Conversion cancellation requested. Already reserved spend may remain.',{refresh:false})}>Cancel conversion</Action>}{value.result?.configuration&&<><ul className="space-y-2">{[...(value.result.assumptions||[]),...(value.result.warnings||[]),...(value.result.ambiguities||[]).map(a=>`${a.field}: ${a.question}`)].map((text,i)=><li key={i} className="break-words">{typeof text==='string'?text:pretty(text)}</li>)}</ul><details><summary className="min-h-11 cursor-pointer py-3">Original source provenance</summary><pre className="whitespace-pre-wrap break-words text-xs [overflow-wrap:anywhere]">{pretty(value.result.provenance)}</pre></details>
      <Action variant="outline" disabled={busy||conflict||!current||value.result.requires_review!==true||value.result.persisted!==false||value.result.execution_enabled!==false} onClick={()=>onDraft(value.result.configuration,value.source_text)}>Place suggestion in editor for review</Action><p>Applying edits the canonical local draft and preserves this conversion's original instructions. It retains the saved selection and requires validation, review and save. Reconcile an existing revision conflict first.</p>{!current&&<p role="status">This suggestion belongs to an earlier editor selection or draft. Review the current source and request a new suggestion before applying.</p>}</>}</div>}
  </div></details>;
}

function BrowserRun({base,paths,data,project,busy,setData,perform}) {
  const run=data.run,controls=data.controls||{},[view,setView]=useState(false),[viewer,setViewer]=useState(null),[clipboard,setClipboard]=useState(''),[exported,setExported]=useState(''),[artifacts,setArtifacts]=useState([]);
  const [reviewed,setReviewed]=useState({}),[verified,setVerified]=useState(false),[manualAuth,setManualAuth]=useState(false),[draftPreviews,setDraftPreviews]=useState({}),[sources,setSources]=useState([]);
  useEffect(()=>{setClipboard('');setExported('');setViewer(null);setView(false);setReviewed({});setVerified(false);setManualAuth(false);setArtifacts([]);setDraftPreviews({});setSources([]);},[run.id,run.attempt_id,run.fence]);
  const artifactFence=run.artifact_fence??run.fence;
  const root=`${paths.runs}/${run.id}`,scope={attempt_id:run.attempt_id,fence:artifactFence},active=!TERMINAL.includes(run.state),operate=project.own_role!=='viewer'&&!project.archived_at;
  const liveAvailable=controls.live_available===true||controls.can_live===true||controls.live?.enabled===true;
  const command=(name,body={})=>perform(async signal=>{await api.write(`${root}/${name}`,body,run.revision,'POST',signal);setData(await api.get(root,signal));},name==='release'?'Control released. The run remains paused until Resume.':`${words(name)} requested. Inspect the durable run state.`,{refresh:false});
  const pending=data.pending_approvals||[],report=data.report;
  return <Panel title={`Browser run · ${words(run.state)}`} icon={FileText} className="min-w-0" description="Server state, approval decisions, budget use and execution evidence.">
    <dl className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm"><Hash label="Run ID" value={run.id}/><Hash label="Attempt ID" value={run.attempt_id}/><Hash label="Pinned policy SHA-256" value={run.policy_sha256}/><div><dt>Revision / fence</dt><dd>{run.revision} / {run.fence}</dd></div></dl>
    {(run.uncertain||run.state==='uncertain')&&<p role="alert" className="rounded-md border p-3 text-sm">The outcome is uncertain. Compare receipts and the destination's actual state before taking further action. An uncertain external effect is never automatically repeated.</p>}
    {data.uncertainties?.length>0&&<section className="space-y-3"><h3 className="font-semibold">Uncertain outcomes</h3><ul className="space-y-3 text-sm">{data.uncertainties.map(item=><li key={item.id} className="rounded-md border p-3 space-y-2"><p className="break-words">{words(item.kind)} · {words(item.state)}{item.decision?` · ${words(item.decision)}`:''}</p>
      {operate&&!active&&item.state==='unresolved'&&(item.kind==='CLEANUP_UNVERIFIED'?<><p>A human assertion cannot verify cleanup. Request a fresh signed teardown receipt from the installed supervisor.</p><Action variant="outline" disabled={busy} onClick={()=>command('retry-cleanup')}>Retry verified cleanup</Action></>:<><p>Record what you verified at the destination. This records your decision and never repeats the external action.</p><div className="flex flex-wrap gap-2">{[['verified_effect','I verified the effect occurred'],['verified_no_effect','I verified no effect occurred'],['abandon_without_replay','Leave without repeating']].map(([decision,label])=><Action key={decision} variant="outline" disabled={busy} onClick={()=>command(`uncertainties/${item.id}/reconcile`,{decision})}>{label}</Action>)}</div></>)}
    </li>)}</ul></section>}
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm"><div className="rounded-md border p-3"><h3 className="font-medium">Budget ceilings</h3><dl>{Object.entries(run.budgets||{}).map(([key,value])=><div key={key} className="flex flex-wrap gap-x-2"><dt>{words(key)}:</dt><dd>{String(value)}</dd></div>)}</dl></div><div className="rounded-md border p-3"><h3 className="font-medium">Recorded use</h3><dl>{Object.entries(run.usage||{}).map(([key,value])=><div key={key} className="flex flex-wrap gap-x-2"><dt>{words(key)}:</dt><dd>{String(value)}</dd></div>)}</dl></div></div>
    <div className="flex flex-wrap gap-2"><Action variant="outline" disabled={busy} onClick={()=>perform(async signal=>setData(await api.get(root,signal)),'Run refreshed.',{refresh:false})}>Refresh run</Action>
      {operate&&<><Action variant="outline" disabled={busy||!controls.can_pause} onClick={()=>command('pause')}>Pause execution</Action><Action disabled={busy||!controls.can_resume} onClick={()=>command('resume')}>Resume execution</Action><Action variant="destructive" disabled={busy||!controls.can_cancel} onClick={()=>command('cancel')}>Stop browser run</Action></>}
    </div>
    {pending.length>0&&<section className="space-y-3"><h3 className="font-semibold">Human approvals</h3>{pending.map(approval=><article key={approval.id} className="rounded-md border p-3 space-y-3 text-sm min-w-0"><h4 className="font-medium">{approval.kind==='off_list_destination'?'Off-list destination request':approval.kind==='network_effect'?'Intercepted external request':approval.kind==='input_draft'?'Proposed form text':'Consequential action request'}</h4>
      <p className="break-all">Destination: {approval.origin||approval.destination||approval.packet?.operation?.url||'Inspect the pinned page and action below'}</p><p className="whitespace-pre-wrap break-words">Purpose: {approval.purpose||approval.candidate?.label||'No purpose supplied — inspect the typed action and pinned observation before deciding.'}</p>
      {approval.kind==='consequential_action'&&<details open><summary className="min-h-11 cursor-pointer py-3">Exact typed browser action</summary><pre className="whitespace-pre-wrap break-words text-xs [overflow-wrap:anywhere]">{pretty(approval.packet?.operation||approval.candidate?.operation)}</pre></details>}
      {approval.kind==='input_draft'&&<div className="space-y-3"><p>Review the exact proposed {approval.action_kind} text before approving it. Text approval prepares a candidate; the consequential action and external request still require their own approval.</p><Hash label="Exact draft artifact" value={approval.artifact_ref}/><Hash label="Exact input target" value={approval.target_ref}/><Hash label="Observed page URL hash" value={approval.url_sha256}/><Action variant="outline" disabled={busy||!approval.artifact_ref?.id} onClick={()=>perform(async signal=>{const blob=await verifyPrivateBlob(await api.download(`${root}/artifacts/${approval.artifact_ref.id}/content?attempt_id=${encodeURIComponent(run.attempt_id)}&fence=${artifactFence}&purpose=review`,signal),approval.artifact_ref),text=await blob.text();if(new TextEncoder().encode(text).length>65536)throw new Error('The proposed text exceeds the private preview limit.');setDraftPreviews(old=>({...old,[`${approval.id}:${approval.artifact_ref.sha256}`]:text}));},'Exact proposed text opened for private review.',{refresh:false})}>Open exact proposed text</Action>
        {Object.hasOwn(draftPreviews,`${approval.id}:${approval.artifact_ref?.sha256}`)&&<Field label="Private proposed form text" textarea rows={5} readOnly value={draftPreviews[`${approval.id}:${approval.artifact_ref.sha256}`]}/>}
      </div>}
      {approval.kind==='off_list_destination'&&<p>Approve only this exact destination and purpose for this attempt. The saved allowlist stays unchanged. Wildcards and permanent expansion are unavailable.</p>}
      {approval.kind==='network_effect'&&<div className="space-y-2"><p>Intercepted external request: {approval.method} · {approval.body_bytes} payload bytes · {approval.no_contact===true?'Held before contact':'Before-contact proof is missing'}. This request needs approval even while a person controls the browser.</p><Hash label="Exact request binding SHA-256" value={approval.binding_sha256}/><Hash label="Payload SHA-256" value={approval.body_sha256}/></div>}
      <dl className="space-y-2"><Hash label="Approval action SHA-256" value={approval.action_sha256}/><Hash label="Observation snapshot" value={approval.snapshot_ref}/><div><dt>Expires / status</dt><dd className="break-words">{approval.expires_at} · {words(approval.state)}</dd></div></dl>
      {operate&&<><label className="flex min-h-11 items-start gap-3 py-2"><input type="checkbox" className="mt-1 shrink-0" disabled={busy||approval.state!=='pending'} checked={!!reviewed[`${approval.id}:${approval.action_sha256}`]} onChange={e=>setReviewed({...reviewed,[`${approval.id}:${approval.action_sha256}`]:e.target.checked})}/><span>I reviewed the exact destination, purpose, typed action and action hash for this request.</span></label><div className="flex flex-wrap gap-2"><Action disabled={busy||!controls.can_approve||!reviewed[`${approval.id}:${approval.action_sha256}`]||approval.state!=='pending'||approval.kind!=='consequential_action'&&!approval.purpose||!Number.isFinite(Date.parse(approval.expires_at))||Date.parse(approval.expires_at)<=Date.now()||['network_effect','off_list_destination'].includes(approval.kind)&&approval.no_contact!==true||approval.kind==='input_draft'&&!Object.hasOwn(draftPreviews,`${approval.id}:${approval.artifact_ref?.sha256}`)} onClick={()=>command(`approvals/${approval.id}/decision`,approvalPayload(approval,run,'approve'))}>Approve this request</Action><Action variant="outline" disabled={busy||!controls.can_approve||approval.state!=='pending'} onClick={()=>command(`approvals/${approval.id}/decision`,approvalPayload(approval,run,'deny'))}>Deny this request</Action></div></>}
    </article>)}</section>}
    <section className="space-y-3"><h3 className="font-semibold">Live browser and manual sign-in</h3><p className="text-sm text-muted-foreground">Live viewing is separate from execution pause. Takeover pauses the agent and uses this session's verified controller. Releasing control leaves the run paused; Resume is explicit. Manual sign-in suppresses captures and page disclosure.</p>
      <div className="flex flex-wrap gap-2"><Action variant="outline" disabled={busy||!active||!liveAvailable||view&&controls.can_release} onClick={()=>setView(!view)}>{view?'Close live view':'Open live view'}</Action>
        {operate&&<><Action variant="outline" disabled={busy} onClick={()=>perform(async()=>{await requestAgentControl();await requestSudo();setVerified(true);},'Controller verification completed. Open the live view and take over explicitly.',{refresh:false})}>Verify controller</Action><Action disabled={busy||!controls.can_takeover||!verified||!manualAuth||!viewer} onClick={()=>command('takeover')}>Take over for manual sign-in</Action><Action variant="outline" disabled={busy||!controls.can_release} onClick={()=>command('release')}>Release browser control</Action></>}
      </div>{operate&&<label className="flex min-h-11 items-start gap-3 text-sm py-2"><input type="checkbox" className="mt-1 shrink-0" disabled={busy} checked={manualAuth} onChange={e=>setManualAuth(e.target.checked)}/><span>I will enter credentials directly in the controlled browser. I will not place them in the guide, instructions, clipboard transfer or model input.</span></label>}
      {view&&<SelectedLiveView base={base} runId={run.id} onViewer={setViewer} approvals={pending.length}/>}
      {!liveAvailable&&<p className="text-sm">Live transport is unavailable for this run. The server must verify the installed runner and relay before enabling it.</p>}
      {viewer&&<p className="text-xs text-muted-foreground">Live viewing connected.</p>}
      <BrowserAuthenticationReadback root={root} run={run} controls={controls} project={project} viewer={viewer} busy={busy} perform={perform} setData={setData}/>
      {controls.can_release&&<p className="text-sm">Release browser control before closing this live view. The agent stays paused after release.</p>}
    </section>
    <details className="rounded-md border p-3"><summary className="min-h-11 cursor-pointer py-3 font-medium">Private files and clipboard</summary><div className="space-y-3 text-sm"><p>Clipboard exchange uses an explicit private text field. The app never automatically reads or writes your device clipboard. Capture and release of sensitive files require human review.</p>
      <Action variant="outline" disabled={busy} onClick={()=>perform(async signal=>setArtifacts((await api.get(`${root}/artifacts?attempt_id=${encodeURIComponent(run.attempt_id)}&fence=${artifactFence}`,signal)).artifacts||[]),'Private artifact metadata loaded.',{refresh:false})}>List run artifacts</Action>
      <ul className="space-y-2">{artifacts.map(artifact=><RunArtifact key={artifact.id} artifact={artifact} root={root} scope={scope} run={run} busy={busy} reviewable={['owner','reviewer'].includes(project.own_role)} perform={perform} refresh={async signal=>setArtifacts((await api.get(`${root}/artifacts?attempt_id=${encodeURIComponent(run.attempt_id)}&fence=${artifactFence}`,signal)).artifacts||[])}/>)}</ul>
      {operate&&<><Field label="Text to explicitly import into the attempt clipboard" textarea rows={3} autoComplete="off" value={clipboard} maxLength={65536} disabled={busy||!controls.can_clipboard} onChange={e=>setClipboard(e.target.value)}/><Action variant="outline" disabled={busy||!active||!clipboard||!controls.can_clipboard} onClick={()=>perform(async signal=>{await api.write(`${root}/clipboard/import`,{...scope,text:clipboard},run.revision,'POST',signal);setClipboard('');},'Text imported into this attempt clipboard.',{refresh:false})}>Import this text</Action>
        {artifacts.filter(a=>a.kind==='clipboard'&&a.available).map(artifact=><Action key={artifact.id} variant="outline" disabled={busy||!active||!controls.can_clipboard} onClick={()=>perform(async signal=>setExported((await api.write(`${root}/clipboard/export`,{...scope,artifact_id:artifact.id},run.revision,'POST',signal)).text),'Attempt clipboard exported to this private field.',{refresh:false})}>Export attempt clipboard {artifact.id.slice(0,8)}</Action>)}
        {exported&&<><Field label="Explicitly exported clipboard text" textarea rows={4} readOnly value={exported}/><Action variant="outline" onClick={()=>setExported('')}>Clear exported text</Action></>}
      </>}
    </div></details>
    <details className="rounded-md border p-3"><summary className="min-h-11 cursor-pointer py-3 font-medium">Cited private page evidence</summary><div className="space-y-3 text-sm"><p>Evidence binds the captured page, original byte count, truncation, guide, consent and model calls. Private evidence is opened only through an explicit human review action.</p><Action variant="outline" disabled={busy||run.manual_auth} onClick={()=>perform(async signal=>setSources((await api.get(`${root}/sources`,signal)).sources||[]),'Private page evidence status checked.',{refresh:false})}>Check cited page evidence</Action><ul className="space-y-3">{sources.map(source=><RunSource key={source.id} source={source} root={root} scope={scope} busy={busy} manualAuth={run.manual_auth} perform={perform}/>)}</ul></div></details>
    {data.authentication_receipts?.length>0&&<details className="rounded-md border p-3"><summary className="min-h-11 cursor-pointer py-3 font-medium">Authentication confirmation receipts</summary><p className="text-sm">These references record human authentication confirmation. Other website changes remain unresolved.</p><ul className="space-y-3 text-sm">{data.authentication_receipts.map(receipt=><li key={receipt.id} className="rounded-md border p-3 min-w-0"><dl className="space-y-2"><Hash label="Confirmation ID" value={receipt.id}/><div><dt>Receipt state / acknowledged authentication requests</dt><dd>{words(receipt.state)} / {receipt.acknowledged_count??'Not confirmed'}</dd></div><Hash label="Confirmation request SHA-256" value={receipt.request_sha256}/><Hash label="Reviewed inventory SHA-256" value={receipt.inventory_sha256}/></dl></li>)}</ul></details>}
    <details className="rounded-md border p-3"><summary className="min-h-11 cursor-pointer py-3 font-medium">Receipts and cleanup evidence</summary><ul className="space-y-3 text-sm">{(data.receipts||[]).map((receipt,index)=><li key={receipt.id||index} className="rounded-md border p-3 min-w-0"><pre className="whitespace-pre-wrap break-words text-xs [overflow-wrap:anywhere]">{pretty(receipt)}</pre></li>)}</ul>{!data.receipts?.length&&<p className="text-sm">No verified receipts are available yet. A requested action alone does not prove completion or cleanup.</p>}</details>
    {!report&&data.report_visibility==='withheld'&&<p role="status" className="rounded-md border p-3 text-sm">The report is withheld because its private evidence or current disclosure consent is unavailable. Check cited page evidence for the exact source status. {data.report_code}</p>}
    {report&&<section className="space-y-3 text-sm"><h3 className="font-semibold">Run report</h3><p className="whitespace-pre-wrap break-words [overflow-wrap:anywhere]">{report.summary}</p>{report.uncertainty&&<p className="break-words">Uncertainty: {report.uncertainty}</p>}<ul className="space-y-2">{report.limitations?.map((text,index)=><li key={index} className="break-words">{text}</li>)}</ul><ul className="space-y-2">{report.citations?.map((citation,index)=>{const url=typeof citation==='string'?citation:citation.url,href=safeBrowserCitation(url);return <li key={index}>{href?<a href={href} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center break-all underline">{typeof citation==='string'?citation:citation.title||url}</a>:<span className="break-words">Evidence reference: {typeof citation==='string'?citation:pretty(citation)}</span>}</li>;})}</ul></section>}
  </Panel>;
}

function RunSource({source,root,scope,busy,manualAuth,perform}) {
  const [text,setText]=useState('');
  useEffect(()=>{setText('');},[source.id,source.content_sha256,scope.attempt_id,scope.fence,manualAuth]);
  return <li className="rounded-md border p-3 space-y-3 min-w-0"><p className="break-all">Source {source.id} · {words(source.state)}{source.code?` · ${source.code}`:''}</p><p className="break-words">{source.origin||'Origin unavailable'} · Captured {source.captured_at}</p><p>{source.artifact_ref?.byte_count} captured bytes of {source.original_bytes} original bytes · {source.truncated?'Truncated observation':'Full bounded observation'}</p><details><summary className="min-h-11 cursor-pointer py-3">Exact source provenance</summary><pre className="whitespace-pre-wrap break-words text-xs [overflow-wrap:anywhere]">{pretty(source)}</pre></details>
    <Action variant="outline" disabled={busy||manualAuth||source.state!=='available'||source.artifact_ref?.mime_type!=='text/plain'} onClick={()=>perform(async signal=>{const blob=await verifyPrivateBlob(await api.download(`${root}/artifacts/${source.artifact_ref.id}/content?attempt_id=${encodeURIComponent(scope.attempt_id)}&fence=${scope.fence}&purpose=review`,signal),source.artifact_ref);setText(await blob.text());},'Exact cited page evidence opened privately.',{refresh:false})}>Open exact cited page evidence<span className="sr-only"> {source.id}</span></Action>
    {text&&<><pre className="whitespace-pre-wrap break-words [overflow-wrap:anywhere] max-h-64 overflow-y-auto rounded-md bg-muted p-3">{text}</pre><Action variant="outline" onClick={()=>setText('')}>Clear cited page preview</Action></>}
  </li>;
}

function SelectedLiveView({base,runId,onViewer,approvals}) {
  const element=useRef(null),controller=useRef(null),[fullscreen,setFullscreen]=useState(false);
  useEffect(()=>{const value=createBrowserFullscreen({element:element.current,onChange:setFullscreen});controller.current=value;return()=>{value.close();controller.current=null;};},[runId]);
  return <div ref={element} tabIndex={-1} data-selected-browser-fullscreen={fullscreen} className={fullscreen?'fixed inset-0 z-[60] flex h-[100dvh] min-h-0 flex-col gap-3 overflow-hidden bg-background p-3':'space-y-3'}>
    <div className="flex shrink-0 items-center justify-between gap-2"><p className="font-medium">Selected browser</p><Action variant="outline" className="!min-h-11 !min-w-11" data-exit-browser-fullscreen={fullscreen?true:undefined} aria-label={fullscreen?'Exit fullscreen selected browser':'Open fullscreen selected browser'} onClick={()=>fullscreen?controller.current.exit():controller.current.enter()}>{fullscreen?<><Minimize2 className="h-4 w-4" aria-hidden="true"/>Exit fullscreen</>:<Maximize2 className="h-4 w-4" aria-hidden="true"/>}</Action></div>
    {approvals>0&&<p role="status" className="shrink-0 rounded-md border border-amber-500 p-3 text-sm">{approvals} pending request{approvals===1?'':'s'} held for review. {fullscreen?'Exit fullscreen to inspect the exact approval.':'Inspect the exact approval above before proceeding.'}</p>}
    <LiveBrowser base={base} runId={runId} expanded={fullscreen} endpoint={browserLiveEndpoint(base,runId)} onViewer={onViewer}/>
  </div>;
}

function RunArtifact({artifact,root,scope,run,busy,reviewable,perform,refresh}) {
  const [preview,setPreview]=useState(null),[text,setText]=useState(''),[rectangles,setRectangles]=useState('[]'),[reviewed,setReviewed]=useState(false),[opened,setOpened]=useState(false),[purpose,setPurpose]=useState('human_download');
  const artifactRoot=`${root}/artifacts/${artifact.id}`,query=`attempt_id=${encodeURIComponent(scope.attempt_id)}&fence=${scope.fence}`;
  useEffect(()=>{setReviewed(false);},[artifact.id,artifact.sha256,purpose,scope.fence]);
  useEffect(()=>{setOpened(false);setPreview(null);setText('');},[artifact.id,artifact.sha256,scope.attempt_id,scope.fence]);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  const image=['image/png','image/jpeg'].includes(artifact.mime_type),canRelease=['download','screenshot_derivative'].includes(artifact.kind);
  const releaseDecided=artifact.reviews?.some(r=>r.purpose===purpose&&r.sha256===artifact.sha256),modelBlocked=purpose==='model_input'&&TERMINAL.includes(run.state);
  return <li className="rounded-md border p-3 space-y-3 min-w-0 text-sm"><p className="break-words">{words(artifact.kind)} · {artifact.mime_type} · {artifact.byte_count} bytes · {words(artifact.state)}</p><Hash label="Artifact SHA-256" value={artifact.sha256}/>
    <Action variant="outline" disabled={busy||!artifact.available||run.manual_auth} onClick={()=>perform(async signal=>{const blob=await verifyPrivateBlob(await api.download(`${artifactRoot}/content?${query}&purpose=review`,signal),artifact);if(image){if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(blob));}else if(['text/plain','text/csv'].includes(artifact.mime_type))setText(await blob.text());else saveBlob(blob,`review-artifact-${artifact.id}`);setOpened(true);},'Exact artifact opened privately for review.',{refresh:false})}>Open exact artifact for review</Action>
    {preview&&<img src={preview} alt="Private artifact selected for human review" className="max-w-full h-auto rounded-md border"/>}{text&&<pre className="whitespace-pre-wrap break-words [overflow-wrap:anywhere] max-h-64 overflow-y-auto rounded-md bg-muted p-3">{text}</pre>}
    {artifact.reviews?.length>0&&<ul className="space-y-1">{artifact.reviews.map(review=><li key={review.purpose}>{words(review.purpose)}: {words(review.decision)} · exact artifact SHA-256 reviewed</li>)}</ul>}
    {(preview||text)&&<Action variant="outline" onClick={()=>{if(preview)URL.revokeObjectURL(preview);setPreview(null);setText('');}}>Clear private preview</Action>}
    {reviewable&&artifact.kind==='screenshot'&&<><Field label="Screenshot redaction rectangles (JSON array of x, y, width and height)" textarea rows={3} value={rectangles} disabled={busy||run.manual_auth} onChange={e=>setRectangles(e.target.value)}/><p className="text-xs text-muted-foreground">Use original image pixels. Review the normalized derivative again before releasing it. Masking selected rectangles does not automatically detect credentials or private data.</p><Action variant="outline" disabled={busy||run.manual_auth||!preview} onClick={()=>perform(async signal=>{let redactions;try{redactions=JSON.parse(rectangles);}catch{throw new Error('Redaction rectangles must be valid JSON.');}if(!Array.isArray(redactions))throw new Error('Use an array of redaction rectangles.');await api.write(`${artifactRoot}/normalize`,{...scope,redactions},run.revision,'POST',signal);await refresh(signal);},'Screenshot derivative created. Open and review it before release.',{refresh:false})}>Create normalized screenshot derivative</Action></>}
    {reviewable&&canRelease&&<><Choice label="Exact artifact release purpose" value={purpose} disabled={busy||run.manual_auth} onChange={e=>setPurpose(e.target.value)}><option value="human_download">Private human download</option><option value="model_input" disabled={TERMINAL.includes(run.state)}>Model content disclosure (active attempt only)</option></Choice><label className="flex min-h-11 items-start gap-3 py-2"><input type="checkbox" className="mt-1 shrink-0" disabled={busy||run.manual_auth||!opened||releaseDecided||modelBlocked} checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/><span>I reviewed: {ARTIFACT_REVIEW}. Purpose: {words(purpose)}.</span></label><div className="flex flex-wrap gap-2"><Action disabled={busy||run.manual_auth||!opened||!reviewed||releaseDecided||modelBlocked} onClick={()=>perform(async signal=>{await api.write(`${artifactRoot}/review`,{...scope,purpose,decision:'approve',reviewed_statement:ARTIFACT_REVIEW},run.revision,'POST',signal);await refresh(signal);},'Exact artifact release decision recorded for the selected purpose.',{refresh:false})}>Approve selected release</Action><Action variant="outline" disabled={busy||run.manual_auth||releaseDecided||modelBlocked} onClick={()=>perform(async signal=>{await api.write(`${artifactRoot}/review`,{...scope,purpose,decision:'reject',reviewed_statement:ARTIFACT_REVIEW},run.revision,'POST',signal);await refresh(signal);},'Exact artifact release rejected.',{refresh:false})}>Reject selected release</Action></div></>}
    {canRelease&&<Action variant="outline" disabled={busy||!artifact.available||run.manual_auth||!artifact.reviews?.some(r=>r.purpose==='human_download'&&r.decision==='approve'&&r.sha256===artifact.sha256)} onClick={()=>perform(async signal=>saveBlob(await verifyPrivateBlob(await api.download(`${artifactRoot}/content?${query}&purpose=download`,signal),artifact),`browser-artifact-${artifact.id}`),'Previously approved private artifact downloaded.',{refresh:false})}>Download approved artifact</Action>}
  </li>;
}
