import { useCallback, useEffect, useState } from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import { BookOpen, History, Paperclip, Rocket } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Action, Panel } from './shared';
import { BrowserAgents } from './BrowserAgents';
import { ProjectTaskOverview } from './ProjectTaskOverview';
import { NewProjectButton, ProjectBrowser } from './ProjectSurface';
import { useBranding } from '@/lib/branding';

function WorkspaceDisclosure({label,forceOpen=false,children}) {
  const [opened,setOpened]=useState(forceOpen),[loaded,setLoaded]=useState(forceOpen);
  useEffect(()=>{if(forceOpen){setOpened(true);setLoaded(true);}},[forceOpen]);
  return <details open={opened} onToggle={event=>{setOpened(event.currentTarget.open);if(event.currentTarget.open)setLoaded(true);}}><summary className="min-h-11 cursor-pointer py-3 font-semibold">{label}</summary>{loaded&&children}</details>;
}

export function ProjectWorkspace({project,base,taskData,section,params,setParams,onChanged,openSection,projects,events,loadMore,busy,error,message,guide,versions,records,manualRecords,access,metadata,onUnavailable,websiteReviews}) {
  const context=useOutletContext() || {}, [menu,setMenu]=useState(false),[editGuide,setEditGuide]=useState(false);
  const branding=useBranding();
  useEffect(()=>{context.setChromeless?.(true);return()=>context.setChromeless?.(false);},[context.setChromeless]);
  const requested=params.get('panel');
  const panel=['activity','browser','resources','details'].includes(requested)?requested:['Guide','Versions','Runs','Agent runs','Website reviews'].includes(section)?'resources':['Details','Access'].includes(section)?'details':section==='Agents'?'browser':'activity';
  const resourceTab=['training','history'].includes(params.get('resource'))?params.get('resource'):['Versions','Runs','Agent runs','Website reviews'].includes(section)?'history':'guide';
  const onSelect=useCallback(name=>setParams(old=>{const next=new URLSearchParams(old);next.set('panel',name);next.delete('browser_panel');return next;},{replace:true}),[setParams]);
  const onOpenRun=(id,options)=>setParams(old=>{const next=new URLSearchParams(old);next.set('browser_run',id);next.set('panel',options?.review?'activity':'browser');next.set('section','Agents');if(options?.review)next.set('browser_panel','review');else next.delete('browser_panel');return next;});
  const selectResource=name=>setParams(old=>{const next=new URLSearchParams(old);next.set('resource',name);next.set('panel','resources');return next;},{replace:true});
  const openAdvanced=()=>setParams(old=>{const next=new URLSearchParams(old);next.set('panel','resources');next.set('resource','training');next.set('advanced','1');return next;},{replace:true});
  const config=taskData.task.configuration?.configuration;
  const resources=<><h2 className="text-2xl font-semibold">Resources</h2><nav aria-label="Resource sections" className="flex border-b">{[['guide','Guide'],['training','Training & files'],['history','History']].map(([name,label])=><button type="button" key={name} aria-pressed={resourceTab===name} onClick={()=>selectResource(name)} className={`min-h-11 min-w-0 flex-1 border-b-2 px-1 text-sm ${resourceTab===name?'border-primary text-foreground font-semibold':'border-transparent text-muted-foreground'}`}>{label}</button>)}</nav>
    <div hidden={resourceTab!=='guide'} className="space-y-4"><Panel title={project.current_version?`Approved guide v${project.current_version.version_number}`:'Guide'} icon={BookOpen} actions={<Action variant="outline" onClick={()=>setEditGuide(true)}>Edit / review guide</Action>}><div className="space-y-3 text-sm [&_h2]:pt-3 [&_h2]:font-semibold [&_ol]:list-decimal [&_ol]:pl-5 [&_ul]:list-disc [&_ul]:pl-5 [&_a]:break-all [&_a]:underline"><ReactMarkdown>{project.current_version?.instructions||config?.work.instructions||project.description||'No guide saved yet.'}</ReactMarkdown></div></Panel><Action variant="outline" className="w-full justify-start gap-2" onClick={()=>selectResource('training')}><Paperclip className="h-4 w-4" aria-hidden="true"/>Training & reference files</Action><Action variant="outline" className="w-full justify-start gap-2" onClick={()=>selectResource('history')}><History className="h-4 w-4" aria-hidden="true"/>Run and guide history</Action></div>
    <div hidden={resourceTab!=='history'} className="space-y-4"><WorkspaceDisclosure label="Guide version history" forceOpen={section==='Versions'}>{versions}</WorkspaceDisclosure><WorkspaceDisclosure label="Manual work records" forceOpen={section==='Runs'}>{manualRecords}</WorkspaceDisclosure><WorkspaceDisclosure label="Historical agent runs" forceOpen={section==='Agent runs'}>{records}</WorkspaceDisclosure>{websiteReviews&&<WorkspaceDisclosure label="Website review reports" forceOpen={section==='Website reviews'}>{websiteReviews}</WorkspaceDisclosure>}</div>
  </>;
  const notice=<>{error&&<p role="alert" className="rounded-md border border-destructive p-3 text-sm text-foreground break-words">{error}</p>}{(busy||message)&&<p role="status" className="text-sm">{busy?'Working…':message}</p>}</>;
  return <div className="operations-ui flex min-h-0 min-w-0 flex-1 flex-col" data-project-workspace>
    <header className="flex shrink-0 items-center justify-between gap-2 border-b px-4 py-3 lg:hidden"><Link to="/operational-projects" className="flex min-h-11 items-center gap-2 font-semibold text-xl"><>{branding.logo?<img src={branding.logo} alt="" className="h-6 w-6 rounded object-contain"/>:<Rocket className="h-6 w-6 text-primary" aria-hidden="true"/>}{branding.name}</></Link><button type="button" className="min-h-11 px-2 text-sm text-muted-foreground" onClick={()=>setMenu(true)}>Projects</button></header>
    <nav aria-label="Project breadcrumb" className="hidden shrink-0 items-center gap-2 px-4 text-sm text-muted-foreground lg:flex"><Link className="inline-flex min-h-11 items-center underline" to="/operational-projects">Projects</Link><span aria-hidden="true">/</span><span className="min-w-0 truncate">{project.name}</span><button type="button" className="ml-auto min-h-11 px-2 underline" onClick={()=>setMenu(true)}>Switch project</button></nav>
    <ProjectTaskOverview project={project} taskData={taskData} executionEnabled activePanel={panel} onOpenAdvanced={openAdvanced} onChanged={onChanged} onOpenRun={onOpenRun} openSection={openSection} render={({activity,details,dialogs,dialogOpen})=><BrowserAgents base={base} project={project} onChanged={onChanged} browserRunId={params.get('browser_run')} initialReview={params.get('browser_panel')==='review'} workspace={{project,onUnavailable,dialogOpen:dialogOpen||menu||editGuide,advanced:params.get('advanced')==='1',panel,onSelect,onOpenRun,resourceTab,resources,activity:<>{activity}<section className="space-y-3"><h2 className="text-lg font-semibold">Activity</h2>{!events.events.length&&<p className="text-sm text-muted-foreground">Run this task to see its activity here.</p>}<ul className="space-y-2">{events.events.map(row=><li key={row.id} className="rounded-md border bg-card p-3 text-sm"><p className="break-words">{row.action.replaceAll('_',' ')}</p><time className="text-xs text-muted-foreground">{row.created_at}</time></li>)}</ul>{events.next_cursor&&<Action variant="outline" disabled={busy} onClick={loadMore}>Load older activity</Action>}</section></>,details:<><h2 className="text-2xl font-semibold">Details</h2>{details}<WorkspaceDisclosure label="Access & connections" forceOpen={section==='Access'}>{access}</WorkspaceDisclosure><WorkspaceDisclosure label="Project information">{metadata}</WorkspaceDisclosure></>,dialogs,notice,onOpenNav:()=>setMenu(true)}}/>}/>
    <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="operations-dialog max-h-[90dvh] sm:max-w-xl"><DialogHeader className="pr-8"><DialogTitle>Projects & navigation</DialogTitle><DialogDescription>Switch projects or return to the main navigation.</DialogDescription></DialogHeader><div className="flex flex-wrap gap-2"><NewProjectButton/><Action variant="outline" onClick={()=>{setMenu(false);context.openNav?.();}}>Main menu</Action><Link to="/operational-projects" className="min-h-11 inline-flex items-center underline">All projects</Link></div><ProjectBrowser projects={projects.some(p=>p.id===project.id)?projects:[project,...projects]} selectedId={project.id}/></DialogContent></Dialog>
    <Dialog open={editGuide} onOpenChange={setEditGuide}><DialogContent className="operations-dialog max-h-[90dvh] sm:max-w-3xl"><DialogHeader className="pr-8"><DialogTitle>Guide editor</DialogTitle><DialogDescription>Guide revisions and approvals keep their existing version history.</DialogDescription></DialogHeader>{guide}</DialogContent></Dialog>
  </div>;
}
